- mteb/abstasks/AbsTaskClassification.py
Fixes `WARNING: main score accuracy not found in scores dict_keys(['en', 'de', 'es', 'fr', 'ja', 'zh'])`
> Fix main score for Classification tasks

- mteb/tasks/STS/SickrSTS.py
Fixes #22.
Changes `hf_hub_name` of Sick-R STS task from `mteb/biosses-sts` to `mteb/sickr-sts`.
> Fix `hf_hub_name` of Sick-R STS task

- mteb/tasks/Reranking/MindSmallReranking.py
Two other notes:
- The renaming can create confusion as there exists a test set just that I assume we don't have the labels - I clarified it [here](https://huggingface.co/datasets/mteb/mind_small/discussions/2)
- MIND uses AUC & MRR & NDCG scores, not MAP, see https://msnews.github.io/
> Fix Mind Reference

- mteb/abstasks/AbsTaskBitextMining.py
Fixes https://github.com/embeddings-benchmark/mteb/issues/51
The current issue is that not all queries may be a part of gold, thus `max([i for (i, j) in gold]) < len(sentence1)` for BUCC.
> Default to 1-indexed gold

- mteb/evaluation/MTEB.py
As we set task langs to an empty list in `__init__` it never is `None`
> Fix no langs

- mteb/abstasks/AbsTaskRetrieval.py
- mteb/abstasks/BeIRTask.py
Somewhat fixes https://github.com/embeddings-benchmark/mteb/issues/66 by falling back to the old data loader, i.e. we do not support DPRES + CQADupstack.
This is a BEIR limitation, so I opened an issue here: https://github.com/beir-cellar/beir/issues/114 Once it's fixed we can remove this hopefully.
> Fallback to old dataloader for cqadupstack

- mteb/evaluation/MTEB.py
This is quite useful when parsing results to avoid having to extract it from the filename
Also is there any major use case for `save_suffix`? Else let's remove it
> Add ds name to res dict

- mteb/abstasks/AbsTask.py
Add the missing @property annotation to AbsTask.description, which prevents typing errors (when checked with mypy) in subclasses.
> Add @property annotation to description method of AbsTask

- setup.py
Bump version ID and update PyPI after adding additional tasks in #124. Given #126 changes the behaviour of the `MTEB` function I have bumped the minor version.
> Bump version ID and update PyPI

- mteb/abstasks/AbsTaskRetrieval.py
- mteb/abstasks/BeIRTask.py
- mteb/evaluation/MTEB.py
- mteb/logging.py
- mteb/tasks/Classification/NorwegianParliamentClassification.py
- mteb/tasks/Classification/__init__.py
- scripts/retrieval.slurm
- scripts/retrieval_multigpu.py
Fixes https://github.com/embeddings-benchmark/mteb/issues/103
Test using
```
pip install git+https://github.com/NouamaneTazi/beir@nouamane/better-multi-gpu
torchrun --nproc_per_node=2 scripts/retrieval_multigpu.py
```
> Support Multi-node Evaluation

- mteb/cmd.py
Currently the command line tool is not working because of a change made by #131. This might be fixed if the refactoring of the command line tool propose in #7 will be ever merged. However, since this PR is work in progress for over one year and not finished. I made this small fix.
At the moment you get the following error message when you try to run the mteb comment (version on main branch) because `args.task_langs` does not exsists:
```python
Traceback (most recent call last):
File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/home/michael/workspace/mteb-long-documents/mteb/cmd.py", line 124, in <module>
main()
File …
```
> fix: add missing task-langs attribute

- mteb/tasks/Retrieval/MSMARCOv2Retrieval.py
The `MSMARCOV2` class lists the `eval_splits` as `["dev1", "dev2"]`, but the actual names of the `.tsv` files are instead `["dev", "dev2"]`. As is, a `ValueError` is raised:
```python
ValueError: File /your_path_to_hf_cache/BeIR/msmarco-v2/qrels/dev1.tsv not present! Please provide accurate file.
```
The correct `dev.tsv` file name can be checked against [the url](https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/) used to [download the dataset](https://github.com/garrett361/mteb/blob/a1dbe2dc8ab468ced4e8e82cf283abb4ba31e16b/mteb/abstasks/BeIRTask.py#L50-L50).
> fix: msmarco-v2 uses dev.tsv, not dev1.tsv

- mteb/evaluation/evaluators/RerankingEvaluator.py
Tested by comparing `use_batched_encoding=True` and `use_batched_encoding=False` on 'multi-qa-MiniLM-L6-cos-v1' sbert model
```json
{
"dataset_revision": "2000358ca161889fa9c082cb41daa8dcfb161a54",
"mteb_dataset_name": "AskUbuntuDupQuestions",
"mteb_version": "1.1.2.dev0",
"test": {
"evaluation_time": 1.23,
"map": 0.6309199068762668,
"mrr": 0.7608055225783756
}
}
{
"dataset_revision": "3bdac13927fdc888b903db93b2ffdbd90b295a69",
"mteb_dataset_name": "MindSmallReranking",
"mteb_version": "1.1.2.dev0",
"test": {
"evaluation_time": 687.07,
"map": 0.30894071459751266,
"mrr": 0.31965886150526257
}
}
{
"dataset_revision": "d3c5e1fc0b855ab6097bf1cda04dd73947d7caab",
"mteb_dataset_name": "SciDocsRR",
"mteb_version": "1.1.2.dev0",
"test": {
"evaluation_time": 18.71,
"map": 0.7427669440147513, …
```
> fix RerankingEvaluator's compute_metrics_individual

- mteb/tasks/Clustering/BigPatentClustering.py
- mteb/tasks/Clustering/WikiCitiesClustering.py
- mteb/tasks/Clustering/__init__.py
- mteb/tasks/Retrieval/NarrativeQARetrieval.py
- mteb/tasks/Retrieval/__init__.py
We are developing models with long context length but noticed that MTEB contains mostly datasets with only a small portion of long text values (beyond 512 tokens). We prepared 3 datasets as evaluation tasks (2 clustering and 1 retrieval task). 
Contains Wikipedia articles of cities with the aim of clustering them by country.
Patent documents can be clustered by their corresponding Cooperative Patent Classification (CPC) code, only selecting patents that belong to a single CPC.
The original objective of the dataset is reading comprehension. We reformulate this as a retrieval task, whereby each question is answered in one document. This is particularly challenging because the questions relate to paragraphs or sentences found in the middle and end of the long document, requiring a long …
> Add Long Document Evaluation Datasets

- mteb/tasks/BitextMining/NorwegianCourtsBitextMining.py
- mteb/tasks/BitextMining/__init__.py
This is mainly important for the [Scandinavian Embedding Benchmark](https://kennethenevoldsen.github.io/scandinavian-embedding-benchmark/), but generally speaking, all multiligual embeddings should aim to encode sentences in Bokmål and Nynorsk relatively close to each other, as they are two written variants of the same language.
> Added Norwegian Bokmål-Nynorsk bitext mining task

- mteb/abstasks/AbsTaskRetrieval.py
- mteb/abstasks/BeIRTask.py
- mteb/evaluation/MTEB.py
This is a small fix for #177. Previously, DRPES was selected based on the presence of the `RANK` environment variable. This led to issues for us during training with pytorch lightning. 
In this PR, we allow passing a keyword argument `parallel_retrieval` to `MTEB.run`, which is further processed by `AbsRetrieval.evaluate` and `BeIRTask.load_data` to toggle the selection of DRES/DRPES. As a consequence, we also need to  pass all kwargs of `MTEB.run` to `task.load_data`. I am not sure whether this could possibly lead to problems in other parts of MTEB.
> Fix selection of DRES/DRPES

- mteb/abstasks/AbsTaskRetrieval.py
- mteb/tasks/Retrieval/MultiLongDocRetrieval.py
- mteb/tasks/Retrieval/__init__.py
We introduce a new multilingual long-document retrieval task **MultiLongDocRetrieval** in this [paper](https://arxiv.org/abs/2402.03216). We hope to add it to MTEB.
The previous code in `AbsTaskRetrieval.py` does not support multilingual retrieval. Therefore, we implement this by referring to the code in `AbsTaskClassification.py`.
We have already tested the modified code, and it is working fine.
> Add MultiLongDocRetrieval task to MTEB.

- mteb/tasks/BitextMining/NorwegianCourtsBitextMining.py
I created the task originally by copying code over from another task, and accidentally left its specific git revision in there.
The issue has already been addressed in [SEB](https://kennethenevoldsen.github.io/scandinavian-embedding-benchmark/).
> Fixed missing revision error on Norwegian Bitext Mining

- tests/test_all_abstasks.py
I noticed test collection was quite slow. Turns out one of the tests was run on import, i.e. as soon as pytest collects the tests.
Instead, I have wrapped it as its own test, and collection is now much faster!
> tests: do not run tests on collection

- .github/workflows/python-package.yml
- .gitignore
- README.md
- mteb/cmd.py
- requirements.dev.txt
- results/sentence-transformers__all-MiniLM-L6-v2/Banking77Classification.json
- results/sentence-transformers__all-MiniLM-L6-v2/BornholmBitextMining.json
- results/sentence-transformers__all-MiniLM-L6-v2/model.json
- setup.py
This is a suggested change. The goal is to make it easier to add model evaluations along with a dataset (as a kind of test).
This includes a few changes:
- the results folder is now added to contain results using the form `results/{model_name}/{task_results}`
- Changes CLI to follow this format
- Additionally also adds a model_meta.json with the model_name, time of run and versions during run.
> Added model results to repo and updated CLI to create consistent folder structure.

- Makefile
- tests/test_all_abstasks.py
* Make tests run in parallel by default
* Switch BitextMining test to smaller dataset (Borholm)
* Switch to a faster embedding model
> tests: speed up tests

- .github/workflows/test.yml
- docs/mmteb/points.md
- pyproject.toml
Added windows using python 3.8 to test suite to ensure that things run on windows as well.
> ci: Added windows to test suite

- mteb/tasks/PairClassification/multilingual/PawsX.py
Fix for issue #309. Eval splits didn't have the correct name.
> Fix PawsX eval splits

- mteb/abstasks/TaskMetadata.py
- tests/test_TaskMetadata.py
This small PR fixes the logging for the missing dataset revision:
- Use the current logger instead of the root logger
- Adds the path of the dataset to the log. Previously, let's say you have in your code base many datasets with missing revision, it would simply log the message a few times at import time without telling you which datasets are problematic.
> Improve logging when the revision is None

- scripts/run_mteb_french.py
Related to this issue #334
This PR removes bitext mining tasks from the French evaluation script, since these tasks need two input languages to run (which was making Flores run forever btw). They should be run separately. 
The scores are also not included in the French leaderboard since it concerns 2 languages and not one.
> Removing bitext mining tasks from fr evaluation script

- docs/mmteb/points.md
- mteb/abstasks/TaskMetadata.py
- mteb/tasks/Classification/__init__.py
- mteb/tasks/Classification/ita/ItaHateClassification.py
- results/intfloat__multilingual-e5-small/ItaHateClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/ItaHateClassification.json
(just fixed linting from orignal PR)
* add italian HateSpeech dataset
* add points
* update dialect, socioeconomic status, domains and points
* add PR review points
* add task_domain for constructed data + rerun models
* update points
* minor fix
* merge points from main
* add review points to main
> fix: add italian HateSpeech dataset (#385)

- docs/mmteb/points.md
Only 1 point instead of 2 points were assigned (ref: `docs/mmteb/readme.md`)
- https://github.com/embeddings-benchmark/mteb/pull/403
- https://github.com/embeddings-benchmark/mteb/pull/411
- https://github.com/embeddings-benchmark/mteb/pull/414
- https://github.com/embeddings-benchmark/mteb/pull/421
Luckily there aren't a lot yet 😅
> docs: Add missing points from PR reviews

- docs/mmteb/points.md
Seems like we have wrongly assigned review points as 1 point rather than 2. 
Thus I have duplicated all the review scores. This might lead. I realized this yesterday and have had 2 prs with 2 points (thus the subtraction in my score).
Let me know if you find any issues in the review scores.
Adding pr reviewers here to let people know about the change, but will merge it in to avoid merge conflicts.
> docs: Updated review points

- pyproject.toml
I was trying to use this package with Pydantic 1.10, and realized I had an import error because it doesn't have `BeforeValidator`. I saw this was available from Pydantic 2, so I set the minimum to 2.
Note I didn't check further, so chances are that a greater minimum is needed (e.g., 2.1).
> Set the min Pydantic version to 2

- .github/workflows/mmteb.yml
- docs/mmteb/points/473.jsonl
Fix for  #471 and https://github.com/embeddings-benchmark/mteb/commit/22ca0e4e941b14d62d543d866fb4daecacdd2805.
1. For users without MTEB push access, the `check-points` CI step will face this error in the PR:
```
Error: Input required and not supplied: token
```
2. Even when new points files were added, the ci workflow did not register changes at the `git diff` step, so it always exits.
Fix is to 
1. split check points into 2 jobs: a) check points, b) create table
2. only run che when pushing to the main branch.
3. run `git add` after `git diff`
> ci: Only create table in ci when pushing to main

- .github/workflows/mmteb.yml
While the fix/feature PR would run smoothly through CI, the github-actions bot would fail on the `create-table` job, specifically on the last step. 
```
nothing to commit, working tree clean
Error: Process completed with exit code 1.
```
Use an if statement to explicitly check the exit status of `git diff --quiet` and allow proper branching based on whether changes are detected or not.
Also replaced `make install` with pip installing only the needed packages to speed up CI.
> ci: Use if-else instead for points table creation

- docs/mmteb/points/486.jsonl
- mteb/tasks/Clustering/multilingual/WikiClusteringP2P.py
- results/intfloat__multilingual-e5-small/WikiClusteringP2P.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/WikiClusteringP2P.json
As described in the title, I have updated WikiClusteringP2P with 10 brand new languages (wuhuu!). These have the following codes: 
- bos-Latn
- cat-Latn
- ces-Latn
- eus-Latn
- ilo-Latn
- kur-Latn
- min-Latn
- mlt-Latn
- sco-Latn
- wln-Latn
Apart from wln, all of the languages are European and all of them are from low to extremely low resource. 
I have also somewhat reduced the size of each dataset from 10 x 1024 to 10 x 512 - as can be seen in the results, the std is still fairly slim. 
Maybe it makes sense for @KennethEnevoldsen to take a look, as you're already familiar?
> Update WikiClusteringP2P with 10 new languages

- mteb/abstasks/AbsTask.py
- mteb/tasks/Classification/fas/PersianFoodSentimentClassification.py
- results/intfloat__multilingual-e5-small/PersianFoodSentimentClassification.json
Proposed fix for issue #520, the proposition is to update the splits of the current dataset dict instead of creating a new one. This should not update splits that are not mentioned in `splits` argument.
> fix: update current dict and do not remove other splits

- docs/mmteb/points/535.jsonl
- mteb/tasks/Classification/__init__.py
- mteb/tasks/Classification/urd/UrduRomanSentimentClassification.py
- results/intfloat__multilingual-e5-small/UrduRomanSentimentClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/UrduRomanSentimentClassification.json
> Add Urdu Latin Sentiment Classification Dataset

- mteb/tasks/Classification/eng/LegalBenchClassification.py
- results/intfloat__multilingual-e5-small/CUADCapOnLiabilityLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/CUADChangeOfControlLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/CUADCompetitiveRestrictionExceptionLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/CUADCovenantNotToSueLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/CUADEffectiveDateLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/CUADExclusivityLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/CUADExpirationDateLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/CUADGoverningLawLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/CUADCapOnLiabilityLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/CUADChangeOfControlLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/CUADCompetitiveRestrictionExceptionLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/CUADCovenantNotToSueLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/CUADEffectiveDateLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/CUADExclusivityLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/CUADExpirationDateLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/CUADGoverningLawLegalBenchClassification.json
Reason for dataset addition: Showcases the model's performance on the [LegalBench](https://hazyresearch.stanford.edu/legalbench/) datasets, enabling evaluation on domain-specific legal texts.
Follow up to #579
- All the `LegalBenchClassification` tasks have been reorganized for better readability. Add additional citations for a few `ContractNLI` tasks.
- The descriptions for all the tasks have been updated to include more information about the task.
The following 8 datasets have been added in this PR:
1. [CUAD Cap on Liability](https://hazyresearch.stanford.edu/legalbench/tasks/cuad_cap_on_liability.html)
2. [CUAD Change of Control](https://hazyresearch.stanford.edu/legalbench/tasks/cuad_change_of_control.html)
3. [CUAD Competitive Restriction …
> fix: Add LegalBench datasets - 4

- README.md
- docs/mmteb/points.md
- docs/mmteb/points/393.jsonl
- mteb/tasks/Retrieval/eng/LEMBNeedleRetrieval.py
- mteb/tasks/Retrieval/eng/LEMBPasskeyRetrieval.py
Hi there, I'm just adding more meta data for LongEmbed. I have also added a `393.jsonl` file in the points folder, though not quite sure about whether I have calculated the scores correctly. Relevant PR is #393
> add info for LongEmbed

- docs/mmteb/points/637.jsonl
- mteb/tasks/Retrieval/multilingual/MLQARetrieval.py
- mteb/tasks/STS/__init__.py
- mteb/tasks/STS/fao/FaroeseSTS.py
- results/intfloat__multilingual-e5-small/FaroeseSTS.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/FaroeseSTS.json
Reason for dataset addition: Adding support for Faroese (new language) under the STS task category.
> Adding FaroeseSTS dataset

- docs/mmteb/points/644.jsonl
- mteb/tasks/Classification/eng/LegalBenchClassification.py
- results/intfloat__multilingual-e5-small/CUADRenewalTermLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/CUADRevenueProfitSharingLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/CUADRofrRofoRofnLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/CUADSourceCodeEscrowLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/CUADTerminationForConvenienceLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/CUADThirdPartyBeneficiaryLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/CUADUncappedLiabilityLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/CUADUnlimitedAllYouCanEatLicenseLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/CUADVolumeRestrictionLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/CUADWarrantyDurationLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/CUADRenewalTermLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/CUADRevenueProfitSharingLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/CUADRofrRofoRofnLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/CUADSourceCodeEscrowLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/CUADTerminationForConvenienceLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/CUADThirdPartyBeneficiaryLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/CUADUncappedLiabilityLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/CUADUnlimitedAllYouCanEatLicenseLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/CUADVolumeRestrictionLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/CUADWarrantyDurationLegalBenchClassification.json
Reason for dataset addition: Showcases the model's performance on the [LegalBench](https://hazyresearch.stanford.edu/legalbench/) datasets, enabling evaluation on domain-specific legal texts.
Follow up to #622 
The following 10 datasets have been added in this PR:
1. [CUAD Renewal Term](https://hazyresearch.stanford.edu/legalbench/tasks/cuad_renewal_term.html)
2. [CUAD Revenue Profit Sharing](https://hazyresearch.stanford.edu/legalbench/tasks/cuad_revenue-profit_sharing.html)
3. [CUAD Rofr Rofo Rofn](https://hazyresearch.stanford.edu/legalbench/tasks/cuad_rofr-rofo-rofn.html)
4. [CUAD Source Code Escrow](https://hazyresearch.stanford.edu/legalbench/tasks/cuad_source_code_escrow.html)
5. [CUAD Termination For Convenience](https://hazyresearch.stanford.edu/legalbench/tasks/cuad_termination_f …
> fix: Add LegalBench datasets - 7

- docs/mmteb/points/716.jsonl
- mteb/tasks/STS/__init__.py
- mteb/tasks/STS/rus/RUParaPhraserSTS.py
- results/intfloat__multilingual-e5-small/RUParaPhraserSTS.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/RUParaPhraserSTS.json
This is a new STS dataset in a language that has not been covered yet (Russian).
> fix: Add RUParaPhraserSTS

- mteb/tasks/Reranking/eng/MindSmallReranking.py
Following https://github.com/embeddings-benchmark/mteb/issues/747
Converting .gz to .zip fixed the issue
> fix: MindSmallReranking not loading

- mteb/tasks/Classification/tha/WisesightSentimentClassification.py
You might have noticed that tests have been failing since earlier today. This is due to a dataset path that has been redirected. Changing the path fixes the issue. We may want to have better automated fix in the future.
> Quick fix CI/CD issue due to dataset redirect

- mteb/tasks/Retrieval/slk/SlovakSumRetrieval.py
Errors from main:
```
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================= slowest 5 durations ==============================
14.63s call     tests/test_mteb.py::test_mteb_task[average_word_embeddings_levy_dependency-TwentyNewsgroupsClustering]
11.19s call     tests/test_mteb.py::test_two_mteb_tasks
10.66s call     tests/test_mteb.py::test_mteb_task[average_word_embeddings_levy_dependency-Banking77Classification]
10.61s call     tests/test_mteb_rerank.py::test_mteb_rerank
9.44s call     tests/test_mteb.py::test_mteb_task[average_word_embeddings_levy_dependency-SciDocsRR]
=========================== short test summary info ============================
FAILED tests/test_all_abstasks.py::test_dataset_availability - AssertionError: Datasets not …
```
> ci: fix slovaksum dir

- docs/mmteb/points/758.jsonl
- mteb/tasks/STS/pol/PolishSTS.py
* The Polish STS had missing metadata. This commit should fix the situation.
> fix: Metadata for Polish STS

- mteb/tasks/Reranking/fra/AlloprofReranking.py
- mteb/tasks/Reranking/fra/SyntecReranking.py
- pyproject.toml
- results/intfloat__multilingual-e5-small/AlloprofReranking.json
- results/intfloat__multilingual-e5-small/SyntecReranking.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/AlloprofReranking.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/SyntecReranking.json
Update the French reranking datasets (alloprof & syntec) by sampling the negative documents using BM25.
Indeed, using an embedding model to sample negative documents through cosine similarity could induce a bias favoring the models that are trained on the same data as the model used to generate the dataset. Moreover, it makes evaluation of the reranking of the latter irrelevant.
> update reranking Fr tasks

- docs/mmteb/points/812.jsonl
- mteb/abstasks/AbsTaskMultilabelClassification.py
- tests/test_mteb.py
This fixes bug reported in https://github.com/embeddings-benchmark/mteb/issues/810 and caused by https://github.com/embeddings-benchmark/mteb/pull/759 .
Not sure if this is the best approach but since old eval_split was working I just copied it from classification abstask.
> Fixes MultilabelClassification eval_split

- README.md
- mteb/__init__.py
- mteb/abstasks/TaskMetadata.py
- mteb/encoder_interface.py
- mteb/evaluation/MTEB.py
- mteb/languages.py
- mteb/overview.py
- pyproject.toml
The intention here is to:
1) move complexity away from the MTEB object
2) ensure that the filters are applied in the same way across the benchmark (currently MTEB filters slightly differently due to not handling the new language codes)
3) deprecate filtering in MTEB going forward (only with a warning atm.)
4) doing it in a two step fashion ensure that users are able to inspect the tasks before they are run (also allow for much more custom filtering on the user end)
> replace get_tasks as default filtering.

- mteb/tasks/Classification/eng/YelpReviewFullClassification.py
- mteb/tasks/Classification/kor/KlueTC.py
- mteb/tasks/PairClassification/kor/KlueNLI.py
- mteb/tasks/PairClassification/multilingual/PawsX.py
- mteb/tasks/Retrieval/eng/NarrativeQARetrieval.py
- mteb/tasks/STS/kor/KlueSTS.py
https://github.com/embeddings-benchmark/mteb/actions/runs/9351588385/job/25737732045?pr=871
```
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================= slowest 5 durations ==============================
22.84s call     tests/test_mteb_rerank.py::test_reranker_same_ndcg1
14.42s call     tests/test_mteb.py::test_mteb_task[average_word_embeddings_levy_dependency-TwentyNewsgroupsClustering]
14.01s call     tests/test_cli.py::test_run_task
13.36s call     tests/test_reproducible_workflow.py::test_reproducibility_workflow[sentence-transformers/all-MiniLM-L6-v2-BornholmBitextMining]
9.37s call     tests/test_mteb.py::test_mteb_task[average_word_embeddings_levy_dependency-SciDocsRR]
=========================== short test summary info …
```
> fix: dataset not available

- docs/mmteb/points/760.jsonl
- mteb/abstasks/AbsTask.py
- mteb/abstasks/stratification.py
- mteb/tasks/MultiLabelClassification/__init__.py
- mteb/tasks/MultiLabelClassification/kor/KorHateSpeechMLClassification.py
- mteb/tasks/MultiLabelClassification/por/BrazilianToxicTweetsClassification.py
This is continuation of the discussion from https://github.com/embeddings-benchmark/mteb/discussions/698. 
cc @x-tabdeveloping
> Added multilabel stratification to AbsTaskMultilabelClassification

- mteb/evaluation/evaluators/utils.py
- tests/test_RerankingEvaluator.py
- tests/test_RetrievalEvaluator.py
Hi MTEB team!
I recently added abstention/calibration metrics to the Retrieval and Reranking tasks and just noticed that there was a slight issue when evaluating on very small datasets (less than 10 samples).
I've made the necessary changes to make it work in this edge case.
Cheers!
> Fix abstention metric for small datasets

- docs/mmteb/points/911.jsonl
- mteb/tasks/Retrieval/zho/CMTEBRetrieval.py
fix Incorrect handling of qrel_revision, the revision would differ if the  dataset repo is different for  `qrels`. Thus, added an attribute to handle `qrel_revision`.  and added their revisions.
fixes: #909
CC: @Muennighoff @KennethEnevoldsen @dzqoo
> fix Incorrect handling of qrel_revision fix: #909

- mteb/cli.py
- tests/create_meta/model_card.md
- tests/create_meta/model_card_gold.md
Hello,
I followed the instructions provided in [https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_model.md](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_model.md).
It turns out that at step "**3. Add the frontmatter to model repository**", when copying the metadata generated in the README.md, Hugging Face returns the following error:
After some investigation, I realized that this was because "s" was missing for "metrics" as well as a "-" before the "type:" contained in "metrics". 
By adding them, everything works locally. So I'm taking the liberty of opening this PR to avoid this problem for others.
Have a nice day :)
> Fix create_meta function in cli.py

- mteb/abstasks/AbsTaskRetrieval.py
- mteb/tasks/Retrieval/code/CodeEditSearchRetrieval.py
- mteb/tasks/Retrieval/multilingual/BelebeleRetrieval.py
- mteb/tasks/Retrieval/multilingual/IndicQARetrieval.py
- mteb/tasks/Retrieval/zho/CMTEBRetrieval.py
Addresses #964 
Run the following and fixed one by one:
```python
from mteb import get_tasks
TASKS = [
"BelebeleRetrieval",
"NorQuadRetrieval",
"SwednRetrieval",
"PublicHealthQA",
"CovidRetrieval",
"CrossLingualSemanticDiscriminationWMT19",
"CrossLingualSemanticDiscriminationWMT21",
"DanFEVER",
"SweFaqRetrieval",
"TV2Nordretrieval",
"CodeEditSearchRetrieval",
"TwitterHjerneRetrieval",
"MLQARetrieval",
"SNLRetrieval",
"IndicQARetrieval",
"XPQARetrieval",
]
exceptions = []
tasks = get_tasks(tasks=TASKS)
for task in tasks:
task.calculate_metadata_metrics()
```
- Half are resolved in #953 by adding `load_data`
- `CovidRetrieval` references a non-existent split
- Some faced index out of range
- `BelebeleRetrieval` still used `self.langs`
- Some did not have titles
- Some have `None` as queries …
> fix: bug in calculate_metadata_metrics for some retrieval datasets

- mteb/models/gritlm.py
if we care about exactly reproducing e5 & grit, I think we have another bug which is that they do not use an instruction for documents, but only queries for Retrieval. One solution could be to distinguish corpus & query prompts like here: https://github.com/ContextualAI/gritlm/blob/da37ccbace1aa4f4bf26273e4e9a7cea705ae951/evaluation/eval_mteb.py#L66 and then instead try to get the respective prompt in encode_corpus & encode_queries --- What do you think?
Fixes https://github.com/embeddings-benchmark/mteb/issues/973
> Fix GritLM instructions

- docs/mmteb/points/982.jsonl
- mteb/abstasks/AbsTaskSpeedTask.py
To run MTEB, `psutil` and `GPUtil` are now required because all abstract tasks are imported for each run. When attempting to import `AbsTaskSpeedTask`, it fails due to `psutil` and `GPUtil` not being installed.
> Move speedtask imports

- mteb/cli.py
- tests/create_meta/model_card_gold.md
> fix: convert scores in meta to be in 0-100 instead of 0-1

- mteb/tasks/Classification/swa/SwahiliNewsClassification.py
> The Swahili Classification Task

- mteb/models/e5_instruct.py
change e5 default to use cuda if available
Fixes #1021 
@Muennighoff adding you here. I will just set it to automerge but if there is any comments I will update it
> fix: change e5 default to use cuda if available

- mteb/tasks/Retrieval/multilingual/WikipediaRetrievalMultilingual.py
The EncoderInterface only accepts list of strings for queries
https://github.com/embeddings-benchmark/mteb/blob/4fc945a76d11b7e9d63412f63322cfca16f679bf/mteb/encoder_interface.py#L95
however 
https://github.com/embeddings-benchmark/mteb/blob/4fc945a76d11b7e9d63412f63322cfca16f679bf/mteb/tasks/Retrieval/multilingual/WikipediaRetrievalMultilingual.py#L72
will pass a dict like for documents. For docs that's fine but not for queries given our interface.
This is a simple fix but it may be missing some subtleties. We could also adapt the interface to also accept dicts for queries but not needed here i think since there's nothing else in the dict anyways besides the text so maybe if this comes up again in the future
cc @rasdani
> Fix query format

- mteb/tasks/Clustering/jpn/LivedoorNewsClustering.py
- mteb/tasks/STS/multilingual/STS22CrosslingualSTS.py
This pull request adds the STS22.v2 and LivedoorNewsClustering.v2 which removed duplicated from their base version.
fixes #1043
> Add STS22.v2 and LivedoorNewsClustering.v2

- mteb/load_results/mteb_results.py
- mteb/tasks/BitextMining/multilingual/FloresBitextMining.py
Did a bit of testing:
```
❯ du -h FloresBitextMining*
15M    FloresBitextMining.json
11M    FloresBitextMining_six_dec.json
7.1M    FloresBitextMining_small_six_dec_and_no_spaces.json
```
> Remove precision for more readable scores and lower memory footprint

- mteb/tasks/Classification/multilingual/LanguageClassification.py
> fix: update lang codes for language classification

- .github/workflows/docs.yml
- Makefile
I am having a few issues with this CI. I believe this should work, but I am not sure exactly why the previous CI doesn't work (it did for a short while). It might be due to the token not being passed correctly. 
This configuration essentially just takes the previous CI that did work on main and adds a completely separate CI for PRs. 
To avoid having to change stuff in the future it convert the build command into `make build-docs`.
@isaac-chung would love a second pair of eyes on this if you have the time
> ci: Splitting doc CI in two to ensure that it runs on PRs AND on main

- mteb/models/e5_instruct.py
An error was found in the function's name, which caused a bug, and not all tasks were completed, due to an error in the model's embeddings. There were sometimes zeros and infinity values.
> fix: fix bug-causing spelling error in function name of e5-mistral-instruct

- mteb/tasks/Classification/multilingual/MultilingualSentimentClassification.py
Now if run MultilingualSentimentClassification with any language as subset it will raise error
Example
```
tasks = mteb.get_tasks(tasks=["MultilingualSentimentClassification"], languages=["eng"])
evaluation = mteb.MTEB(tasks)
evaluation.run(model, output_folder="results", verbosity=2, overwrite_results=True)
```
> fix MultilingualSentimentClassification

- mteb/cli.py
- mteb/tasks/Clustering/multilingual/MLSUMClusteringP2P.py
> fix: Ensure that MLSUMClusteringP2P.v2 use the fast implementation as was intended

- README.md
Instead of having a single drop down for the advanced usage, I create a dropdown for each subsection. This makes the makes it much easier to see what is available in the docs.
> docs: improve searchability in the advanced usage documentation

- mteb/cli.py
- mteb/load_results/mteb_results.py
Closes #1111
I've run `mteb create_meta` and got `type: CQADupstackRetrieval_is_a_combined_dataset` in type. I think that other datasets have same problems
> fix export type

- mteb/models/nomic_models.py
> fix: nomic models using prefix correctly

- mteb/tasks/BitextMining/__init__.py
- mteb/tasks/BitextMining/multilingual/IWSLT2017BitextMining.py
The present IWSTL2017BitextMining raises following error when the loading dataset.
```
ERROR:mteb.evaluation.MTEB:Error while evaluating IWSLT2017BitextMining: 'list' object has no attribute 'map'                             
Traceback (most recent call last):                                                                                                        
File "/path/to/experiments/mteb_jpn.py", line 126, in <module>                                                    
main(args)                                                                                                                            
File "/path/to/experiments/mteb_jpn.py", line 111, in main                                                        
evaluation.run( …
```
> fix: IWSLT2017BitextMining loading dataset.

- mteb/abstasks/TaskMetadata.py
- mteb/models/google_models.py
- tests/test_TaskMetadata.py
This fix allows for more lenient TaskMetadata when using the package, but maintain the validation for the package within the tests.
This is intended to ensure flexibility and ease of use, while maintaining high-quality doucementation of tasks
Fixes #1121
> fix: Allow more linient TaskMetadata

- mteb/tasks/STS/zho/CMTEBSTS.py
The test set of AFQMC is hidden so has removed it from the default suite. This influences the C-MTEB. Who is the best person to contact for this? (@Muennighoff)
> fix: removed test set for AFQMC with no gold labels

- mteb/benchmarks.py
- mteb/models/instructions.py
- scripts/task_selection/task_selection_example.ipynb
This PR updates composition of tasks in Russian part of MTEB. Namely, it adds recently merged MIRACL (#833, #830), RuBQReranking, Multi-label tasks CEDR and SensitiveTopics (#881) and RuParaphraser (#716). 
Also, PR adds instructions (in English) for all tasks from the benchmark, which allows better test the potential of instructional models (e.g. e5-instruct models).
> Update ruMTEB tasks list

- mteb/evaluation/evaluators/PairClassificationEvaluator.py
- mteb/tasks/PairClassification/zho/CMTEBPairClassification.py
Fix https://github.com/embeddings-benchmark/mteb/pull/1061#issuecomment-2303061402
Removed test split, because [OCNLI](https://huggingface.co/datasets/C-MTEB/OCNLI) doesn't have it.
> fix: Remove unavailable test split from OCNLI 

- docs/adding_a_dataset.md
- docs/adding_a_model.md
Added fixes for a couple of broken links in [adding_a_dataset](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_dataset.md) and [adding_a_model](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_model.md). 
Note: the script run_mteb_chinese.py seems to be gone entirely.
> docs: Fix broken links in docs

- mteb/evaluation/MTEB.py
- tests/test_benchmark/test_benchmark.py
> fix: Ensure that results are returned even when hitting cache

- docs/mmteb/points.md
> docs: Update affiliation

- mteb/models/__init__.py
- tests/test_tasks/test_mteb_rerank.py
Address #1192. Running the snipper in the issue description should return no WARNINGs now.
- Use the config attribute of [CrossEncoder](https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/cross_encoder/CrossEncoder.py) to get model name
- Small cosmetic fix on indent after return statement
CC @orionw @Muennighoff as you were part of the discussion in the last PR.
> fix: Get meta from CrossEncoder

- README.md
- docs/benchmarks.md
- mteb/cli.py
- mteb/evaluation/MTEB.py
- tests/test_cli.py
Addresses #1250 point 1. 
- Add benchmarks under the "Docs" section of README
- Add CLI option to list all available benchmarks
- Headers will print the benchmark name
- The tasks will be printed the same way as it is now
- Add test case for the added CLI option
This command should yield something like the following, starting with MTEB(eng):
```
mteb available_benchmarks
```
<details>
<summary>Full printout</summary>
```bash
>> mteb available_benchmarks
─────────────────────────────────────────────────────────────── MTEB(eng)  ────────────────────────────────────────────────────────────────
Summarization
- SummEval, p2p
PairClassification
- SprintDuplicateQuestions, s2s
- TwitterSemEval2015, s2s
- TwitterURLCorpus, s2s
Classification
- AmazonCounterfactualClassification, s2s, multilingual …
```
> fix: Add listing all available benchmarks CLI option

- mteb/cli.py
- mteb/evaluation/MTEB.py
- tests/test_benchmark/test_benchmark.py
- tests/test_cli.py
- tests/test_tasks/test_mteb_rerank.py
Address #1250 point 2.
- Added test cases for a list of Benchmark objects passed into the task parameter
- Added command line option to select Benchmarks
The following can now run. 1) script
```python
from sentence_transformers import SentenceTransformer
import mteb
model_name = "average_word_embeddings_komninos"
model = SentenceTransformer(model_name)
benchmark = mteb.get_benchmarks(names=["MTEB(eng)"])
evaluation = mteb.MTEB(tasks=benchmark)
results = evaluation.run(model)
```
and command line:
```
mteb run -m average_word_embeddings_komninos -b 'MTEB(eng)'
```
> fix: Select benchmarks CLI option

- mteb/load_results/load_results.py
The `load_results` function includes a `results_repo` parameter, allowing the use of an alternative Git repository for storing the benchmarking results. This parameter is then passed to the `download_of_results` function. However, the current implementation requires the alternative repository to be named _results_, as this name is hardcoded.
This PR updates the code to derive the results_directory path from the repository name, removing the hardcoded requirement and giving more flexibility in naming the alternative repository.
> fix: derive `results_directory` path from `results_repo` name

- mteb/tasks/PairClassification/zho/CMTEBPairClassification.py
Fix the KeyError of [CMNLI dataset](https://huggingface.co/datasets/C-MTEB/CMNLI) in C-MTEB:  'test' does not exist.
> fix: Remove non-existent eval split of CMNLI

- mteb/tasks/Retrieval/__init__.py
- mteb/tasks/Retrieval/slk/SKQuadRetrieval.py
This commit introduces the Retrieval SK Quad dataset, designed to assess Slovak search performance. The dataset is derived from SK-QuAD and includes questions with their best answers categorized post-annotation. This addition provides a significant resource for advancing Slovak language search evaluation and supporting further research and development.
> fix: Add Retrieval SK Quad dataset for Slovak search evaluation

- mteb/benchmarks/benchmarks.py
- mteb/tasks/Clustering/multilingual/MLSUMClusteringP2P.py
- mteb/tasks/Clustering/multilingual/MLSUMClusteringS2S.py
This should solve issue #1311.
I re-uploaded the dataset to parquet format here: https://huggingface.co/datasets/mteb/mlsum as suggested by @lhoestq, to avoid using the script generation for loading.
> Re-upload dataset to hub to avoid using script upload

- mteb/evaluation/evaluators/Image/ClassificationEvaluator.py
- mteb/models/__init__.py
- mteb/models/vlm2vec_models.py
- results-mieb/TIGER-Lab__VLM2Vec-LoRA/7403b6327958071c1e33c822c7453adadccc7298/Caltech101.json
- results-mieb/TIGER-Lab__VLM2Vec-LoRA/7403b6327958071c1e33c822c7453adadccc7298/STS12.json
- results-mieb/TIGER-Lab__VLM2Vec-LoRA/7403b6327958071c1e33c822c7453adadccc7298/model_meta.json
> [mieb] Add VLM2vec

- mteb/benchmarks/benchmarks.py
- mteb/leaderboard/app.py
- mteb/leaderboard/table.py
- mteb/load_results/task_results.py
> WIP: Leaderboard UI improvements

- mteb/tasks/Retrieval/eng/FEVERRetrieval.py
The other splits can still be run as long as they are specified.
Adresses #1343
> fix: make sure test is the default split for FEVER

- mteb/benchmarks/benchmarks.py
- mteb/caching.py
- mteb/leaderboard/app.py
- mteb/load_results/benchmark_results.py
- mteb/load_results/task_results.py
fixes #1296 
I introduced the following optimizations:
- Skipping validation, where unnecessary.
- Caching results of large computations where possible.
This is a massive improvement, and I feel like the leaderboard is finally running at a rather usable speed.
> fix: Speed up leaderboard by caching and skipping validation

- mteb/models/e5_v.py
- mteb/models/vlm2vec_models.py
Got OOMs for these due to grads being computed
> [mieb] Fix torch no grad

- mteb/leaderboard/app.py
- mteb/leaderboard/table.py
Implemented the following things:
- Added RegEx-sensitive search bar
- Reorganized model and benchmark criteria in a way that's more sensible
- Table improvements:
- Better column names
- Reorganized columns
- Added clickable model links
- Adjusted column widths
> fix: Leaderboard UI improvements

- mteb/models/blip_models.py
Fixes https://github.com/embeddings-benchmark/mteb/issues/1392.
> [MIEB] Remove non-existent method for blip

- mteb/evaluation/MTEB.py
- mteb/leaderboard/table.py
This PR add support for disabling `rich` output on console with `verbosity=0` on `evaluation.run()`.
This solves #1385 and partially solves #1046
> Disable `rich` output with `verbosity=0` on `evaluation.run`

- mteb/models/openclip_models.py
fixes #1393 by adding `unsqueeze(0)` after applying preprocessing.
Running `mteb run -m laion/CLIP-ViT-B-32-DataComp.XL-s13B-b90K -t CVBenchCount` yields
```
********************** Evaluating CVBenchCount **********************
INFO:mteb.evaluation.MTEB:Loading dataset for CVBenchCount
INFO:mteb.abstasks.AbsTask:
Task: CVBenchCount, split: test, subset: default. Running...
/home/ubuntu/isaac/work/mteb/mteb/models/openclip_models.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
with torch.no_grad(), torch.cuda.amp.autocast():
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 …
```
> [mieb] Fix open clip for cv bench count

- pyproject.toml
This PR adds the file `the_ugly_duckling.txt` to the Python wheel. Currently when installing mteb with `pip install mteb` and then running a SpeedTask you get the error below. This PR fixes that.
```
File ".../venv/lib/python3.12/site-packages/mteb/abstasks/AbsTaskSpeedTask.py", line 35, in load_data
with file_path.open("r") as f:
^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/pathlib.py", line 1013, in open
return io.open(self, mode, buffering, encoding, errors, newline)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '.../venv/lib/python3.12/site-packages/mteb/abstasks/the_ugly_duckling.txt'
```
> fix: Add the_ugly_duckling.txt for speedtask to Python wheel

- docs/adding_a_model.md
> docs: Update recommendation for pushing results

- scripts/run_mieb_get_params.py
- scripts/run_mieb_kshot_ablation.py
- scripts/run_mieb_rerun_siglip.py
scripts for mieb:
siglip rerun (see #1424); linear probing k-shot ablation; get params count
> [mieb] mieb scripts (siglip rerun & linear probing ablation & params count)

- .gitignore
- mteb/evaluation/evaluators/RetrievalEvaluator.py
Fixes #1389
Ran through tests but couldn't find a case where it was actually used. It might be a thing we can simply remove.
> fix: add logging for RetrievalEvaluator NaN values for similarity scores

- mteb/benchmarks/benchmarks.py
@x-tabdeveloping the Bright retrieval will probably look a bit odd. Is there a way to split a task into multiple columns?
Fixes #1423
> Fix: Add missing benchmarks in benchmarks.py

- mteb/leaderboard/app.py
- mteb/leaderboard/figures.py
- mteb/leaderboard/table.py
- pyproject.toml
I added an interactive performance vs.  number of parameters plot as the first thing people see when selecting a benchmark. #1396 
I also added some info on the benchmarks to the benchmark description as Niklas requested here: #1317 
Here's a screenshot:
I also bumped the Gradio version, as I thought it might fix certain things, but I have two burning problems still, for which I opened respective issues in Gradio (https://github.com/gradio-app/gradio/issues/9938, https://github.com/gradio-app/gradio/issues/9937)
> Leaderboard 2.0: added performance x n_parameters plot + more benchmark info

- mteb/load_results/task_results.py
In the current implementation, `mteb_version` is dropped if it's set to `None`, but `TaskResult` expects `mteb_version` to be present in the dictionary
> fix: Fix load external results with `None` mteb_version

- mteb/leaderboard/app.py
- mteb/leaderboard/table.py
Minor changes to tables and figures to make things more readable and intuitive.
> WIP: Polishing up leaderboard UI

- mteb/load_results/task_results.py
Currently can't load results without version, e. g. `{"test": {"en": {"accuracy": 0.7285810356}}, "mteb_dataset_name": "MassiveIntentClassification"}`
> fix: loading pre 1.11.0

- mteb/cli.py
- mteb/evaluation/MTEB.py
- pyproject.toml
- tests/test_cli.py
This PR enables code carbon by default. Closes https://github.com/embeddings-benchmark/mteb/issues/1427
> feat: enable codecarbon by default

- pyproject.toml
This PR pins datasets version to be less than 3.0.0 to avoid datasets.tasks errors. I made PR #1470 but this one is for merging
on the `v2.0.0` branch
partly fixes https://github.com/embeddings-benchmark/mteb/issues/1465
> fix: pin datasets version <3.0.0

- pyproject.toml
This PR pins `datasets` version to be less than 3.0.0 to avoid `datasets.tasks` errors.
This solves #1465
> fix: pinned datasets to <3.0.0

- mteb/abstasks/AbsTaskRetrieval.py
- mteb/abstasks/dataloaders.py
I've added a multilingual retrieval loader with the following structure:  
- `{config}-corpus`  
- `{config}-queries`  
...  
However, currently, there are no datasets that fit this structure. Previously, when I uploaded datasets, I used `corpus-config`, but more other datasets start with `config`. These datasets have variations that make them incompatible with this loader for direct use, so this is more for the future
> feat: Multilingual retrieval loader

- README.md
- mteb/evaluation/MTEB.py
- tests/test_benchmark/mock_models.py
The current README is a bit misleading and causing issues for newcomers. See #1490 and #1491 for reference.
> fix: align readme with current mteb

- mteb/evaluation/MTEB.py
- tests/test_benchmark/mock_tasks.py
- tests/test_evaluation/test_split_evaluation.py
Fixes #1260 
- Based on https://github.com/embeddings-benchmark/mteb/pull/1268 and addresses most of the comments
- Once run, the returned result will contain the missing splits as well as the already run splits
- Requires `overwrite=True` to work
- Changed tests to use the same MTEB object instead of a new one
Example Usage
```python
from mteb import MTEB, get_tasks, get_model
tasks = get_tasks(tasks=["Banking77Classification"])
model = get_model("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")
evaluation = MTEB(tasks=tasks)
results = evaluation.run(
model,
eval_splits=["val"],
output_folder=str(tmp_path / "testcase2"),
verbosity=2,
)
results2 = evaluation.run(
model,
eval_splits=["val", "test"],
output_folder=str(tmp_path / "testcase2"),
verbosity=2, …
```
> feat: Evaluate missing splits

- mteb/tasks/PairClassification/multilingual/XStance.py
- mteb/tasks/STS/por/SickBrSTS.py
Fixes #1407 . This code now runs without error.
```python
import mteb
task = mteb.get_task("SICK-BR-STS")  # or XStance
task.load_data()
```
> fix: Task load data error for SICK-BR-STS and XStance

- mteb/leaderboard/app.py
- mteb/leaderboard/table.py
- mteb/models/openai_models.py
- pyproject.toml
Proprietary models were not correctly shown due to model size filtering being incorrectly implemented.
I also fixed column wrapping and formatting, the per task performance table is also correctly ordered.
> fix: Proprietary models now get correctly shown in leaderboard

- mteb/leaderboard/app.py
- mteb/load_results/benchmark_results.py
- mteb/models/cohere_models.py
- pyproject.toml
> Add cohere models

- mteb/models/mxbai_models.py
> fix: Add mixbai models

- mteb/load_results/task_results.py
- mteb/tasks/Retrieval/eng/DBPediaRetrieval.py
- mteb/tasks/Retrieval/eng/HotpotQARetrieval.py
Some results were missing from the leaderboard, since task result validation removed them, because some languages were missing from the results.
Validation only throws warnings now, I also removed some splits from `eval_splits` on two tasks, since all models were missing these splits from the results repo.
> Made result loading more permissive, changed eval splits for HotPotQA and DBPedia

- mteb/models/google_models.py
- mteb/models/model2vec_models.py
Hello! Small PR focused on `google_models.py` since we noticed that they were not working properly on the latest versions of MTEB.
This PR introduces a few fixes to make them work again, as well as two new models: `text-embedding-005` and `text-multilingual-embedding-002`.
Fixes #1480
- Use batching to circumvent Vertex AI limits on number of instances and input tokens
- Optionally use `tqdm` to show batching progress
- Load correct `google_task_type`, since we were wrongly passing the `prompt_name` before
- Add support for `text-embedding-005` and `text-multilingual-embedding-002` models
- Fix linting issue in `model2vec_models.py` raised by `make lint`
> feat(google_models): fix issues and add support for `text-embedding-005` and `text-multilingual-embedding-002`

- mteb/evaluation/evaluators/RetrievalEvaluator.py
- mteb/models/bm25.py
The `bm25s` implementation for retrieval tasks does not currently work with the latest versions of MTEB. This PR introduces two fixes to restore its functionality:
- Update the argument check in `RetrievalEvaluator` from `self.retriever.model` to `self.retriever.model.model`.
- Adjust the `search` method to account for the fact that `corpus[cid]` may now be a dictionary, removing the need to always wrap it as `{"text": corpus[cid]}`.
These changes were already applied in the results presented in https://github.com/embeddings-benchmark/results/pull/55 to verify that they worked properly. They will not impact older results.
> fix(bm25s): search implementation

- README.md
- mteb/model_meta.py
> fix: Add training dataset to model meta

- mteb/models/cohere_models.py
- mteb/models/openai_models.py
As a follow-up to https://github.com/embeddings-benchmark/mteb/pull/1562, Cohere models where lacking batching, which made it difficult to run them on a large corpus. This PR adds such batching as well as `tqdm` for tracking progress (also added to openai_models at the same time).
There is also a fix for loading the correct `cohere_task_type`, since we were wrongly passing the `prompt_name` before as with `google_models`.
> feat: (cohere_models) cohere_task_type issue, batch requests and tqdm for visualization

- mteb/tasks/Retrieval/multilingual/PublicHealthQARetrieval.py
[PublicHealthQA](https://huggingface.co/datasets/xhluca/publichealth-qa) has some rows with `None` values in `question` or `answer`, which raised an error while evaluating models on it. We noticed the issue when evaluating models in the `MTEB(Medical)` benchmark. This change was already applied in the results presented in https://github.com/embeddings-benchmark/results/pull/55.
> fix(publichealth-qa):  ignore rows with `None` values in `question` or `answer`

- mteb/leaderboard/app.py
- mteb/leaderboard/figures.py
- mteb/leaderboard/table.py
I added a radar chart to a tab you can switch to from the other plot.
It only displays the top 5 models that have been run on all task types to avoid clutter.
I also decided not to display instruction retrieval, since it can be negative and it looks weird.
Here's how it looks:
> fix: Added radar chart displaying capabilities on task types

- mteb/models/misc_models.py
- mteb/tasks/Classification/multilingual/HinDialectClassification.py
- mteb/tasks/Classification/multilingual/SouthAfricanLangClassification.py
- tests/test_TaskMetadata.py
Closes https://github.com/embeddings-benchmark/mteb/issues/1586
It seems that sometimes `eval_langs` is incorrectly specified as a dictionary instead of a list for monolingual tasks.  I've added test to check if it correctly specified
> fix: Eval langs not correctly passed to monolingual tasks

- mteb/evaluation/evaluators/Image/Any2AnyRetrievalEvaluator.py
- mteb/evaluation/evaluators/Image/ZeroshotClassificationEvaluator.py
- mteb/models/align_models.py
- mteb/models/blip2_models.py
- mteb/models/blip_models.py
- mteb/models/clip_models.py
- mteb/models/cohere_v.py
- mteb/models/dino_models.py
- mteb/models/e5_v.py
- mteb/models/evaclip_models.py
- mteb/models/jina_clip.py
- mteb/models/moco_models.py
- mteb/models/nomic_models_vision.py
- mteb/models/openclip_models.py
- mteb/models/siglip_models.py
- mteb/models/vista_models.py
- mteb/models/vlm2vec_models.py
- mteb/models/voyage_v.py
Fix https://github.com/embeddings-benchmark/mteb/issues/1523#issuecomment-2535897120
1. Make `get_xxx_embeddings` follow `encode`, accepting the follow arguments.
```
task_name=task_name,
prompt_type=PromptType.passage,
**self.encode_kwargs,
```
2. `ImageDataset.transform` could be `None`, which could avoid unnecessary `Image -> Tensor -> Image` operations.
3. Pass `input_type` to `voyage_v` API by `prompt_type`
I failed 8 tests, but they may not be triggered by above changes.
```
FAILED tests/test_benchmark/test_benchmark_integration_with_datasets.py::test_benchmark_sentence_transformer[model0-task0] - TypeError: 'NoneType' object is not callable
FAILED tests/test_reproducible_workflow.py::test_reproducibility_workflow[8b3219a92973c328a8e22fadcfa821b5dc75636a-sentence-transformers/all-Min …
```
> [MIEB] Make multimodal models compatible to `task_name` and `prompt_type`

- README.md
Closes: https://github.com/embeddings-benchmark/mteb/issues/1589
Improve the documentation and add information about the PLAID Index in PyLate.
> doc: colbert add score_function & doc section

- mteb/leaderboard/app.py
- mteb/leaderboard/figures.py
I added a guide for embedding size as requested, along with smaller adjustments to plotting behaviour.
> Leaderboard: Refined plots

- mteb/leaderboard/app.py
Implemented the following features in the leaderboard:
1. Download buttons: #1531 
2. Custom URLs: #1518 
3. Description of aggregate metrics: #1512 
4. Sort task info #1510
> fix: Leaderboard refinements

- README.md
- mteb/abstasks/AbsTask.py
- mteb/abstasks/AbsTaskBitextMining.py
- mteb/abstasks/AbsTaskClassification.py
- mteb/abstasks/AbsTaskInstructionRetrieval.py
- mteb/abstasks/AbsTaskMultilabelClassification.py
- mteb/abstasks/AbsTaskRetrieval.py
- mteb/evaluation/MTEB.py
- mteb/models/misc_models.py
- tests/test_benchmark/mock_tasks.py
- tests/test_evaluation/test_split_evaluation.py
Continue ideas from https://github.com/embeddings-benchmark/mteb/pull/1525
If a missing split is present in the existing results, return its results without running the evaluation.
> Feat: Evaluate missing languages

- mteb/evaluation/MTEB.py
When `co2_tracker` is enabled, it is used for API-based models as well, which can be misleading. This PR introduces a simple check to determine if a model's meta defines `API` as its framework, and if so, disables `co2_tracker` for the evaluation run.
Currently, four model families use `API` as their framework: `cohere_models`, `google_models`, `openai_models` and `voyage_models`.
This PR relates to the conversation [here](https://github.com/embeddings-benchmark/results/pull/71#issuecomment-2542593617).
> fix: disable co2_tracker for API models

- mteb/models/arctic_models.py
- mteb/models/bge_models.py
- mteb/models/cohere_models.py
- mteb/models/jina_models.py
- mteb/models/ru_sentence_models.py
- mteb/models/uae_models.py
- mteb/models/voyage_models.py
This PR sets the `use_instructions` parameter to True for models that use prompts.
I've also included Arctic models because, while they don’t explicitly mention prompts in their MTEB implementation, they add the prompts directly in their `config_sentence_transformers.json`, so SentenceTransformers uses them automatically (example [here](https://huggingface.co/Snowflake/snowflake-arctic-embed-m-v2.0/blob/main/config_sentence_transformers.json))
Additional context for this PR can be found in [this thread](https://github.com/embeddings-benchmark/results/pull/66#discussion_r1879811928)
A follow up PR in the results repo updates the corresponding `model_meta.json` values for these specific models and revisions.
> fix: set `use_instructions` to True in models using prompts

- mteb/evaluation/MTEB.py
- tests/test_evaluation/test_split_evaluation.py
Currently, if `overwrite` is passed with existing results, it won't overwrite them, and everything will be skipped.
This was the reason of https://github.com/embeddings-benchmark/mteb/pull/1584#issuecomment-2541310911
> fix: override existing results

- mteb/models/align_models.py
- mteb/models/blip2_models.py
- mteb/models/blip_models.py
- mteb/models/clip_models.py
- mteb/models/cohere_v.py
- mteb/models/dino_models.py
- mteb/models/e5_v.py
- mteb/models/evaclip_models.py
- mteb/models/jina_clip.py
- mteb/models/nomic_models_vision.py
- mteb/models/openclip_models.py
- mteb/models/siglip_models.py
- mteb/models/vista_models.py
- mteb/models/vlm2vec_models.py
- mteb/models/voyage_v.py
In PR https://github.com/embeddings-benchmark/mteb/pull/1583 , I only changed the arguments of `get_fused_emebddings`, but forgot to update the internal implementation logic accordingly, which caused runtime errors. (Sorry)
Now, they are fixed.
I will run `i`, `t`, and `it` encodings for each model to check.
---
Checking progress:
| code |  i2t - Flickr30kI2TRetrieval | it2t - LLaVAIT2TRetrieval PR https://github.com/embeddings-benchmark/mteb/pull/1611 | note |
|-----|-----|-----|----|
| align_models.py | ✓ | ✓ |
| blip2_models.py |  |  | `salesforce-lavis` is conflict with `sentence_transformers>=3.0`|
| blip_models.py | ✓ | ✓ |
| clip_models.py | ✓ | ✓ |
| cohere_v.py | | | I don't have a key |
| dino_models.py| | | DINO models only support image encoding. |
| e5_v.py | ✓ | ✓ |
| …
> [MIEB] Fix `get_fused_emebddings`

- mteb/tasks/Classification/ara/HotelReviewSentimentClassification.py
- mteb/tasks/Classification/ara/TweetEmotionClassification.py
- mteb/tasks/Classification/deu/TenKGnadClassification.py
- mteb/tasks/Classification/eng/ArxivClassification.py
- mteb/tasks/Classification/eng/PatentClassification.py
- mteb/tasks/Classification/fil/FilipinoHateSpeechClassification.py
- mteb/tasks/Classification/mya/MyanmarNews.py
- mteb/tasks/Classification/nld/DutchBookReviewSentimentClassification.py
- mteb/tasks/Classification/swe/SwedishSentimentClassification.py
- mteb/tasks/Classification/tha/WisesightSentimentClassification.py
- mteb/tasks/Classification/urd/UrduRomanSentimentClassification.py
- mteb/tasks/Retrieval/multilingual/IndicQARetrieval.py
- mteb/tasks/STS/jpn/JSTS.py
- pyproject.toml
Ref https://github.com/embeddings-benchmark/mteb/issues/1465
Update datasets wich can't be loaded with `datasets>=3.0`. I'll provide run results a bit later
> [V2] Update datasets wich can't be loaded with `datasets>=3.0`

- mteb/tasks/Retrieval/deu/GermanDPRRetrieval.py
> fix: GermanDPR Dataset Causes Cross-Encoder Failure Due to Unexpected dict

- mteb/tasks/Image/Any2AnyRetrieval/__init__.py
- mteb/tasks/Image/Any2AnyRetrieval/eng/EncyclopediaVQAIT2ITRetrieval.py
- mteb/tasks/Image/Any2AnyRetrieval/eng/LLaVAIT2TRetrieval.py
- mteb/tasks/Image/Any2AnyRetrieval/eng/OKVQAIT2TRetrieval.py
- mteb/tasks/Image/Any2AnyRetrieval/eng/ReMuQIT2TRetrieval.py
https://github.com/embeddings-benchmark/mteb/issues/1523
Image-text to text retrieval:
- LLaVAIT2TRetrieval
- OKVQAIT2TRetrieval
- ReMuQIT2TRetrieval
Image-text to image-text retrieval:
- EncyclopediaVQAIT2ITRetrieval
I'm runing tests by `mteb run -m {model_name} -t {task_name}`
|   cv_recall_at_5      | LLaVA IT2Tl | OKVQA IT2T  | ReMuQ IT2T | EncyclopediaVQA IT2IT |
|--------------------|-------------|--------------|-------------|-----------|
| nomic-ai/nomic-embed-vision-v1.5 |  73.809 |  12.228  |  93.655  |   41.287   |
| openai/clip-vit-base-patch16     |        38.594 |  4.419    |  66.528  |   16.589   |
**Reason for dataset addition**: These datasets are used in recent studies (such as preFLMR) to evaluate multimodal embedding models, and could provide a meaningful complement to …
> [MIEB] Add new multimodal retrieval tasks

- mteb/task_selection.py
Changed the `results_to_dataframe` function to make the [example](https://github.com/embeddings-benchmark/mteb/blob/ef5a068c82e51b82f7c2233581ea3e2b597a6a8b/README.md?plain=1#L405-L422) from the documentation work.
Error before
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[32], line 11
7 models = [mteb.get_model_meta(name) for name in results_eval_mteb_df["full_name"].unique()]
9 results = mteb.load_results(models=models, tasks=tasks)
---> 11 df = results_to_dataframe(results)
File ~/miniconda3/envs/llm_emb/lib/python3.12/site-packages/mteb/task_selection.py:50, in results_to_dataframe(mteb_results, drop_na, **kwargs)
42 """Convert the results of the MTEB evaluation to a …
```
> Update results_to_dataframe to use BenchmarkResults class

- mteb/tasks/Image/Any2AnyRetrieval/eng/VidoreBenchRetrieval.py
In ViDoRe code, they have some corpus deduplication operation (by image_filename).
https://github.com/illuin-tech/vidore-benchmark/blob/469665d6286f04a4ae09ed7c31dc66dfb44e727a/src/vidore_benchmark/retrievers/vision_retriever.py#L119
However, this deduplication was not implemented in MIEB's ViDoRe data loading process, resulting in inconsistent corpus size. This inconsistency could significantly affect the accuracy of evaluation results.
I switched to ViDoRe BEIR version.
https://huggingface.co/collections/vidore/vidore-benchmark-beir-672fd04012c14cc4e162f2bc
~~Therefore, I added deduplication code to ensure consistency with the official ViDoRe release.~~
~~For example, the corpus size of `VidoreTatdqaRetrieval` should be `277`, not `1,663` as previously shown.
Refer to …
> [MIEB] Switch to ViDoRe BEIR version

- tests/test_benchmark/task_grid.py
- tests/test_tasks/test_mieb_datasets.py
Part of #1339. Extend the test coverage for `mteb/abstasks/Image` and `mteb/evaluation/evaluators/Image` from 30% to 69%.
```
pytest tests/test_tasks/test_mieb_datasets.py -n auto --durations=5 --cov-report=term-missing --cov-config=pyproject.toml --cov=mteb/abstasks/Image --cov=mteb/evaluation/evaluators/Image
```
<details>
<summary>Before</summary>
```
---------- coverage: platform linux, python 3.12.1-final-0 -----------
Name                                                                       Stmts   Miss  Cover   Missing
--------------------------------------------------------------------------------------------------------
mteb/abstasks/Image/AbsTaskAny2AnyMultiChoice.py                             202    166    18%   36-63, 67-71, 80-109, 112-121, 124-138, 141-155, 158-186, …
```
> Extend MIEB test coverage

- mteb/abstasks/TaskMetadata.py
- mteb/evaluation/MTEB.py
- mteb/modalities.py
- mteb/model_meta.py
- mteb/models/align_models.py
- mteb/models/blip2_models.py
- mteb/models/blip_models.py
- mteb/models/clip_models.py
- mteb/models/cohere_v.py
- mteb/models/dino_models.py
- mteb/models/e5_v.py
- mteb/models/evaclip_models.py
- mteb/models/jina_clip.py
- mteb/models/moco_models.py
- mteb/models/nomic_models_vision.py
- mteb/models/openclip_models.py
- mteb/models/siglip_models.py
- mteb/models/vista_models.py
- mteb/models/vlm2vec_models.py
- mteb/models/voyage_v.py
Fixes #1632 
- Added ModelMeta.modalities, which defaults to `["text"]` to be backwards compatible. VLMs will have `["image","text"]`.
- Added logic in `MTEB.run` for exact match between task and model modalities
- Added modality model meta to relevant models
Here is the new log, showing that moco only supports images.
```
Any2AnyRetrieval
- VidoreSyntheticDocQAAIRetrieval, t2i
INFO:mteb.evaluation.MTEB:
********************** Evaluating VidoreSyntheticDocQAAIRetrieval **********************
INFO:mteb.evaluation.MTEB:nyu-visionx/moco-v3-vit-b only supports ['image'], but the task modalities are ['text', 'image'].
```
cc @Muennighoff @gowitheflow-1998
> [mieb] Task filtering by modality supported by models

- mteb/models/gte_models.py
- mteb/models/instruct_wrapper.py
- mteb/models/linq_models.py
- mteb/models/nvidia_models.py
- mteb/models/salesforce_models.py
- mteb/models/wrapper.py
> Correction of discrepancies for gte-Qweb model

- mteb/evaluation/MTEB.py
In #1633, the skipping of image&text tasks for image-only models was added but image-only tasks are now being skipped for image-text models as well. Fixing this with a subset logic.
> [mieb] model task modalities matching logic

- mteb/evaluation/MTEB.py
lol surprised we had this bug; it literally errors out for me 😁
> Fix output_folder for co2 evaluation

- mteb/benchmarks/benchmarks.py
adding RAR-b that's currently missing in `benchmarks.py` and thus not appearing on leaderboard 2.0 (#1013).
> add missing benchmark to benchmarks.py

- mteb/models/model2vec_models.py
Fixes #1662 
Fix applies to both `minishlab/potion-base-2M` and `minishlab/M2V_base_output` (and should also apply to all other model2vec models). Running `mteb run -t ClimateFEVERHardNegatives -m minishlab/potion-base-2M` should produce the following results:
<details>
```
INFO:mteb.abstasks.AbsTaskRetrieval:Time taken to retrieve: 11.89 seconds
INFO:mteb.evaluation.MTEB:Evaluation for ClimateFEVERHardNegatives on test took 13.14 seconds
INFO:mteb.evaluation.MTEB:Scores: {'default': {'ndcg_at_1': 0.092, 'ndcg_at_3': 0.07845, 'ndcg_at_5': 0.0882, 'ndcg_at_10': 0.11008, 'ndcg_at_20': 0.13069, 'ndcg_at_100': 0.16963, 'ndcg_at_1000': 0.21536, 'map_at_1': 0.04165, 'map_at_3': 0.05536, 'map_at_5': 0.0622, 'map_at_10': 0.07081, 'map_at_20': 0.07609, 'map_at_100': 0.08203, 'map_at_1000': …
```
> fix: Cast all Model2Vec outputs as floats

- mteb/abstasks/AbsTaskMultilabelClassification.py
Closes https://github.com/embeddings-benchmark/mteb/issues/1654
> fix: remove model as a parameter for MulticlassClassification

- mteb/models/voyage_models.py
- mteb/models/wrapper.py
Closes https://github.com/embeddings-benchmark/mteb/issues/1652 
Closes https://github.com/embeddings-benchmark/mteb/issues/1649
> fix: Use prompts instead of prompt names for voyage

- mteb/evaluation/MTEB.py
- mteb/models/bm25.py
- pyproject.toml
Fixes #1646 
As bm25s is only intended for retrieval tasks, we now skip evaluating on non-retrieval tasks.
- Add warning for non-retrieval tasks when bm25s is the selected model
- Clean up install in `pyproject.toml`
Running `mteb run -m bm25s -t indonli` now yields:
```
──────────────────────────────────────────────────────────────────────────── Selected tasks  ────────────────────────────────────────────────────────────────────────────
PairClassification
- indonli, s2s
INFO:mteb.evaluation.MTEB:
********************** Evaluating indonli **********************
WARNING:mteb.evaluation.MTEB:bm25s only supports Retrieval tasks, but the task type is PairClassification. Skipping task.
```
CC @Muennighoff
> fix: Add warning for non-retrieval tasks when using bm25s

- mteb/models/sentence_transformer_wrapper.py
- mteb/models/wrapper.py
- tests/test_reproducible_workflow.py
Incorrect task names would raise `KeyError`, but previously the check was only for `ValueError`.
Closes https://github.com/embeddings-benchmark/mteb/issues/1657
Closes https://github.com/embeddings-benchmark/mteb/issues/1659
> fix: add check for key error in loader

- mteb/models/nomic_models.py
I tried running `mteb run -m nomic-ai/nomic-embed-text-v1.5 -t NorwegianCourtsBitextMining`, and now it works
Closes https://github.com/embeddings-benchmark/mteb/issues/1680
> fix: nomic tensor return

- mteb/models/nomic_models.py
Currently, prompt names are added at the beginning of sentences, but this isn't always correct. For example, instead of `classification: `, it might incorrectly be `MultilabelClassification: `, or `passage: ` instead of `search_document: `.
> fix: nomic prompts

- mteb/tasks/Retrieval/eng/NanoArguAnaRetrieval.py
- mteb/tasks/Retrieval/eng/NanoClimateFeverRetrieval.py
- mteb/tasks/Retrieval/eng/NanoDBPediaRetrieval.py
- mteb/tasks/Retrieval/eng/NanoFEVERRetrieval.py
- mteb/tasks/Retrieval/eng/NanoFiQA2018Retrieval.py
- mteb/tasks/Retrieval/eng/NanoHotpotQARetrieval.py
- mteb/tasks/Retrieval/eng/NanoMSMARCORetrieval.py
- mteb/tasks/Retrieval/eng/NanoNFCorpusRetrieval.py
- mteb/tasks/Retrieval/eng/NanoNQRetrieval.py
- mteb/tasks/Retrieval/eng/NanoQuoraRetrieval.py
- mteb/tasks/Retrieval/eng/NanoSCIDOCSRetrieval.py
- mteb/tasks/Retrieval/eng/NanoSciFactRetrieval.py
- mteb/tasks/Retrieval/eng/NanoTouche2020Retrieval.py
In the previous implementation, each query could only have one relevant document, but in most datasets, queries can have multiple relevant documents.
Results https://github.com/embeddings-benchmark/mteb/issues/1627#issuecomment-2568373454, https://github.com/embeddings-benchmark/results/pull/84
Closes https://github.com/embeddings-benchmark/mteb/issues/1627
> fix: NanoBeir

- mteb/models/sentence_transformers_models.py
```
>>> import mteb
>>> mteb.get_model_meta("keeeeenw/MicroLlama-text-embedding", "98f70f14cdf12d7ea217ed2fd4e808b0195f1e7e")
ModelMeta(name='keeeeenw/MicroLlama-text-embedding', revision='98f70f14cdf12d7ea217ed2fd4e808b0195f1e7e', release_date='2024-11-10', languages=['eng-Latn'], loader=None, n_parameters=272000000, memory_usage=None, max_tokens=2048.0, embed_dim=1024, license='apache-2.0', open_weights=True, public_training_data=None, public_training_code=None, framework=['Sentence Transformers', 'PyTorch'], reference='https://huggingface.co/keeeeenw/MicroLlama-text-embedding', similarity_fn_name='cosine', use_instructions=False, training_datasets=None, adapted_from=None, superseded_by=None)
>>> tasks = mteb.get_tasks(tasks=["Banking77Classification"])
... evaluation = …
```
> fix: Register MicroLlama Text Embedding

- mteb/models/misc_models.py
I haven't checked the performance because it was only tested on CMTEB, which includes very large tasks. Additionally, they probably ran it with instructions, but this needs to be verified. Also commented out `flash_attention_2`, because I've tested model on kaggle and `flash_attention_2` is not supporting T4. 
Closes https://github.com/embeddings-benchmark/mteb/issues/1696
> Fix: minicpmv2

- mteb/evaluation/evaluators/BitextMiningEvaluator.py
- mteb/tasks/BitextMining/multilingual/BUCCBitextMining.py
Closing: https://github.com/embeddings-benchmark/mteb/issues/1694
Results for `sentence-transformers/LaBSE`, since I can't reproduce results for `intfloat/multilingual-e5-small`. Maybe they used for `query: ` as prefix here.
| | Leaderboard (BUCC) | PR (BUCC) | BUCC.v2 |
|-|-|-|-|
| de-en | 99.35 | 99.3633 | 99.4294 |
| fr-en | 98.72 | 98.716 | 98.9489 |
| ru-en | 97.78 | 97.7755 | 97.4614 |
| zh-en | 99.16 | 99.1575 | 99.2277 |
> fix: rollback BUCC revision

- mteb/load_results/load_results.py
- mteb/load_results/task_results.py
- mteb/tasks/Classification/eng/EmotionClassification.py
- mteb/tasks/PairClassification/eng/SprintDuplicateQuestionsPC.py
- mteb/tasks/Retrieval/eng/FiQA2018Retrieval.py
- mteb/tasks/Retrieval/eng/MSMARCORetrieval.py
- mteb/tasks/Retrieval/eng/QuoraRetrieval.py
- mteb/tasks/Retrieval/eng/SciFactRetrieval.py
potentially related to #1724
- redacts missing subsets to avoid 100+ subsets printed to a max of 2 (see below)
- reduce to logging.info instead of logging.warning
- removed splits that are commonly never evaluated on and thus also the errors for them being missing
The second part removed quite a few warnings (4930 to 3865)
It also seems like these train splits were accidentally included in some of the MMTEB benchmark.
This will remove those splits from those benchmarks (which are all in beta, so I believe that is fine). We will have to recompute the tables for the paper though (which we should probably do anyway).
I also found what I believe to be an error: Scifact (train) was is included in MTEB(Medical). I have removed the "train" split (alspochecked other tasks in benchmark)
Here is a …
> feat: reduce logging for load_results()

- mteb/models/e5_v.py
Fixes #1647 
Running `python mteb/models/e5_v.py` now returns
```
ImportError: This wrapper only works with transformers==4.44.2
```
> fix: add version check e5-v in mieb

- mteb/evaluation/evaluators/RetrievalEvaluator.py
- mteb/models/rerankers_custom.py
- mteb/models/rerankers_monot5_based.py
Closes https://github.com/embeddings-benchmark/mteb/issues/1671
- When running from the CLI, the device is passed to the model, but `RerankingWrapper` didn’t account for it.  
- In reranking tasks, there are no instructions for each sentence, so `None` is appended to the end of the query.  
- The `predict` function initially expected `query`, `passage`, and `instruction` every time, but now it checks the number of parameters passed.
> fix: allow kwargs in init for RerankingWrapper

- mteb/leaderboard/app.py
- mteb/leaderboard/figures.py
- mteb/load_results/load_results.py
- mteb/load_results/task_results.py
When using the leaderboard, only main scores get loaded thereby preventing OOM errors.
> Fixed result loading on leaderboard

- mteb/leaderboard/app.py
- mteb/leaderboard/table.py
- mteb/load_results/benchmark_results.py
- mteb/load_results/task_results.py
Due to the huge increase in data, I needed to optimize the leaderboard again.
Since one of the main issues was the amount of time it would take to call `get_scores()` I wrote a faster, more limited version plus I made sure scores only get calculated when absolutely necessary. 
I made the function itself faster by avoiding memory allocations wherever possible. On a larger scale this corresponds to a roughly 2.5x speed increase to `get_scores`
I also added smarter managing of user-induced and callback-induced state changes, thereby drastically reducing the number of unnecessary callbacks.
The difference is night and day, the leaderboard went from being barely usable to quite fast :zap:
> fix: Leaderboard Speedup

- mteb/leaderboard/table.py
- mteb/load_results/task_results.py
We had an issue where sometimes the mean(task_type) column would come out to be something different than mean(task) when there was a single task type on a benchmark.
I have fixed this issue, as well as a problem with `get_score`.
> fix: Fixed task_type aggregation on leaderboard

- mteb/evaluation/evaluators/RetrievalEvaluator.py
- mteb/models/sentence_transformer_wrapper.py
Fixes ColBERT similarity()
https://github.com/embeddings-benchmark/mteb/pull/1594
CC @Samoed
> fix: fixes implementation of similarity()

- mteb/leaderboard/app.py
- mteb/load_results/task_results.py
- scripts/compare_leaderboard_results.py
ref https://github.com/embeddings-benchmark/mteb/issues/1571#issuecomment-2583329317
Results of script: [results.json](https://github.com/user-attachments/files/18382085/results.json) (this is jsonl file, but github don't allow to upload it as jsonl, only as json)
| Task Name | Old Leaderboard | New Leaderboard |
|-----------|-----------------|-----------------|
| AmazonCounterfactualClassification | 71.87 | 74.8 |
| AmazonPolarityClassification | 88.61 | 88.7 |
| AmazonReviewsClassification | 45.75 | 44.7 |
| ArguAna | 39.09 | 39.06 |
| ArxivClusteringP2P | 39.22 | 39.22 |
| ArxivClusteringS2S | 30.8 | 30.8 |
| AskUbuntuDupQuestions | 56.42 | 57.88 |
| BIOSSES | 82.46 | 82.26 |
| Banking77Classification | 70.44 | 79.42 |
| BiorxivClusteringP2P | 35.84 | 35.75 |
| BiorxivClusteringS2S | …
> other: add script for leaderboard compare

- mteb/models/sentence_transformer_wrapper.py
- mteb/models/sentence_transformers_models.py
- mteb/models/wrapper.py
Closes https://github.com/embeddings-benchmark/mteb/issues/1731
> [v2] fix contriever (add similarity_fn_name to ST wrapper)

- mteb/evaluation/MTEB.py
- tests/test_benchmark/test_benchmark.py
Fixes `_run_eval()` for `co2_tracker=False` and adds a corresponding test
> fix: [v2] _run_eval() for case: co2_tracker False & add test

- mteb/models/openai_models.py
>  While running the benchmark again for all tasks, I ran into an error while evaluating a classification task. Digging deeper, I noticed something weird. OpenAI text embedding models generally have a context length of 8192 (if you go over that, the API throws an error). But it looks like the `text-embedding-ada-002` model actually has a context length of 8191. If you push it to 8192 tokens, the API doesn’t throw an error (probably to align with the `text-embedding-3-*` models), but the model sometimes returns null values instead. I think we should update `openai_models.py` to fix this. Here’s a script to reproduce the issue, change 8191 to 8192 and see the results.
> 
> ```python
> from openai import OpenAI
> import tiktoken
> import numpy as np
> 
> client = OpenAI()
> encoding = …
```
> fix: update max tokens for OpenAI

- mteb/benchmarks/benchmarks.py
Fixes #1789
@imenelydiaker, @x-tabdeveloping, @gowitheflow-1998 and @Muennighoff I have added the three of you.
@isaac-chung let me know if I can add you to MMTEB tasks as well.
@slvnwhrl would love to add you as a contact person for the german benchmark if you wish?
similar for @rafalposwiata and the polish benchmark.
> fix: Added contacts to benchmarks

- mteb/abstasks/AbsTask.py
- mteb/abstasks/MultilingualTask.py
- mteb/benchmarks/benchmarks.py
- mteb/languages.py
- mteb/overview.py
- Updated task filtering adding exclusive_language_filter and hf_subset
- fix bug in MTEB where cross-lingual splits were included
- also fix bug where "en-ext" was included in AmazonCounterfactualClassification
- added missing language filtering to MTEB(europe, beta) and MTEB(indic, beta)
fixes #1757
fixes https://github.com/embeddings-benchmark/mteb/issues/1757
The following code outlines the problems:
```py
import mteb
from mteb.benchmarks import MTEB_ENG_CLASSIC
task = [t for t in MTEB_ENG_CLASSIC.tasks if t.metadata.name == "STS22"][0]
task = mteb.get_task("STS22", languages=["eng"])
task.hf_subsets
task = [t for t in MTEB_ENG_CLASSIC.tasks if t.metadata.name == "STS22"][0]
task.hf_subsets
task = mteb.get_task("STS22", hf_subsets=["en"])
task = mteb.get_task("STS22", …
```
> feat: Update task filtering, fixing bug which included cross-lingual tasks in overly many benchmarks

- mteb/load_results/task_results.py
ref https://github.com/embeddings-benchmark/mteb/issues/1797
Retrieval and PairClassification scores were loaded incorrect
> fix: loading pre 11

- mteb/leaderboard/app.py
- mteb/load_results/load_results.py
- pyproject.toml
- scripts/compare_leaderboard_results.py
Previously, results from `no_revision_available` were filtered out, because it tried to match `intfloat/multilingual-e5-small` and `intfloat__multilingual-e5-small` (dir name). Also updated script for leaderboard comparison. I tried to build a leaderboard, but I got OOM.
| Task Name | Old Leaderboard | New Leaderboard |
|-----------|-----------------|-----------------|
| T2Retrieval | 71.39 | 71.39 |
| MMarcoRetrieval | 73.17 | 73.17 |
| DuRetrieval | 81.35 | 81.35 |
| CovidRetrieval | 72.82 | 72.82 |
| CmedqaRetrieval | 24.38 | 24.38 |
| EcomRetrieval | 53.56 | 53.56 |
| MedicalRetrieval | 44.84 | 44.84 |
| VideoRetrieval | 58.09 | 58.09 |
| T2Reranking | 65.24 | 65.24 |
| MMarcoReranking | 24.33 | 24.33 |
| CMedQAv1-reranking | N/A | 63.44 |
| CMedQAv2-reranking | N/A | 62.41 |
| Ocnli …
> fix: allow to load no revision available

- mteb/leaderboard/app.py
- mteb/leaderboard/table.py
- mteb/load_results/benchmark_results.py
Added a number of minor fixes:
- `join_revision` now prefers when revision is specified as opposed to `"no_revision_available"`
- Fixed problems with zero-shot filtering #1807 
- Fixed aggregation issues on a task type level #1809
> fix: Zero shot and aggregation on Leaderboard

- Makefile
- mteb/models/sentence_transformers_models.py
- scripts/extract_model_names.py
Fixes #1756 
A change to `mteb/models/sentence_transformers_models.py` only results in `sentence-transformers/all-MiniLM-L6-v2` written to `scripts/model_names.txt` now using the `make model-load-test` command. The scripts can still be used separately to run existing options.
It shouldn't and it doesn't. When models are added from scratch, the PRs are to follow the [relevant docs](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_model.md) and PR checklist. We saw an influx of model meta because of the leaderboard backfill. Every change to a model file now will trigger a model load test that takes 1 model from each file. The rest (loading, running, getting results) does not change and will remain the same as before.
This CI workflow is mainly for validating any updates …
> ci: only return 1 model_name per file

- mteb/models/bge_models.py
ref https://github.com/embeddings-benchmark/mteb/issues/1803
> fix: add bge-m3 `ModelMeta`

- mteb/evaluation/evaluators/RetrievalEvaluator.py
> fix: bm25s

- mteb/abstasks/Image/AbsTaskImageMultilabelClassification.py
- mteb/tasks/Image/ImageMultilabelClassification/eng/PascalVOC2007.py
Fixes https://github.com/embeddings-benchmark/mteb/issues/1792
Fixing the computation of the `lrap` metric for multi-label classification. `lrap` is supposed to [operate on continuous scores](https://scikit-learn.org/1.5/modules/generated/sklearn.metrics.label_ranking_average_precision_score.html), instead of predicted labels. This change largely smooths the large performance range in `lrap` across models brought by change in `samples_per_label`.
Was trying to fix the same for main but got a chain of failed tests (mainly because `main` is using `KNeighborsClassifier()` by itself - which I'm not sure would work in the expected way either; `mieb` is currently using `MultiOutputClassifer(estimator=LogisicRegression())`, which makes each label a separate binary classification problem).
> [mieb] fixing lrap computation for multi-label classification

- mteb/model_meta.py
It was removed then readded with the incorrect type and now every test is failing. This should fix it, but we should also probably add some docs and be on the same page on what this property is actually for.
> fix: Hotfixed public_training_data type annotation

- mteb/models/gme_models.py
- mteb/models/jina_models.py
- mteb/models/lens_models.py
| | BIOSSES|
| - | - |
| Model card | 80.51 |
| main | 55.5422 |
| PR | 80.4832 |
Closing https://github.com/embeddings-benchmark/mteb/issues/1862
> fix: fix jina v1, 2 models

- mteb/leaderboard/app.py
- mteb/load_results/benchmark_results.py
I have fixed the issue where we had the needed scores from the external results, and they would be overwritten by a newer revision missing some splits.
> fix: External results are preferred when only they have the needed splits

- pyproject.toml
The new plotly version came out yesterday, and it messes with the main graph in the leaderboard, therefore I have limited the plotly version in the pyproject.toml file.
Closes #1901
> fix: Limited plotly version to be less than 6.0.0

- mteb/leaderboard/app.py
TODO:
This is what it currently looks like (banner above titles Benchmarks and Model Selection):
> Adding a banner to the new MMTEB leaderboard

- mteb/abstasks/AbsTask.py
No version bump needed. Adding a warning for https://github.com/embeddings-benchmark/mteb/pull/1924
> misc: add warning for save_suffix removal from AbsTask

- mteb/tasks/Retrieval/eng/HagridRetrieval.py
Fix the following error when evaluating on HagridRetrieval:
```
ValueError: The repository for miracl/hagrid contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/miracl/hagrid.
Please pass the argument `trust_remote_code=True` to allow custom code to be run.
Do you wish to run the custom code? [y/N]
```
> Fix HagridRetrieval load_dataset "trust_remote_code"

- mteb/models/gte_models.py
> Add gte-modernbert-base

- mteb/tasks/Retrieval/nld/SCIDOCSNLRetrieval.py
The language mistake in [SCIDOCSNLRetrieval.py](https://github.com/nikolay-banar/mteb/edit/main/mteb/tasks/Retrieval/nld/SCIDOCSNLRetrieval.py) is fixed.
> fix: BEIR-NL metadata mistake

- mteb/models/sentence_transformers_models.py
This PR adds `sentence-transformer-xxl` model to mteb, as requested in #1998. We modify the `mteb/models/sentence_transformers_models.py` with the metadata of Sentence Transformer XXL.
Closes #1998
@Muennighoff @KennethEnevoldsen
> Adding sentence-transformer-xxl model to mteb

- mteb/benchmarks/benchmarks.py
I'm not sure the generalization argument makes a lot of sense because the other version uses the ~same tasks so any model tuned the first version is also tuned to that one I think? Maybe I am wrong 🤔
> docs: update MTEB eng classic benchmark description 

- scripts/make_leaderboard.py
Added a script to create and save a leaderboard locally for a given benchmark as discussed in https://github.com/embeddings-benchmark/mteb/discussions/2011.
The script retrieves results, parses them to a Pandas DF, prints them, and (optionally) saves them to a CSV. It uses the same functionality used for generating the live leaderboard. This makes it much easier to generate results locally and check aggregate scores before submitting them to MTEB.
NOTE: I named the script `make_leaderboard` but open to other suggestions.
The script can be used as follows:
`python scripts/make_leaderboard --benchmark "MTEB(eng)" --save-path "leaderboard_results"`
Optionally, a custom results repo can be used (default is https://github.com/embeddings-benchmark/results), and specific models can be requested, …
> fix: Added script for generating and saving a local leaderboard

- mteb/leaderboard/app.py
> fix: Add column descriptions to leaderboard

- mteb/benchmarks/benchmarks.py
- mteb/load_results/task_results.py
- mteb/tasks/Retrieval/eng/BrightRetrieval.py
- tests/test_load_results/test_task_results.py
fixed #1978 
- Fixed bug in validate_and_filter()
- Added tests for this
- Added bright (long)
- problem: bright (long) uses recall@1 as its main score. Not sure how to resolve that? (added issue #2046)
- Fixed bright to only use standard split
@x-tabdeveloping seems like the filtering does not check for splits, this seems a bit worrying to me:
Results from BRIGHT (long):
Results from BRIGHT:
---
Did a bit of a debugging process. It I have now fixed it in `validate_and_filter()`.
You can see the diff here:
```py
import mteb
task = mteb.get_task("BrightRetrieval")
res = mteb.load_results(tasks=[task])
res_filtered = res.filter_models().join_revisions()
[m for m in res_filtered.model_results if m.model_name == "GritLM/GritLM-7B"][
0
].task_results[0].get_score()
bench: mteb.Benchmark = …
```
> fix: Add BRIGHT (long)

- mteb/models/e5_models.py
We've missed `MIRACL` and `Mr.Tydi`
https://arxiv.org/pdf/2402.05672
> fix: add missing `e5` training datasets

- mteb/leaderboard/table.py
- pyproject.toml
This PR enhances the leaderboard UI by freezing `Rank` and `Model` columns on the `Summary` table and the `Model` column on the `Performance per task` table. With this change, users can scroll horizontally without losing track of model.
Addresses #2033 
https://github.com/user-attachments/assets/7a62b0fd-b581-43fb-8922-6a26b6cab4ee
> fix: Freeze model/rank columns in leaderboard

- mteb/benchmarks/benchmarks.py
> fix: Fixed previous incorrect specification of splits for CMTEB ( MTEB(cmn, v1) )

- mteb/evaluation/MTEB.py
- tests/test_benchmark/mock_models.py
- tests/test_benchmark/test_benchmark.py
Fixes #2075 
- Added back task filtering by modalities. 
- Added unit test to cover cases of running models with different modalities as tasks
When running `mteb run -m average_word_embeddings_komninos -t MNIST`, we now get (instead of an exception / error):
```
────────────────────────────────────────────────────────────────────────────── Selected tasks  ───────────────────────────────────────────────────────────────────────────────
ImageClassification
- MNIST, i2i
INFO:mteb.evaluation.MTEB:
********************** Evaluating MNIST **********************
INFO:mteb.evaluation.MTEB:average_word_embeddings_komninos only supports ['text'], but the task modalities are ['image'].
```
> fix: Add back task filtering by modalities

- mteb/abstasks/Image/AbsTaskAny2TextMultipleChoice.py
- mteb/descriptive_stats/Image/Any2TextMutipleChoice/CVBenchCount.json
- mteb/descriptive_stats/Image/Any2TextMutipleChoice/CVBenchDepth.json
- mteb/descriptive_stats/Image/Any2TextMutipleChoice/CVBenchDistance.json
- mteb/descriptive_stats/Image/Any2TextMutipleChoice/CVBenchRelation.json
- Add Any2TextMutipleChoice Descriptive Statistics
- Run on all 4 tasks in this type
> misc: Add Any2TextMutipleChoice Descriptive Statistics

- mteb/models/arctic_models.py
- mteb/models/e5_instruct.py
- mteb/models/gte_models.py
- mteb/models/salesforce_models.py
Reported with references to paper + quotes.
> fix: Updated model annotations for GTE, e5, gritlm, and SFR models

- mteb/leaderboard/app.py
Adding Google as a sponsor and making some changes to the headline in anticipation of MIEB appearing in the LB soon i.e. framing it as a leaderboard for anything that is "Embedding" --- Please let me know if you have any concerns!
> docs: Fix typos & refine text

- mteb/abstasks/AbsTaskClusteringFast.py
- mteb/abstasks/AbsTaskInstructionRetrieval.py
- mteb/evaluation/MTEB.py
- mteb/models/rerankers_custom.py
- mteb/tasks/BitextMining/vie/VieMedEVBitextMining.py
- pyproject.toml
- scripts/running_model/check_results.py
- scripts/task_selection/create_main_results_table.ipynb
- tests/test_TaskMetadata.py
- tests/test_cli.py
- tests/test_tasks/test_all_abstasks.py
Currently you get the error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 5.16.0 requires ruff>=0.9.3; sys_platform != "emscripten", but you have ruff 0.6.4 which is incompatible.
```
I have change ruff to the latest version (0.9.7). This results in the same number of changes as using 0.9.3 so we might as well use the latest.
Note that this will cause merge conflicts with v2 (updating ruff and formatting or doing an immediate merge should solve those issues)
> fix: Upgrade ruff to be gradio compatible

- mteb/models/e5_instruct.py
In their model card they're referring to multilingual-e5 tech report. I think they've used datasets from multilingual models
> update e5 instruct training data

- mteb/models/sentence_transformers_models.py
Fixes #2109 
This adds ModelMeta's for:
* https://huggingface.co/sentence-transformers/static-retrieval-mrl-en-v1
* https://huggingface.co/sentence-transformers/static-similarity-mrl-multilingual-v1
I'm running evaluations for these for https://github.com/embeddings-benchmark/results now.
---
- Tom Aarsen
> Add 2 new Static Sentence Transformer models

- tests/test_tasks/test_all_abstasks.py
This simplified the test and also make it a lot simpler. It also removed about 100 test cases which where all to the same API call.
> test: fix dataset availability test

- mteb/leaderboard/app.py
- mteb/leaderboard/table.py
- mteb/model_meta.py
This PR includes a proposed solution to the issues we've been having with our previous way of filtering for zero-shot models.
Zero-shot-ness is now of a gradual nature and shows up in the main table as a percentage along with accompanying colours.
I have also changed the zero-shot filtering scheme to better fit the new system.
Now all models will be visible by default, but one can choose to hide the ones that have been trained on any of the datasets, or ones, whose makers did not disclose their training data.
> Added zero-shot percentages and different filtering scheme

- mteb/models/mxbai_models.py
I received this email from the Mixedbread team:
> as mentioned in our blog post ([https://www.mixedbread.com/blog/mxbai-embed-large-v1#built-for-rag-and-real-world-use-cases:~:text=During%20the%20whole,related%20use%20cases](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.mixedbread.com%2Fblog%2Fmxbai-embed-large-v1%23built-for-rag-and-real-world-use-cases%3A~%3Atext%3DDuring%2520the%2520whole%2Crelated%2520use%2520cases&data=05%7C02%7Cmartonkardos%40cas.au.dk%7C44d7acaec50143eb9b7f08dd57468d7e%7C61fd1d36fecb47cab7d7d0df0370a198%7C1%7C0%7C638762682729840700%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=EzK3ibYx%2BeTlYwRy9bVNXgRRDRuXjakTBDNYt1CixYk%3D&reserved=0).) We do not …
> Added training data annotations to MXBAI

- mteb/abstasks/Image/AbsTaskAny2AnyRetrieval.py
Fixes #1686 
Able to get this down to 16 seconds by not using row-by-row operation and instead by using numpy. 
```
INFO:mteb.abstasks.Image.AbsTaskAny2AnyRetrieval:Fri Feb 28 16:36:45 2025 - Done load qrels, before map qrels_dict
INFO:mteb.abstasks.Image.AbsTaskAny2AnyRetrieval:Fri Feb 28 16:37:01 2025 - Done qrels_dict
```
Reproduced the same results on `mteb run -t Flickr30kT2IRetrieval -m openai/clip-vit-base-patch16` before and after the change.
> misc: Speed up qrel creation in any2anyretrieval

- mteb/abstasks/TaskMetadata.py
- mteb/evaluation/evaluators/Audio/ClusteringEvaluator.py
- mteb/models/overview.py
- mteb/models/qwen_models.py
- mteb/models/wav2vec_models.py
- mteb/models/wavlm_models.py
- mteb/models/whisper_models.py
- mteb/tasks/Audio/Clustering/eng/VoiceEmotions.py
- mteb/tasks/Audio/Clustering/eng/VoiceGender.py
- run.py
Reverts embeddings-benchmark/mteb#2202
> Revert "Revert "Maeb - added voice clustering task, wav2vec model and VoxCeleb dataset (subset)""

- mteb/leaderboard/app.py
- mteb/model_meta.py
Previously `is_zero_shot_on` failed when the list of tasks was empty.
> fix: Fixed leaderboard crash

- tests/test_tasks/test_all_abstasks.py
Use official API for dataset checking. Maybe this would solve the problem with dataset checking
ref https://github.com/embeddings-benchmark/mteb/pull/2201, https://github.com/embeddings-benchmark/mteb/issues/2200
CC @sam-hey
> Change `dataset on HF` test to use official api

- mteb/leaderboard/figures.py
This PR is related to the issue #2156 to remove overlapping legends from the radar chart
The Radar Plot now looks like below where the legend is shifted to the right.
> Remove overlapping legends from radar chart

- mteb/leaderboard/figures.py
This PR is related to formatting issue of "Max Tokens" specifically for Static Embedding Models related to issue #2159 . The issue occurred because some models have "Max Tokens" as `"Infinite"`or `"Unknown"`
After changes, the Performance Plot looks like this:
<details>
<summary>For model with Max Tokens as "Infinite": </summary>
</details>
<details>
<summary>For model with Max Tokens as "Unknown": </summary>
</details>
<details>
<summary>For model with Max Tokens as Some Integer value: </summary>
</details>
> Formatting issue in Performance Plot

- mteb/tasks/Audio/AudioMultilabelClassification/__init__.py
- mteb/tasks/Audio/AudioMultilabelClassification/eng/FSD50HF.py
All existing HuggingFace datasets for FSD50K were broken, either corrupt data or didn't have complete test+train split. We downloaded the original data from FreeSound and put it on HF. Tested wav2vec (results next comment)
- [✅ ] **Code Formatted**: Format the code using `make lint` to maintain consistent style.
- [✅ ] **Updated Documentation**: Add or update documentation to reflect the changes introduced in this PR.
- [❌ ] **New Tests Added**: Write tests to cover new functionality. Validate with `make test-with-coverage`.
All existing HuggingFace datasets for FSD50K were broken, either corrupt data or didn't have complete test+train split. We downloaded the original data from FreeSound and put it on HF. Tested wav2vec (results next comment)
- [ ✅] …
> Add new and complete version of FSD50K multi-label audio classification task

- mteb/models/voyage_models.py
"passage" is not a valid input for the voyage API. Remapped to "document".
> fix: bug in voyage implementation

- mteb/tasks/Audio/AudioZeroshotClassification/__init__.py
- mteb/tasks/Audio/AudioZeroshotClassification/eng/UrbanSound8k.py
Add UrbanSound8k dataset for zero-shot, partially addresses #2291. Test results in next comment
- [✅ ] **Code Formatted**: Format the code using `make lint` to maintain consistent style.
- [ ✅] **Updated Documentation**: Add or update documentation to reflect the changes introduced in this PR.
- [❌ ] **New Tests Added**: Write tests to cover new functionality. Validate with `make test-with-coverage`.
- [ ✅] I have run the following models on the task (adding the results to the pr). These can be run using the `mteb -m {model_name} -t {task_name}` command.
- [ ❌ ] If the dataset is too big (e.g. >2048 examples), considering using `self.stratified_subsampling() under dataset_transform()`
- [✅ ] I have filled out the metadata object in the dataset file …
> Add urbansound8k for zero-shot

- mteb/models/overview.py
- mteb/models/vdr_models.py
This PR is related to addition of VDR model and Training Dataset given in issue #1769
> Added VDR Model

- pyproject.toml
These errors where discovered when trying to install the package using `uv`.
We have a problem with salesforce-lavis, which is not compatible with the current set of dependencies.
> fix: Resolve conflicting dependencies

- mteb/tasks/Retrieval/multilingual/MIRACLRetrieval.py
Add `trust_remote_code` to MIRACLRetrieval to ensure that it can be loaded using newer versions of datasets
> fix: Add `trust_remote_code` to MIRACLRetrieval

- mteb/tasks/Audio/AudioMultilabelClassification/eng/FSD50HF.py
Fixes concerns of https://github.com/embeddings-benchmark/mteb/pull/2285#issuecomment-2723273989 and adds stratified subsampling for test set
> fix FSD-50K Task Metadata, Label handling and add stratified subsampling

- mteb/benchmarks/benchmarks.py
- mteb/tasks/Retrieval/eng/BrightRetrieval.py
Not sure this is the best way to fix this. Let me know if you can find a better fix.
fixes #2327
An overview of the problem is presented in the issue, but in general the issue is that you can't find the "long" split for certain domains (which are just None).
@swj0419 tagging you as I can see you did the original submission and is a co-author on the paper.
> fix: Ensure BrightRetrieval is valid to run

- mteb/evaluation/evaluators/Image/Any2AnyMultiChoiceEvaluator.py
- mteb/evaluation/evaluators/Image/ImageTextPairClassificationEvaluator.py
- tests/test_benchmark/test_benchmark.py
Closes https://github.com/embeddings-benchmark/mteb/issues/2275
> Pass task name to all evaluators

- mteb/benchmarks/benchmark.py
- mteb/benchmarks/benchmarks.py
- mteb/benchmarks/get_benchmark.py
- mteb/leaderboard/app.py
fixes #2413
This only removed the benchmark from the leaderboard but keep it in MTEB.
> fix: Add option to remove benchmark from leaderboard

- mteb/leaderboard/table.py
This PR is addition of memory usage column for models on leaderboard.
Closes #1935 
<details>
<summary> The leaderboard looks like: </summary> 
</details>
> Added Memory Usage column on leaderboard

- README.md
- mteb/benchmarks/benchmarks.py
Feel free to reverse to non-chrono if you prefer; thought maybe it is clearer
> Fix typos; Standardize spacing; Chronological order

- docs/adding_a_model.md
- mteb/models/blip2_models.py
- mteb/models/bm25.py
- mteb/models/cohere_v.py
- mteb/models/colbert_models.py
- mteb/models/google_models.py
- mteb/models/instruct_wrapper.py
- mteb/models/jina_models.py
- mteb/models/llm2clip_models.py
- mteb/models/llm2vec_models.py
- mteb/models/moco_models.py
- mteb/models/model2vec_models.py
- mteb/models/openai_models.py
- mteb/models/openclip_models.py
- mteb/models/repllama_models.py
- mteb/models/rerankers_custom.py
- mteb/models/vlm2vec_models.py
- mteb/models/voyage_models.py
- mteb/models/voyage_v.py
- mteb/requires_package.py
- pyproject.toml
This PR is related to addition of model specific dependencies in pyproject.toml as well as giving detailed and clear warning using` requires_package`.
Closes #2398 .
> Add model specific dependencies in pyproject.toml

- mteb/leaderboard/app.py
- mteb/leaderboard/table.py
- scripts/make_leaderboard.py
This PR is related to applying background gradients for all columns in summary table performance per task table on leaderboard for better visibility as described in issue #2382 
Closes #2382 
<details>
<summary> Summary Table </summary>
</details>
<details>
<summary> Performance Per Task Table </summary>
</details>
> Add Background Gradients in Summary and Task Table

- mteb/leaderboard/table.py
This PR is just quick fix because after merge of PR #2392 the command `python -m mteb.leaderboard.app` was returning error, because in PR #2428, a new column name "Memory Usage (MB)" is added to leaderboard which needs to be excluded from gradient background styling.
> leaderboard fix

- mteb/tasks/Retrieval/eng/NanoDBPediaRetrieval.py
Hello mteb maintainers, @Muennighoff,  @Samoed 
The original DBPedia has a prompt, but since NanoDBPedia did not have one, I added it
It would be grateful if you could check.
Thank you.
- Seongtae Hong
> fix: add prompt to NanoDBPedia

- tests/test_tasks/test_all_abstasks.py
> fix: Ignore datasets not available in tests

- mteb/abstasks/TaskMetadata.py
- tests/test_TaskMetadata.py
Fixes #2500
- Currently, a TaskMetadata with eval_langs=["eng_Latn"] will pass tests/test_TaskMetadata.py::test_all_metadata_is_filled_and_valid (when it should fail)
- unnest the if statements in test_all_metadata_is_filled_and_valid
- add check if "-" is in the code to avoid the uncaught error.
- skip AbsTaskAggregate instead of manually adding each instance in `_HISTORIC_DATASETS`
> ci: refactor TaskMetadata eval langs test

- mteb/benchmarks/benchmarks.py
In MIEB-lite, specify the multilingual parts of the multilingual visualSTS tasks (i.e. the AggTasks that _exclude_ English) to match the paper.
I'm afk right now - will spin up a local LB to double check.
> [MIEB] Specify only the multilingual AggTask for MIEB-lite

- mteb/abstasks/AbsTask.py
- mteb/abstasks/aggregated_task.py
- mteb/evaluation/MTEB.py
- mteb/overview.py
- tests/test_TaskMetadata.py
- tests/test_overview.py
- tests/test_tasks/test_all_abstasks.py
> fix: Update mteb.get_tasks with an exclude_aggregate parameter to exclude aggregate tasks

- mteb/models/jina_models.py
Fixes incorrect arguments passed to `requires_package` for `einops` and `flash_attn`. The check still failed even after running suggested installation commands (`pip install 'mteb[jina]'` and `pip install 'mteb[flash_attention]'`) because the function was checking for the wrong required package names.
> fix: Update requirements in JinaWrapper

- mteb/models/jasper_models.py
Closes #2474 
Changed to bfloat16. @Samoed @KennethEnevoldsen
> fix: jasper models embeddings having nan values

- mteb/encoder_interface.py
I suspect these should have been deleted.
> Remove the comments from ImageEncoder

- mteb/benchmarks/benchmarks.py
- mteb/leaderboard/benchmark_selector.py
- Update MIEB benchmark display names to image-text
- Add img only display name and icon
> Add image only MIEB benchmark to LB left panel

- mteb/abstasks/AbsTask.py
- mteb/abstasks/AbsTaskRetrieval.py
- mteb/abstasks/TaskMetadata.py
- mteb/abstasks/dataset_card_template.md
- mteb/tasks/PairClassification/multilingual/XNLI.py
- pyproject.toml
- tests/test_reproducible_workflow.py
Closes https://github.com/embeddings-benchmark/mteb/issues/1892
I've generated readme for `XNLIV2` https://huggingface.co/datasets/mteb/XNLIV2 and `AlloprofReranking` https://huggingface.co/datasets/mteb/AlloprofReranking
```python
import mteb
task = mteb.get_task("XNLIV2")
task_card = task.generate_dataset_card()
task_card.push_to_hub("mteb/XNLIV2")
```
Currently, updating a `DatasetCard` requires pushing all data to the Hub, because Hugging Face stores dataset information in the `README`. When the card is regenerated, the split information can break. Although there's a method to load the full dataset card, there isn’t a way to directly load the existing `DatasetCardData`.
> [v2] Dataset card generation

- mteb/tasks/PairClassification/__init__.py
- mteb/tasks/PairClassification/dan/TalemaaderPC.py
---
For issue #2608 :
- Dataset: https://huggingface.co/datasets/mteb/talemaader_pc
- Scores: 
<details><summary>`intfloat/multilingual-e5-small`</summary>
```json 
{
"dataset_revision": "e714d53c059ca83d56c41d22f800da8245bb87fc",
"task_name": "TalemaaderPC",
"mteb_version": "1.38.3",
"scores": {
"test": [
{
"similarity_accuracy": 0.74975,
"similarity_accuracy_threshold": 0.993789,
"similarity_f1": 0.400241,
"similarity_f1_threshold": 0.778437,
"similarity_precision": 0.250314,
"similarity_recall": 0.998,
"similarity_ap": 0.207258,
"cosine_accuracy": 0.74975,
"cosine_accuracy_threshold": 0.993789,
"cosine_f1": 0.400241,
"cosine_f1_threshold": 0.778437,
"cosine_precision": 0.250314,
"cosine_recall": 0.998,
"cosine_ap": 0.207259,
"manhattan_accuracy": …
```
> Add Talemaader pair classification task

- scripts/format_citations.py
> Remove `typer` dependency from citation script

- .github/workflows/leaderboard_build.yml
- Makefile
- tests/test_leaderboard.py
> Add tests for leaderboard build

- mteb/tasks/Classification/ara/HotelReviewSentimentClassification.py
- mteb/tasks/Classification/ara/TweetEmotionClassification.py
- mteb/tasks/Classification/deu/TenKGnadClassification.py
- mteb/tasks/Classification/eng/ArxivClassification.py
- mteb/tasks/Classification/eng/PatentClassification.py
- mteb/tasks/Classification/fil/FilipinoHateSpeechClassification.py
- mteb/tasks/Classification/mya/MyanmarNews.py
- mteb/tasks/Classification/nld/DutchBookReviewSentimentClassification.py
- mteb/tasks/Classification/swe/SwedishSentimentClassification.py
- mteb/tasks/Classification/tha/WisesightSentimentClassification.py
- mteb/tasks/Classification/urd/UrduRomanSentimentClassification.py
- mteb/tasks/Retrieval/multilingual/IndicQARetrieval.py
- mteb/tasks/STS/jpn/JSTS.py
- pyproject.toml
> fix: Update datasets wich can't be loaded with `datasets>=3.0` 

- mteb/models/openai_models.py
closes: #1650
tested using:
```py
mdl = mteb.get_model("openai/text-embedding-3-large")
arr = mdl.encode(["Hello world!"])
print(arr.shape)
arr = mdl.encode(["Hello world!", ""])
print(arr.shape)
print(arr[1])
arr = mdl.encode(["", "", ""])
print(arr.shape)
print(arr[1])
```
which returns:
```
(1, 3072)
(2, 3072)
[0. 0. 0. ... 0. 0. 0.]
(3, 3072)
[0. 0. 0. ... 0. 0. 0.]
```
> fix: Allow empty string for openai models

- docs/adding_a_benchmark.md
- docs/adding_a_model.md
> Correction in docs

- .github/pull_request_template.md
- docs/adding_a_dataset.md
- docs/adding_a_model.md
1) Updated PR template to only include checklist for datasets and models. The other checklists were essentially just tests.
2) I have updated the documentation for adding models. Notably I have split out the implementation segment, which I think makes it more readable.
3) Required that you argue for a dataset before addition
fixes #2568
> docs: Updated the PR template and improved submission docs

- mteb/models/google_models.py
Hi,
this is a little fix for an invalid task type of the Google embedding models.
The type `SIMILARITY` is invalid. The correct one is `SEMANTIC_SIMILARITY`. 
See https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/task-types#supported_task_types
Best,
Malte
> Fixing Google embedding task type for STS

- pyproject.toml
Now we’re using `fix` for new models and datasets to bump the MTEB version. I propose adding new prefixes to indicate version bumps. 
CC @KennethEnevoldsen
> add new prefixes to releases

- mteb/tasks/Retrieval/eng/BrightRetrieval.py
Seems like the revision wasn't specified correctly. I have respecified it and checked that it can load.
Checked using:
```py
import mteb
task = mteb.get_task("BrightRetrieval", eval_splits=["standard"])
task.load_data()
```
fixes #2811
> fix: Ensure bright uses the correct revision

- mteb/models/ru_sentence_models.py
> model: Add custom instructions for GigaEmbeddings

- mteb/models/wrapper.py
- tests/test_benchmark/test_benchmark.py
Fix validation for tasks with multiple `-`
>  if the task dataset contains a "-", there will be an error in parsing the task_name, such as when specifying "NQ-PL-query".
Ref https://github.com/embeddings-benchmark/results/pull/217#issuecomment-2996133931
CC @YanshekWoo
> fix: prompt validation for tasks with `-`

- mteb/benchmarks/benchmarks.py
- mteb/descriptive_stats/InstructionRetrieval/IFIRAila.json
- mteb/descriptive_stats/InstructionRetrieval/IFIRCds.json
- mteb/descriptive_stats/InstructionRetrieval/IFIRFiQA.json
- mteb/descriptive_stats/InstructionRetrieval/IFIRFire.json
- mteb/descriptive_stats/InstructionRetrieval/IFIRNFCorpus.json
- mteb/descriptive_stats/InstructionRetrieval/IFIRPm.json
- mteb/descriptive_stats/InstructionRetrieval/IFIRScifact.json
- mteb/tasks/InstructionRetrieval/eng/IFIRAilaRetrieval.py
- mteb/tasks/InstructionRetrieval/eng/IFIRCdsRetrieval.py
- mteb/tasks/InstructionRetrieval/eng/IFIRFiQARetrieval.py
- mteb/tasks/InstructionRetrieval/eng/IFIRFireRetrieval.py
- mteb/tasks/InstructionRetrieval/eng/IFIRNFCorpusRetrieval.py
- mteb/tasks/InstructionRetrieval/eng/IFIRPmRetrieval.py
- mteb/tasks/InstructionRetrieval/eng/IFIRScifactRetrieval.py
- mteb/tasks/InstructionRetrieval/eng/__init__.py
> dataset: Add IFIR benchmark

- mteb/models/seed_1_6_embedding_models.py
Due to ByteDance's naming convention of seed models, rename seed-1.6-embedding to seed1.6-embedding
Checklist
> rename seed-1.6-embedding to seed1.6-embedding

- mteb/models/jina_models.py
- tests/test_benchmark/mock_models.py
- tests/test_benchmark/test_benchmark.py
Previously, tests are failing with error. I think `average_word_embeddings_levy_dependency` is not fully compatible now
```
FAILED tests/test_benchmark/test_benchmark.py::test_prompt_name_passed_to_all_encodes[task_name0] - ValueError: A configuration of type rag cannot be instantiated because both `question_encoder` and `generator` sub-configurations were not passed, only {'attn_implementation': None}
```
> fix tests to be compatible with `SentenceTransformers` `v5`

- mteb/models/jina_models.py
- mteb/tasks/Reranking/__init__.py
- mteb/tasks/Reranking/jpn/JQaRAReranking.py
- mteb/tasks/Reranking/jpn/JaCWIRReranking.py
- mteb/tasks/Retrieval/__init__.py
- mteb/tasks/Retrieval/jpn/JaCWIRRetrieval.py
- mteb/tasks/Retrieval/jpn/NLPJournalAbsArticleRetrieval.py
- mteb/tasks/Retrieval/jpn/NLPJournalAbsIntroRetrieval.py
- mteb/tasks/Retrieval/jpn/NLPJournalTitleAbsRetrieval.py
- mteb/tasks/Retrieval/jpn/NLPJournalTitleIntroRetrieval.py
I added the following new Japanese datasets
- [JaCWIR](https://huggingface.co/datasets/hotchpotch/JaCWIR) for retrieval and reranking
- [JQaRA](https://huggingface.co/datasets/hotchpotch/JQaRA) for reranking
I [added](https://huggingface.co/datasets/sbintuitions/JMTEB/discussions/3) them to [JMTEB](https://huggingface.co/datasets/sbintuitions/JMTEB) (Japanese MTEB) and now synchronize them to MTEB.
I also fixed the ANLP related datasets (`NLPJournalTitleIntroRetrieval`, `NLPJournalTitleAbsRetrieval`, `NLPJournalAbsIntroRetrieval`) as the origin dataset has been updated. For reproductivity purpose, I separated v1 (~2020-06-15, has been used for a while) and v2 (~2025-06-15, recently updated) by accessing to `dataset_version` in JMTEB to make it available to access the previous version (for …
> Add and fix some Japanese datasets: ANLP datasets, JaCWIR, JQaRA

- mteb/tasks/Audio/Any2AnyRetrieval/Clotho.py
- mteb/tasks/Audio/Any2AnyRetrieval/__init__.py
Fixes #2053
model: laion/clap-htsat-fused.
```
ClothoA2TRetrieval
"cv_recall_at_1": 0.17895,
"cv_recall_at_3": 0.31962,
"cv_recall_at_5": 0.40574,
"cv_recall_at_10": 0.53397,
ClothoT2ARetrieval
"cv_recall_at_1": 0.13142,
"cv_recall_at_3": 0.26285,
"cv_recall_at_5": 0.33572,
"cv_recall_at_10": 0.44655,
```
> dataset: add Clotho by creating the datasets on the fly

- mteb/models/msclap_models.py
- mteb/models/muq_mulan_model.py
- mteb/models/speecht5_models.py
- mteb/models/wav2clip_model.py
> fix encode() in audio models

- mteb/models/jina_models.py
This PR fixes the bug introduced in `jina-embeddings-v4` wrapper due to a recent PR #2912. Since the mapping is already updated in the `model_prompts`, we don't need to change it in the function check
> fix: replace with passage

- mteb/tasks/Retrieval/fra/BSARDRetrieval.py
The PR fixes [2906](https://github.com/embeddings-benchmark/mteb/issues/2906) by adding the second version of BSARD with the proper loader.
> dataset: Add BSARD v2, fixing the data loading issues of v1

- mteb/tasks/Retrieval/eng/GovReport.py
Hi,
I’m submitting this pull request to push the [GovReport](https://huggingface.co/datasets/launch/gov_report) dataset to MTEB.
GovReport is a dataset created by LAUNCH Lab for the purposes of training and evaluating models capable of summarizing lengthy (on average, 9k-tokens-long) US government reports.
We have reframed the problem in terms of the retrieval of reports based on their summaries, making our reformatted datasets suitable for the evaluation of legal and governmental information retrieval models.
We want to improve the coverage of legal tasks on MTEB and we believe this dataset will contribute to increasing the diversity and difficulty of MTEB.
This pull request is being submitted courtesy of [Isaacus, a legal AI research company](https://isaacus.com/).
You may find the …
> dataset: add GovReport dataset

- mteb/models/whisper_models.py
Fixes #2944 
- Cast batch to numpy
- Pad with max_length instead of longest
`mteb run -m openai/whisper-small -t NMSQAPairClassification` yields:
<details>
<summary>NMSQA Results</summary>
```
{'default': {'similarity_accuracy': 0.5321637426900585, 'similarity_accuracy_threshold': 0.8944698572158813, 'similarity_f1': 0.6747967479674797, 'similarity_f1_threshold': 0.8944698572158813, 'similarity_precision': 0.515527950310559, 'similarity_recall': 0.9764705882352941, 'similarity_ap': 0.45288448359423344, 'cosine_accuracy': 0.5321637426900585, 'cosine_accuracy_threshold': 0.8944698572158813, 'cosine_f1': 0.6747967479674797, 'cosine_f1_threshold': 0.8944698572158813, 'cosine_precision': 0.515527950310559, 'cosine_recall': 0.9764705882352941, 'cosine_ap': 0.45288448359423344, …
```
> [MAEB] Fix whisper model audio inference

- mteb/leaderboard/benchmark_selector.py
- mteb/tasks/Classification/slk/CSFDSKMovieReviewSentimentClassification.py
- mteb/tasks/Retrieval/__init__.py
- mteb/tasks/Retrieval/eng/BarExamQA.py
- mteb/tasks/Retrieval/eng/BillSumCA.py
- mteb/tasks/Retrieval/eng/BillSumUS.py
Hi,
I’m submitting this pull request to push the [Californian](https://huggingface.co/datasets/isaacus/mteb-BillSumCA) and [US](https://huggingface.co/datasets/isaacus/mteb-BillSumUS) splits of the [BillSum](https://huggingface.co/datasets/FiscalNote/billsum) dataset to MTEB.
BillSum is a dataset created by FiscalNote for the purposes of training and evaluating models capable of summarizing federal and state legislation.
We have reframed the problem in terms of the retrieval of bills based on their summaries, making our reformatted datasets suitable for the evaluation of legal information retrieval models.
We want to improve the coverage of legal domain tasks on MTEB and we believe this dataset will contribute to increasing the diversity and difficulty of MTEB.
This pull request is being …
> dataset: add BillSum datasets

- mteb/cache.py
- tests/test_evaluation/test_evaluate.py
> [v2] `mteb.evaluate` now saves `model_meta.json`

- mteb/models/ast_model.py
- mteb/models/clap_models.py
- mteb/models/cnn14_model.py
- mteb/models/data2vec_models.py
- mteb/models/encodec_model.py
- mteb/models/hubert_models.py
- mteb/models/mctct_model.py
- mteb/models/mms_models.py
- mteb/models/msclap_models.py
- mteb/models/muq_mulan_model.py
- mteb/models/qwen2_models.py
- mteb/models/seamlessm4t_models.py
- mteb/models/speecht5_models.py
- mteb/models/unispeech_models.py
- mteb/models/vggish_models.py
- mteb/models/wav2clip_model.py
- mteb/models/wav2vec2_models.py
- mteb/models/wavlm_models.py
- mteb/models/whisper_models.py
- mteb/models/yamnet_models.py
- Added 30-second truncation to all models.
- Added show_progress_bar kwarg for enabling/disabling progress display.
> MAEB Model Evaluation Fixes

- mteb/models/openai_models.py
https://github.com/embeddings-benchmark/mteb/issues/3002
https://github.com/embeddings-benchmark/mteb/issues/3003
Add OpenAI/text-embedding-3-small (512 dim)
Add OpenAI/text-embedding-3-large (512 dim)
> Add OpenAI models with 512 dimension

- mteb/tasks/Retrieval/nob/snl_retrieval.py
The provided revisions doesn't seem to be present on:
adrlau/navjordj-SNL_summarization_copy
Replacing with latest revision
> fix: incorrect revision for SNLRetrieval

- mteb/descriptive_stats/Retrieval/HumanEvalRetrieval.json
- mteb/tasks/Retrieval/__init__.py
- mteb/tasks/Retrieval/code/HumanEvalRetrieval.py
https://github.com/embeddings-benchmark/mteb/issues/3014
- HumanEval dataset for code retrieval tasks
- 158 queries, 158 documents
> Add HumanEvalRetrieval task

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/workflows/stale_pr.yml
Fixes https://github.com/embeddings-benchmark/mteb/issues/3064
- Labels a "needs-more-infomation" issue stale after 60 days
- Closes a stale "needs-more-infomation" issue after 7 days
- Labels a PR stale after 14 days
- Closes a stale PR after 7 days
Any update (update/comment) can reset the stale idle time on the issues/PRs.
> ci: Add stale workflow

- mteb/models/openclip_models.py
Hello,
Fixed the package detection issue in openclip_models.py that was not properly checking for packages.
While `open_clip_torch` is the pip installation name, the actual import should be done with `open_clip`. 
This caused the following bug even when the open_clip_torch library was properly installed:
```
ImportError: openclip_loader requires the open_clip_torch library but it was not found in your environment. If you want to load laion/CLIP-ViT-bigG-14-laion2B-39B-b160k models, please pip install 'mteb[open_clip_torch]' to install the package.
```
Verification logic:
```python
>>> importlib.util.find_spec("open_clip_torch")  # False
>>> importlib.util.find_spec("open_clip")        # True
```
Thanks! 😊
> fix: open_clip package validation

- mteb/leaderboard/benchmark_selector.py
- mteb/models/bedrock_models.py
- mteb/models/cohere_models.py
- mteb/models/colbert_models.py
- mteb/models/google_models.py
- mteb/models/llm2vec_models.py
- mteb/models/repllama_models.py
- mteb/models/sentence_transformer_wrapper.py
- mteb/models/voyage_models.py
- mteb/models/wrapper.py
- tests/test_benchmark/test_benchmark_integration_with_sentencetransformers.py
- tests/test_reproducible_workflow.py
As released, the `Wrapper.validate_task_to_prompt_name()` function raises a `KeyError` if it encounters any key in the prompts dictionary that doesn't match a specific formatting requirement, even if the provided prompts dictionary contained _some_ valid keys. 
In most cases, `Wrapper` subclasses would pass this `KeyError` through and cause the MTEB wrapper initialization or evaluation run to fail.
The `SentenceTransformerWrapper` behaved differently in that it would catch the error raised by `Wrapper.validate_task_to_prompt_name()` and set the model prompts to `None`, allowing the evaluation to run but without any of the prompts that would make the model perform as expected. 
The `ColBERTWrapper` subclass was trying to catch a `ValueError` that did not seem like it would ever come up. …
> fix: Improving validate_task_to_prompt_name logs and error messages

- mteb/abstasks/TaskMetadata.py
To use `field_validator` we need to add `classmethod` after it https://docs.pydantic.dev/latest/concepts/validators/#__tabbed_1_2
```python
class Model(BaseModel):
number: int
@field_validator('number', mode='after')  
@classmethod
def is_even(cls, value: int) -> int:
if value % 2 == 1:
raise ValueError(f'{value} is not an even number')
return value  
```
> fix: Add @classmethod for @field_validators in TaskMetadata 

- docs/usage/usage.md
- mteb/abstasks/AbsTask.py
- mteb/abstasks/AbsTaskRetrieval.py
fixes #2830
- Updated docs to use `mteb.evaluate` for two-stage retrieval
- Restructured so saving results is before two-stage retrieval
- Minor updates on docstring and variables (notably to avoid confusion of results and predictions)
- Updated late-interaction example (though it could use some work - see comment below)
> [v2] Use `mteb.evaluate` for two-stage retrieval

- mteb/models/overview.py
- mteb/models/youtu_models.py
- pyproject.toml
When submitting you models as a PR, please copy and paste the following checklist into pull request message:
> model: add Youtu-Embedding-V1

- pyproject.toml
Copied from `v2` with addition of `jina-v4` vs `llm2vec`
> fix: conflict dependencies

- mteb/models/colpali_models.py
Hi! 😁
I'm using `ColPali` models to evaluate ViDoRe benchmarks and encountered an `AttributeError`. The issue occurs because `ColPaliEngineWrapper.similarity()` tries to use `self.processor_kwargs`, which is not defined in the class. **I've temporarily resolved this by removing the `**self.processor_kwargs` reference.**
```
Traceback (most recent call last):
File "/KoVidore-benchmark/kovidore/evaluate.py", line 495, in run_benchmark
results = evaluation.run(model, output_folder=f"results/{model_name}", encode_kwargs = {'batch_size': batch_size})
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/KoVidore-benchmark/.venv/lib/python3.12/site-packages/mteb/evaluation/MTEB.py", line 672, in run
raise e
File …
```
> fix: AttributeError in ColPaliEngineWrapper similarity method

- .github/ISSUE_TEMPLATE/eval_request.yaml
- mteb/benchmarks/benchmarks/rteb_benchmarks.py
Adding @fzowl as you are noted as the maintainer.
> fix: Add submission references for RTEB

- mteb/benchmarks/_create_table.py
- mteb/benchmarks/benchmark.py
- mteb/benchmarks/benchmarks/benchmarks.py
- mteb/leaderboard/benchmark_selector.py
- mteb/tasks/Classification/multilingual/HUMEMultilingualSentimentClassification.py
Goal of this PR is to align the LB aggregation with the paper so that the Humans rank 4th. 
Notably:
1. created a dedicated HUMEBenchmark object, similar to how RTEB's method.
2. `[HUMEMultilingualSentimentClassification](https://huggingface.co/datasets/mteb/HUMEMultilingualSentimentClassification)` had used `nor` instead of `nob`. Changing the actual dataset and results should be done separately.
3. "Human Benchmark" added under "General Purpose" on the left side bar.
> Aggregate by subset for HUMEv1

- mteb/benchmarks/_create_table.py
- mteb/benchmarks/benchmarks/rteb_benchmarks.py
- mteb/leaderboard/app.py
- mteb/leaderboard/table.py
Move zero-shot percentage calculation to the end of summary table creation which only apply to RTEB table.
You can see the changes in: https://huggingface.co/spaces/SmileXing/leaderboard.
> Feat: Move zero-shot percentage calculation to the end of summary

- mteb/leaderboard/table.py
Currently we pin 3 columns, this makes it hard or impossible to view on phones. The 3rd column is also no longer garuanteed as RTEB leaderboard does not use the zero-shot column
> fix: Only pin model name and rank

- mteb/tasks/Retrieval/multilingual/MIRACLRetrieval.py
added prompt query for MIRACLRetrievalHardNegatives run task to mteb/mteb/tasks/Retrieval/multilingual/MIRACLRetrieval.py
> fix: add prompt for MIRACLRetrievalHardNegatives

- mteb/models/model_implementations/pylate_models.py
Hello,
As detailed [here](https://github.com/embeddings-benchmark/mteb/pull/3183#issuecomment-3376052542), there was an issue with ColBERT models using Flash Attention during training but not inference. This has been fixed in a new version of PyLate that has been released (to fix CPU inference and GPU without FA), but it also requires to use the new config from the model, which was not done because the revision of the model was set to an older one.
This fixes the issue by updating the revision to get the correct config
> Update PyLate model revision to fix inference without FA

- mteb/MTEB.py
We're decided not to use by default in `mteb.evaluate`. I aligned `mteb.MTEB` with it. Maybe test become faster. Close https://github.com/embeddings-benchmark/mteb/issues/3275
> [v2] Make co2 optioinal
