embeddings-benchmark/mteb

- mteb/tasks/Retrieval/DBPediaRetrieval.py
- mteb/tasks/Retrieval/FEVERRetrieval.py
- mteb/tasks/Retrieval/FiQA2018Retrieval.py
- mteb/tasks/Retrieval/HotpotQARetrieval.py
- mteb/tasks/Retrieval/MSMARCORetrieval.py
- mteb/tasks/Retrieval/QuoraRetrieval.py
Fixes https://github.com/embeddings-benchmark/mteb/issues/16
> Fix BEIR splits

- mteb/tasks/Reranking/MindSmallReranking.py
Fixes https://github.com/embeddings-benchmark/mteb/issues/28  along with https://huggingface.co/datasets/mteb/mind_small/discussions/1
> rename `validation`split to `test`for MindSmallReranking

- mteb/abstasks/AbsTaskClassification.py
Fixes https://github.com/embeddings-benchmark/mteb/issues/25
Should look like this now:
```
INFO:mteb.evaluation.MTEB:
********************** Evaluating Banking77Classification **********************
INFO:mteb.evaluation.MTEB:Loading dataset for Banking77Classification
Task: Banking77Classification, split: test. Running...
INFO:mteb.abstasks.AbsTaskClassification:========== Experiment 1/10 ==========
INFO:mteb.evaluation.evaluators.ClassificationEvaluator:Encoding 616 training sentences...
Batches: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 911.78it/s]
INFO:mteb.evaluation.evaluators.ClassificationEvaluator:Encodin …
```
> add logs for classification bootstrap experiments

- README.md
- mteb/evaluation/MTEB.py
Return the evaluation results dictionary if `return_resutls` is set to `True`
> Returning Evaluation results

- mteb/abstasks/AbsTaskBitextMining.py
- mteb/abstasks/AbsTaskClustering.py
- mteb/abstasks/AbsTaskPairClassification.py
- mteb/abstasks/AbsTaskReranking.py
- mteb/abstasks/AbsTaskSTS.py
- mteb/abstasks/CrosslingualTask.py
- mteb/abstasks/MultilingualTask.py
- mteb/evaluation/evaluators/ClusteringEvaluator.py
- mteb/evaluation/evaluators/SummarizationEvaluator.py
If all scores are the same in SummEval, the correlation computation will produce NaN scores.
For example for the below Machine translations, some models encode them as the same embedding.
I couldn't come up with a better solution than skipping - any better ideas?
```python
["japanese photographer yûki aoyama 's latest series of images capture po-faced teenagers in the air next to their daughters . images are from the 37-year-old 's latest book that roughly translates to daughter and a salaryman each image . the images are also to be part of a book of the father-daughter photographer . the 37-year-old has been captured by photographer photographer yûki .", "japanese photographer yûki aoyama 's latest series of images capture po-faced teenagers pictured next to their fathers leaping into …
```
> Fix SummEval NaN scores

- mteb/evaluation/MTEB.py
Solves https://github.com/embeddings-benchmark/mteb/issues/31
> Add flag to overwrite results

- scripts/redditp2p/script_clustering.py
Goes along with https://huggingface.co/datasets/mteb/reddit-clustering-p2p/discussions/1
Example:
```python
from mteb import MTEB
from mteb.abstasks.AbsTaskClustering import AbsTaskClustering
from sentence_transformers import SentenceTransformer
class RedditClusteringP2P(AbsTaskClustering):
@property
def description(self):
return {
"name": "RedditClusteringP2P",
"hf_hub_name": "mteb/reddit-clustering-p2p",
"description": (
"Clustering of title+posts from reddit. Clustering of 10 sets of 50k paragraphs and 40 sets of 10k"
" paragraphs."
),
"reference": "https://huggingface.co/datasets/sentence-transformers/reddit-title-body",
"type": "Clustering",
"category": "p2p",
"eval_splits": ["test"],
"eval_langs": ["en"],
"main_score": "v_measure",
"revision": …
```
> New RedditP2P Script

- mteb/tasks/STS/SickrSTS.py
Fixes https://github.com/embeddings-benchmark/mteb/issues/83
> Remove validation

- README.md
- mteb/abstasks/AbsTaskRetrieval.py
Needed so that the script in the readme works
> Default to false

- mteb/abstasks/AbsTaskRetrieval.py
- mteb/evaluation/MTEB.py
Added two args save_results and task_name to support cache results
> Add support for cache results

- README.md
See https://github.com/embeddings-benchmark/mteb/issues/211
> Refer to other works

- mteb/abstasks/AbsTaskBitextMining.py
- mteb/abstasks/AbsTaskClassification.py
- mteb/abstasks/AbsTaskClustering.py
- mteb/abstasks/AbsTaskPairClassification.py
- mteb/abstasks/AbsTaskReranking.py
- mteb/abstasks/AbsTaskRetrieval.py
- mteb/abstasks/AbsTaskSTS.py
- mteb/abstasks/AbsTaskSummarization.py
- mteb/tasks/BitextMining/da/BornholmskBitextMining.py
- mteb/tasks/Clustering/de/BlurbsClusteringP2P.py
- mteb/tasks/PairClassification/zh/CMTEBPairClassification.py
- mteb/tasks/Reranking/zh/CMTEBReranking.py
- mteb/tasks/Retrieval/de/GerDaLIRRetrieval.py
- mteb/tasks/STS/pl/PolishSTS.py
- mteb/tasks/Summarization/fr/SummEvalFrSummarization.py
Unfortunately, the diff contains a lot of formatting changes as well, see #256.
I've gone through it manually, and it should only be docstrings which are changed. I've had to make a few educated guesses, so a thorough look-through is definitely recommended.
@Muennighoff @KennethEnevoldsen 
Closes #250.
> docs: add dataset schemas

- .github/workflows/lint.yml
- .github/workflows/test.yml
> ci: renamed test job and workflow

- mteb/tasks/Classification/en/ToxicConversationsClassification.py
- mteb/tasks/Clustering/en/RedditClusteringP2P.py
Also tested that both taskthey run using the CLI.
Fixes #293
> fix: Fixed mispecified rev. id for datasets

- mteb/tasks/Reranking/en/MindSmallReranking.py
> fix: Update MindSmallReranking.py to have the correct hf reference

- docs/mmteb/points.md
Added missing points for SEB (added in #287)
Nb:
NorwegianCourtsBitextMining: 2
SNLClustering: 2 + 2
VGClustering: 2
NorQuadRetrieval: 2 + 2
SNLRetrieval: 2
sv:
SwednClustering: 2 + 2
SwednRetrieval: 2 + 2
SweFaqRetrieval: 2
da: 
DanFever: 2 + 2
TV2Nordretrieval: 2
TwitterHjerneRetrieval: 2
= 32
> docs: Added point for SEB

- docs/mmteb/points.md
Reasoning and approval in #280, which for some reason diverged a lot from main.
@KennethEnevoldsen Unsure if your points form #280 were already added, so have added nothing new here.
> docs: add points and affiliation for MartinBernstorff

- docs/mmteb/readme.md
> docs: Update mmteb

- .github/workflows/test.yml
- Makefile
- pyproject.toml
> fix: missing json and updated tests to not run in editable mode

- docs/mmteb/points.md
Added points for previous submissions
For a description of points for each PR see commit messages below.
Tagging the relevant persons here in case I have missed something (in a few cases I am unaware if the tasks were the first of their kind for the given language, and thus should gain a bonus point).
@guenthermi, @Muennighoff, @rasdani, @PhilipMay, @slvnwhrl, @staoxiao, @NouamaneTazi, @rafalposwiata, @violenil, @hanhainebula, @taeminlee.
I have added all the points to the main contributor, but assuming that some of the PRs have multiple contributors we can split it out.
> docs: Added points for previous submissions

- docs/adding_a_dataset.md
- docs/mmteb/points.md
- mteb/tasks/Reranking/eng/SciDocsReranking.py
Updated docs examples to avoid confusion.
> docs: Updated examples in documentation

- CONTRIBUTING.md
@KennethEnevoldsen Have added you as a post-merge review.
> chore: move and update contributing.md

- docs/mmteb/points.md
- mteb/tasks/Classification/__init__.py
- mteb/tasks/Classification/ara/RestaurantReviewSentimentClassification.py
- results/intfloat__multilingual-e5-base/RestaurantReviewSentimentClassification.json
- results/intfloat__multilingual-e5-base/model_meta.json
- results/intfloat__multilingual-e5-small/RestaurantReviewSentimentClassification.json
- results/intfloat__multilingual-e5-small/model_meta.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/RestaurantReviewSentimentClassification.json
This just adds points for the #369 pr
> Arabic reviews

- .github/workflows/lint.yml
- Makefile
- mteb/abstasks/AbsTask.py
Seems like linting check always pass, this is just to check the CI.
> style: This should fail linting

- docs/mmteb/points.md
- mteb/tasks/Classification/__init__.py
- mteb/tasks/Classification/ben/BengaliHateSpeechClassification.py
- results/intfloat/multilingual-e5-small/BengaliHateSpeechClassification.json
- results/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/BengaliHateSpeechClassification.json
- [X ] Run tests locally to make sure nothing is broken using `make test`.
> Add BengaliHateSpeechClassification

- docs/mmteb/points.md
- mteb/tasks/Classification/__init__.py
- mteb/tasks/Classification/tur/TurkishProductSentimentClassification.py
- results/intfloat__e5-small/TurkishProductSentimentClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/TurkishProductSentimentClassification.json
It is a multi domain product review sentiment dataset and it was released by the same authors as in #389.
> Turkish multidomain product review data

- docs/mmteb/points.md
- mteb/tasks/Clustering/fra/MLSUMClusteringP2P.py
- mteb/tasks/Clustering/fra/MLSUMClusteringS2S.py
Fix for issue #402 and #334.
The custom load_dataset() function was removed, which caused an error. I'll open another PR to make this dataset multilingual and improve the loading process.
> fix: add custom load dataset function for MLSUM tasks

- docs/mmteb/points.md
Hi,
great initiative with Multilingual MTEB. I added information about myself in this PR. In the next ones I will continue to contribute ;)
> Update contributor information

- docs/mmteb/points.md
Corrections from PR (@isaac-chung it seems like we both corrected your points). The 4 points from be was a 
#403
> docs: Correct review points

- docs/mmteb/points.md
- docs/mmteb/points/430.jsonl
- mteb/tasks/Classification/__init__.py
- mteb/tasks/Classification/uig/UyghurSentimentClassification.py
- results/intfloat__multilingual-e5-base/UyghurSentimentClassification.json
- results/intfloat__multilingual-e5-small/UyghurSentimentClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/UyghurSentimentClassification.json
Reason for dataset addition: Cover Uyghur in Classification
> fix: Add Uyghur Sentiment Classification

- docs/mmteb/points.md
- docs/mmteb/points/376.jsonl
- mteb/tasks/Clustering/multilingual/WikiClusteringP2P.py
- results/intfloat__multilingual-e5-small/WikiClusteringP2P.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/WikiClusteringP2P.json
* add tasks and leaderboard update
* change names to the right ones:))
* update points and start migrating to multilingual format
* add metadata and working revision
* bump revision to newest version of data
* Update mteb/tasks/Clustering/multilingual/WikiClusteringP2P.py
* Update mteb/tasks/Clustering/multilingual/WikiClusteringP2P.py
* Update mteb/tasks/Clustering/multilingual/WikiClusteringP2P.py
* Update mteb/tasks/Clustering/multilingual/WikiClusteringP2P.py
* Update mteb/tasks/Clustering/multilingual/WikiClusteringP2P.py
* update to match main
* add date and fix literal
* add result for MiniLM-L12-v2
* add scores for intfloat model
> fix: Add Wikiclustering benchmark for multiple languages:)) (#376)

- docs/mmteb/points.md
- mteb/tasks/Classification/__init__.py
- mteb/tasks/Classification/bul/BulgarianStoreReviewSentimentClassfication.py
- results/intfloat__multilingual-e5-small/BulgarianStoreReviewSentimentClassfication.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/BulgarianStoreReviewSentimentClassfication.json
* Bulgarian for (https://github.com/embeddings-benchmark/mteb/issues/361)
* This one also has a high average character length, which is rare, especially for non-English languages.
> Add Bulgarian Online Store Review Dataset

- mteb/tasks/Classification/__init__.py
- mteb/tasks/Classification/kur/KurdishSentimentClassification.py
- results/intfloat__multilingual-e5-small/KurdishSentimentClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/KurdishSentimentClassification.json
Recently collected Kurdish Sentiment from [paper](https://link.springer.com/article/10.1007/s10579-023-09716-6#citeas) and I believe it is the first Kurdish dataset.
- [] I have added points for my submission to the [POINTS.md](https://github.com/embeddings-benchmark/mteb/blob/main/docs/mmteb/points.md) file.
> Adding Kurdish Sentiment dataset

- mteb/tasks/Classification/__init__.py
- mteb/tasks/Classification/fas/PersianFoodSentimentClassification.py
- results/intfloat__multilingual-e5-small/PersianFoodSentimentClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/PersianFoodSentimentClassification.json
Persian Food Sentiment dataset from [paper](https://arxiv.org/abs/2005.12515) and I believe it is the first Persian dataset.
> Adding Persian Food Sentiment Dataset

- docs/mmteb/points/432.jsonl
- mteb/tasks/Classification/__init__.py
- mteb/tasks/Classification/fas/PersianFoodSentimentClassification.py
- results/intfloat__multilingual-e5-small/PersianFoodSentimentClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/PersianFoodSentimentClassification.json
temp branch for https://github.com/embeddings-benchmark/mteb/pull/432
> fix: Add Persian Food Sentiment Classification

- docs/mmteb/points/448.jsonl
Add points for #448. 
- 2 points in coordination (coordination contributions for mmteb by auto validating points)
> docs: coordination contributions for mmteb by auto validating points

- docs/mmteb/points/463.jsonl
- mteb/tasks/Classification/__init__.py
- mteb/tasks/Classification/bam/BambaraSentimentClassification.py
- results/intfloat__multilingual-e5-small/BambaraSentimentClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/BambaraSentimentClassification.json
Reason for dataset addition: Cover Bambara in Classification
> fix: Add Bambara Sentiment Classification

- docs/mmteb/points/470.jsonl
- mteb/tasks/Classification/__init__.py
- mteb/tasks/Classification/ell/GreekSentimentClassification.py
- results/intfloat__multilingual-e5-small/GreekSentimentClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/GreekSentimentClassification.json
> feat: Add Greek sentiment classification

- docs/mmteb/points/472.jsonl
- mteb/tasks/Classification/__init__.py
- mteb/tasks/Classification/fil/FilipinoHateSpeechClassification.py
- results/intfloat__multilingual-e5-small/FilipinoHateSpeechClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/FilipinoHateSpeechClassification.json
* First filipino classification dataset
* https://github.com/embeddings-benchmark/mteb/issues/367
> Add Filipino Classification Dataset

- docs/mmteb/points/470.jsonl
- docs/mmteb/points/474.jsonl
- mteb/tasks/Classification/__init__.py
- mteb/tasks/Classification/ssw/SiswatiNewsClassification.py
- results/intfloat__multilingual-e5-base/SiswatiNewsClassification.json
- results/intfloat__multilingual-e5-small/SiswatiNewsClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/SiswatiNewsClassification.json
Reason for dataset addition: Cover Siswati in Classification
> fix: Add Siswati News Classification

- docs/mmteb/points/460.jsonl
> ci: hotfix for points

- .github/pull_request_template.md
- docs/mmteb/points/513.jsonl
- mteb/abstasks/AbsTask.py
- mteb/tasks/Classification/ara/HotelReviewSentimentClassification.py
- mteb/tasks/Classification/ell/GreekLegalCodeClassification.py
- results/intfloat__multilingual-e5-small/HotelReviewSentimentClassification.json
Addresses https://github.com/embeddings-benchmark/mteb/issues/508
Also added a rerun as a comparison.
> Unify subsampling with stratify

- docs/mmteb/points/518.jsonl
- mteb/abstasks/AbsTask.py
- mteb/tasks/Classification/ara/HotelReviewSentimentClassification.py
Follow up on https://github.com/embeddings-benchmark/mteb/pull/513#issuecomment-2072012070
CC @imenelydiaker @KennethEnevoldsen
> fix: Stratify subsample fixes

- docs/mmteb/points/502.jsonl
- mteb/tasks/Classification/__init__.py
- mteb/tasks/Classification/nep/NepaliNewsClassification.py
- results/intfloat__multilingual-e5-small/NepaliNewsClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/NepaliNewsClassification.json
> Add Nepali news classification dataset

- README.md
- docs/adding_a_leaderboard_tab.md
Also see https://github.com/embeddings-benchmark/mteb/issues/321
> LB tab instructions

- docs/mmteb/points/499.jsonl
- mteb/tasks/Classification/__init__.py
- mteb/tasks/Classification/eng/FinancialPhrasebankClassification.py
- results/intfloat__multilingual-e5-small/FinancialPhrasebankClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/FinancialPhrasebankClassification.json
> Add Financial Phrasebank dataset

- docs/mmteb/points/551.jsonl
- mteb/tasks/BitextMining/__init__.py
- mteb/tasks/BitextMining/srn/SRNCorpusBitextMining.py
- results/intfloat__multilingual-e5-small/SRNCorpusBitextMining.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/SRNCorpusBitextMining.json
I have added the SRNCorpus test set, which covers the Surinam creole language Sranantongo and Dutch. @KennethEnevoldsen @imenelydiaker could one of you review?
> Add SRNCorpus

- docs/mmteb/points/557.jsonl
- mteb/tasks/Classification/__init__.py
- mteb/tasks/Classification/tel/TeluguAndhraJyotiNewsClassification.py
- results/intfloat/multilingual-e5-small/TeluguAndhraJyotiNewsClassification.json
- results/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/TeluguAndhraJyotiNewsClassification.json
> Telugu news classification

- docs/mmteb/points/558.jsonl
- mteb/tasks/Classification/multilingual/MultiHateClassification.py
Change MultiHateClassification to use dataset_transform istead of overloading load_dataset.
As discussed with @KennethEnevoldsen in https://github.com/embeddings-benchmark/mteb/pull/545
> Change MultiHateClassification to use dataset_transform

- docs/mmteb/points.md
Forgot to add to the last PR, not pressing
> Added names and affiliation to table

- docs/mmteb/points/655.jsonl
- mteb/tasks/Classification/eng/LegalBenchClassification.py
- results/intfloat__multilingual-e5-small/InternationalCitizenshipQuestionsLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/JCrewBlockerLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/LearnedHandsBenefitsLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/LearnedHandsBusinessLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/LearnedHandsConsumerLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/LearnedHandsCourtsLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/LearnedHandsCrimeLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/LearnedHandsDivorceLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/LearnedHandsDomesticViolenceLegalBenchClassification.json
- results/intfloat__multilingual-e5-small/LearnedHandsEducationLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/InternationalCitizenshipQuestionsLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/JCrewBlockerLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/LearnedHandsBenefitsLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/LearnedHandsBusinessLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/LearnedHandsConsumerLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/LearnedHandsCourtsLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/LearnedHandsCrimeLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/LearnedHandsDivorceLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/LearnedHandsDomesticViolenceLegalBenchClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/LearnedHandsEducationLegalBenchClassification.json
Reason for dataset addition: Showcases the model's performance on the [LegalBench](https://hazyresearch.stanford.edu/legalbench/) datasets, enabling evaluation on domain-specific legal texts.
Follow up to #648 
The following 10 datasets have been added in this PR:
1. [International Citizenship Questions](https://hazyresearch.stanford.edu/legalbench/tasks/international_citizenship_questions.html)
2. [JCrew Blocker](https://hazyresearch.stanford.edu/legalbench/tasks/jcrew_blocker.html)
3. [LearnedHands Benefits](https://hazyresearch.stanford.edu/legalbench/tasks/learned_hands_benefits.html)
4. [LearnedHands Business](https://hazyresearch.stanford.edu/legalbench/tasks/learned_hands_business.html)
5. [LearnedHands Consumer](https://hazyresearch.stanford.edu/legalbench/tasks/learned_hands_consu …
>  fix: Add LegalBench datasets - 9

- mteb/results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/model_meta.json
Seems like this dir is unnecessary no?
> Delete mteb/results directory

- README.md
> docs: remove prompt kwargs for example

- docs/mmteb/points.md
Hey, just adding some "contributor information" about myself
> Adding contributor information

- mteb/tasks/Classification/ron/RomanianReviewsSentiment.py
* Fix a double assignment in the RomanianReviewsSentiment class.
-----------------------
A fix for a small issue I found while browsing the code.
> fix: Double assignemnt in RomanianReviewsSentiment

- mteb/tasks/Classification/ron/RomanianReviewsSentiment.py
> fix: RomanianReviewsSentiment moved to new repo

- docs/mmteb/points/588.jsonl
- docs/mmteb/points/735.jsonl
- https://github.com/embeddings-benchmark/mteb/pull/735
- https://github.com/embeddings-benchmark/mteb/pull/588
> docs: add missing points

- docs/mmteb/points.md
Hey, my info is written twice for some reason, so removing the second occurrence
> docs: remove duplicate info

- docs/mmteb/points/789.jsonl
- mteb/evaluation/MTEB.py
Fix for bug of selecting a langugae in multilingual tasks.
Joint work with @isaac-chung 🚀
> fix: select language in multilingual tasks

- docs/mmteb/points/791.jsonl
- mteb/evaluation/MTEB.py
The wrong attribute was used here, just updating the attribute
> fix: update CO2 tracker attribute

- docs/mmteb/points/805.jsonl
- mteb/tasks/Retrieval/fra/FQuADRetrieval.py
- mteb/tasks/Retrieval/fra/SyntecRetrieval.py
Fixing some retrieval metrics for French tasks (raises an error with MAP)
> Fix French retieval metrics

- docs/mmteb/points/716.jsonl
* Fix the typo in points as per the discussion in https://github.com/embeddings-benchmark/mteb/pull/716#issuecomment-2130437694
> fix: Typo in points for #716

- mteb/tasks/Clustering/eng/ArxivClusteringP2PFast.py
- mteb/tasks/Clustering/eng/BigPatentClustering.py
- mteb/tasks/Clustering/eng/StackExchangeClustering.py
- mteb/tasks/Clustering/eng/StackExchangeClusteringP2P.py
- results/intfloat__multilingual-e5-small/BigPatentClusteringFast.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/BigPatentClusteringFast.json
> rename *fast to *v2 for clustering task

- README.md
- docs/mmteb/points/806.jsonl
- docs/mmteb/points/826.jsonl
- mteb/__init__.py
- mteb/abstasks/TaskMetadata.py
- mteb/cmd.py
- mteb/encoder_interface.py
- mteb/evaluation/MTEB.py
- mteb/languages.py
- mteb/overview.py
- pyproject.toml
- tests/test_cli.py
Updated CLI to use new task filter. Also removed a few flags which seems to not be used.
> Updated CLI to use new task filter

- mteb/tasks/Classification/ara/HotelReviewSentimentClassification.py
- mteb/tasks/Classification/eng/PoemSentimentClassification.py
- mteb/tasks/Classification/hin/HindiDiscourseClassification.py
- mteb/tasks/Clustering/multilingual/MLSUMClusteringP2P.py
- mteb/tasks/Clustering/multilingual/MLSUMClusteringS2S.py
- mteb/tasks/MultiLabelClassification/por/BrazilianToxicTweetsClassification.py
- mteb/tasks/Retrieval/multilingual/MLQARetrieval.py
> fix: Find missing dataset revisions

- .gitignore
- docs/mmteb/points.md
- docs/mmteb/points/854.jsonl
- docs/mmteb/points/XXX.jsonl
- mteb/abstasks/AbsTaskRetrieval.py
- mteb/evaluation/evaluators/RerankingEvaluator.py
- mteb/evaluation/evaluators/RetrievalEvaluator.py
- mteb/evaluation/evaluators/utils.py
- tests/test_RerankingEvaluator.py
- tests/test_RetrievalEvaluator.py
Hi @KennethEnevoldsen,
As discussed in PR [https://github.com/embeddings-benchmark/mteb/pull/841](https://github.com/embeddings-benchmark/mteb/pull/841), the most up-to-date version of our code is now here!
> Add abstention metrics to retrieval and reranking tasks

- mteb/tasks/Classification/ara/OnlineStoreReviewSentimentClassification.py
- results/intfloat__multilingual-e5-small/0a68dcd3dad5b4962a78daa930087728292b241d/OnlineStoreReviewSentimentClassification.json
- results/intfloat__multilingual-e5-small/model_meta.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/bf3bf13ab40c3157080a7ab344c831b9ad18b5eb/OnlineStoreReviewSentimentClassification.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/model_meta.json
- Updated the dataset that I used in OnlineStoreReviewSentimentClassification task .
- Uploaded the Updated data.
- Updated the reference to the new version in the task.
> Updated the revision of dataset

- docs/mmteb/points.md
Here is a PR to modify my affiliation. Changed "CentraleSupélec & Artefact" to "CentraleSupélec & Artefact Research Center", respectively my academic and company lab affiliations.
Sorry for the inconvenience!
> Affiliation modification

- mteb/models/gritlm.py
- mteb/tasks/Retrieval/__init__.py
https://github.com/embeddings-benchmark/mteb/issues/879
> Add GritLM

- docs/mmteb/points/911.jsonl
Hi @KennethEnevoldsen!
Just added the points for my bug fixes contribution :)
> Add points for #911

- mteb/models/__init__.py
> Fix GritLM Loading

- mteb/models/__init__.py
- scripts/mmteb/dataset_construction/wiki_clustering.md
Added minimal documentation for wikiclusterings
> docs: added documentation for wiki clustering

- docs/mmteb/points/917.jsonl
- mteb/tasks/STS/__init__.py
- mteb/tasks/STS/multilingual/SemRel24STS.py
- results/intfloat__multilingual-e5-small/0a68dcd3dad5b4962a78daa930087728292b241d/SemRel24STS.json
- results/sentence-transformers__paraphrase-multilingual-MiniLM-L12-v2/bf3bf13ab40c3157080a7ab344c831b9ad18b5eb/SemRel24STS.json
Also tested model `sentence-transformers/LaBSE` and validated that the results matched with the numbers given in [dataset paper Table 12](https://arxiv.org/pdf/2402.08638)
> Add STS dataset SemRel2024

- pyproject.toml
see https://github.com/huggingface/datasets/pull/6976 for more information
> fix: temporarily limit numpy version due to bug in datasets

- docs/mmteb/points/948.jsonl
@KennethEnevoldsen add point for PR #948
> Add point for PR 948

- mteb/tasks/Clustering/deu/BlurbsClusteringP2P.py
- mteb/tasks/Clustering/deu/BlurbsClusteringS2S.py
- mteb/tasks/Clustering/deu/TenKGnadClusteringP2P.py
- mteb/tasks/Clustering/deu/TenKGnadClusteringS2S.py
- mteb/tasks/Clustering/fra/AlloProfClusteringP2P.py
- mteb/tasks/Clustering/fra/AlloProfClusteringS2S.py
- mteb/tasks/Clustering/fra/HALClusteringS2S.py
- mteb/tasks/Clustering/jpn/LivedoorNewsClustering.py
- mteb/tasks/Clustering/jpn/MewsC16JaClustering.py
- mteb/tasks/Clustering/multilingual/MLSUMClusteringP2P.py
- mteb/tasks/Clustering/multilingual/MLSUMClusteringS2S.py
- mteb/tasks/Clustering/multilingual/SIB200ClusteringS2S.py
- mteb/tasks/Clustering/multilingual/WikiClusteringP2P.py
- mteb/tasks/Clustering/nob/SNLHierarchicalClustering.py
- mteb/tasks/Clustering/nob/VGHierarchicalClustering.py
- mteb/tasks/Clustering/pol/PolishClustering.py
- mteb/tasks/Clustering/rus/GeoreviewClusteringP2P.py
- mteb/tasks/Clustering/rus/RuSciBenchGRNTIClusteringP2P.py
- mteb/tasks/Clustering/rus/RuSciBenchOECDClusteringP2P.py
- mteb/tasks/Clustering/swe/SwednClustering.py
- mteb/tasks/Clustering/zho/CMTEBClustering.py
> Backward compatibility fixes for clustering

- README.md
- docs/adding_a_model.md
> docs: fix cli commands

- mteb/models/gritlm.py
Not sure this is the cleanest solution but GritLM init does not take arbitrary kwargs and fails if we pass device
> Fix GritLM kwarg

- docs/mmteb/points.md
- docs/mmteb/points/873.jsonl
- docs/mmteb/points/906.jsonl
https://github.com/embeddings-benchmark/mteb/discussions/595#discussioncomment-9815088
> add points

- mteb/cli.py
- mteb/evaluation/evaluators/RetrievalEvaluator.py
- mteb/models/e5_instruct.py
- mteb/models/gritlm.py
- mteb/models/instructions.py
Issue mentioned in https://github.com/embeddings-benchmark/mteb/pull/976
> Fix GritLM Retrieval instructions

- mteb/models/bge_models.py
- mteb/models/jina_models.py
Addresses part of https://github.com/embeddings-benchmark/arena/issues/6
> Add BGE large en v1.5

- mteb/models/__init__.py
- mteb/models/salesforce_models.py
Addresses part of https://github.com/embeddings-benchmark/arena/issues/6
> add SFR embed model

- mteb/models/llm2vec_models.py
- mteb/models/salesforce_models.py
> LLM2Vec multi-gpu bug fix

- .github/workflows/docs.yml
- docs/create_tasks_table.py
Fix current issue with CI where it fails due to df.sum(axis=0) being outdated. Replaced with recommended solution.
> ci: fix outdated CI for pandas

- .github/workflows/docs.yml
- docs/create_tasks_table.py
@isaac-chung just so you see that it is fixed.
> ci: fix docs ci again

- mteb/tasks/Classification/swa/SwahiliNewsClassification.py
- [ x] I have filled out the ModelMeta object to the extent possible
> minor update __init__ was not included make the repo not being able to be called as the module

- mteb/evaluation/evaluators/RerankingEvaluator.py
> fix: ensure reranking kwargs are properly passed

- mteb/models/llm2vec_models.py
- mteb/models/text_formatting_utils.py
> reuse corpus utils for LLM2Vec

- mteb/model_meta.py
> Fix Jina model loading

- docs/mmteb/points.md
> Update contributor table

- docs/adding_a_model.md
Fixes https://github.com/embeddings-benchmark/mteb/issues/1073
Should we also disable issues on results + leaderboard and refer issues to this repo?
> Change refresh description

- .github/workflows/docs.yml
> ci: allow docs ci to be run by contributors on PRs

- mteb/models/__init__.py
- mteb/models/google_models.py
> Add google API models

- mteb/tasks/Retrieval/dan/TwitterHjerneRetrieval.py
LIcense added: https://huggingface.co/datasets/sorenmulli/da-hashtag-twitterhjerne/discussions/2
> fix: Added misisng license

- mteb/models/voyage_models.py
Additonally also added voyage multilingual.
cc @AlexeyVatolin
> fix: Added fix for voyage models to handle too large batches

- mteb/tasks/Image/Clustering/__init__.py
- mteb/tasks/Image/Clustering/eng/CIFAR.py
- results-mieb/openai__clip-vit-base-patch32/3d74acf9a28c67741b2f4f2ea7635f0aaf6f0268/CIFAR100Clustering.json
- results-mieb/openai__clip-vit-base-patch32/3d74acf9a28c67741b2f4f2ea7635f0aaf6f0268/CIFAR10Clustering.json
> [MIEB] Add CIFAR clustering

- docs/adding_a_model.md
- mteb/cli.py
- tests/create_meta/existing_readme.md
- tests/create_meta/model_card_gold_existing.md
- tests/create_meta/model_card_gold_without_frontmatter.md
- tests/create_meta/model_card_without_frontmatter.md
- tests/test_cli.py
Merge new results with existing readme.
> Merge results with existing README.md

- mteb/load_results/load_results.py
- mteb/load_results/mteb_results.py
Required for loading results using `mteb.load_results`
Also needed to implement tests on mteb results repo to avoid future issues.
> feat: Added in functionality to allow loading outdated results

- mteb/tasks/Retrieval/__init__.py
> Missing import for SadeemQuestionRetrieval

- tests/test_load_results/test_mteb_results.py
These tests are no longer used since results moved to the results repo.
> fix: Remove unused tests

- mteb/models/google_models.py
- mteb/models/gte_models.py
- mteb/models/llm2vec_models.py
LLM2Vec model raises the following error when I executed JaGovFaqsRetrieval.
```
File "/path/to/experiments/mteb.py", line 106, in main                                                                              
evaluation.run(                                                                                                                                              
File "/path/to/mteb/evaluation/MTEB.py", line 422, in run                                             
raise e                                                                                                                                                      
File "/path/to/mteb/evaluation/MTEB.py", line 383, in run                                             
results, tick, tock = self._run_eval( …
```
> Fix: llm2vec for retrieval

- docs/mmteb/points.md
Hey, this just adds some contributor information about my coworker and myself
> Updating the contributor information

- pyproject.toml
- scripts/task_selection/task_selection_example.ipynb
> docs: format notebooks and upgrade ruff

- mteb/tasks/Retrieval/multilingual/MintakaRetrieval.py
Fix following error because MintakaRetrieval uses original load datasets.
```
File "/path/to/mteb/tasks/Retrieval/multilingual/MintakaRetrieval.py", line 166, in load_data                                                                                                                                          
self.corpus, self.queries, self.relevant_docs = _load_mintaka_data(                                                                                                                                                                                                                           
^^^^^^^^^^^^^^^^^^^ …
```
> fix: load_data in MintakaRetrieval

- mteb/abstasks/AbsTaskSummarization.py
- mteb/evaluation/evaluators/SummarizationEvaluator.py
- mteb/tasks/Summarization/eng/SummEvalSummarization.py
- mteb/tasks/Summarization/fra/SummEvalFrSummarization.py
- pyproject.toml
> fix: Ensure that summarization only calculates the metric across the statistic.

- mteb/models/arctic_models.py
- mteb/models/google_models.py
- scripts/run_mteb_english_cluster.py
> Add Arctic-m-v1.5 to embedding benchmark

- mteb/models/arctic_models.py
A merge of #1128 with merge fixe
> Merge pr 1128

- mteb/abstasks/AbsTaskClassification.py
- mteb/abstasks/AbsTaskClustering.py
- mteb/abstasks/AbsTaskClusteringFast.py
- mteb/abstasks/AbsTaskInstructionRetrieval.py
- mteb/abstasks/AbsTaskMultilabelClassification.py
- mteb/abstasks/AbsTaskPairClassification.py
- mteb/abstasks/AbsTaskRetrieval.py
- mteb/tasks/Retrieval/multilingual/BelebeleRetrieval.py
- tests/test_benchmark/mock_tasks.py
- tests/test_benchmark/task_grid.py
- tests/test_tasks/test_metadata.py
> add multilingual mocks and test descriptive_stats

- scripts/task_selection/task_selection_indic.ipynb
- scripts/task_selection/task_selection_mult.ipynb
> format main

- mteb/benchmarks.py
> add citation rumteb

- docs/mmteb/points/1179.jsonl
- mteb/cli.py
- mteb/create_meta.py
- mteb/load_results/mteb_results.py
- tests/create_meta/model_card_gold_without_frontmatter.md
- tests/test_benchmark/test_benchmark.py
- tests/test_cli.py
> refactor: create_meta

- docs/mmteb/create_points_table.py
Fix positional argument error introduced in [a previous PR](https://github.com/embeddings-benchmark/mteb/pull/1174).
> ci: remove positional argument

- docs/mmteb/points.md
> Update contributors table

- docs/mmteb/points.md
Updating authorship information as requested in https://github.com/embeddings-benchmark/mteb/commit/c160ace1d6f43775bf303f5d49be0055a535a05a
> docs: authorship-info for crystina-z

- docs/mmteb/points.md
* Add affiliation details of @mrshu to `docs/mteb/points.md`
> docs: Add affiliation of @mrshu

- mteb/tasks/Classification/eng/AmazonPolarityClassification.py
> Mismatch of the category of AmazonPolarityClassification

- docs/mmteb/points.md
Small update of my affiliation for the final version of the paper.
> Update of my affiliation

- docs/mmteb/points.md
Added @sarahooker (lmk if you want your email to be added too Sara)
> Add contributor

- docs/mmteb/points.md
* Use the diacritic character to be inline with Slovak spelling.
> fix: @mrshu's name in `points.md`

- docs/mmteb/points/1004.jsonl
- docs/mmteb/points/1006.jsonl
Added missing points primarily related to introduction and methods sections
I used the jsonl keys  (-> Paper writing), hopefully all is correct this time!
> Paper writing

- README.md
> docs: Fix a link in the README

- mteb/evaluation/evaluators/utils.py
Ensure that we can run using numpy<2.0.0
@Samoed do you have time to review this? Also would you be okay with being added as a collaborator to mteb?
> Allow numpy<2.0.0

- mteb/leaderboard/app.py
- mteb/load_results/task_results.py
I'm opening this PR so that you can track my progress in ironing out some of the UI problems in the Leaderboard.
> WIP: Leaderboard UI improvements

- mteb/tasks/MultiLabelClassification/por/BrazilianToxicTweetsClassification.py
> fix: upload BrazilianToxicTweetsClassification to hf

- mteb/leaderboard/app.py
- mteb/leaderboard/table.py
- mteb/load_results/benchmark_results.py
- mteb/models/overview.py
> Leaderboard updates: Model meta + task and benchmark info

- mteb/benchmarks/benchmarks.py
- mteb/evaluation/MTEB.py
- mteb/leaderboard/table.py
> Update logging verbosity levels in MTEB

- mteb/abstasks/AbsTaskRetrieval.py
- mteb/tasks/PairClassification/multilingual/XStance.py
- mteb/tasks/Retrieval/multilingual/MultiLongDocRetrieval.py
- mteb/tasks/Retrieval/multilingual/XMarketRetrieval.py
In some tasks, validation on the dataset failed due to the `trust_remote_code` parameter. Fixed this error
> Added the necessary trust_remote_code

- mteb/models/evaclip_models.py
> [mieb] Fix EVA CLIP for CV Bench

- mteb/models/vlm2vec_models.py
> [mieb] Add calculate probs for vlm2vec

- README.md
> docs: Fix a typo in README

- mteb/abstasks/AbsTaskClassification.py
- mteb/abstasks/AbsTaskMultilabelClassification.py
- mteb/tasks/Classification/ces/CSFDCZMovieReviewSentimentClassification.py
- mteb/tasks/Classification/ces/CzechProductReviewSentimentClassification.py
- mteb/tasks/Classification/ces/CzechSoMeSentimentClassification.py
- mteb/tasks/Classification/dan/AngryTweetsClassification.py
- mteb/tasks/Classification/dan/DKHateClassification.py
- mteb/tasks/Classification/dan/DanishPoliticalCommentsClassification.py
- mteb/tasks/Classification/dan/LccSentimentClassification.py
- mteb/tasks/Classification/eng/EmotionClassification.py
- mteb/tasks/Classification/eng/ToxicConversationsClassification.py
- mteb/tasks/Classification/eng/TweetSentimentExtractionClassification.py
- mteb/tasks/Classification/eng/YahooAnswersTopicsClassification.py
- mteb/tasks/Classification/eng/YelpReviewFullClassification.py
- mteb/tasks/Classification/est/estonian_valence.py
- mteb/tasks/Classification/multilingual/AfriSentiLangClassification.py
- mteb/tasks/Classification/multilingual/AmazonCounterfactualClassification.py
- mteb/tasks/Classification/multilingual/NordicLangClassification.py
- mteb/tasks/Classification/multilingual/ScalaClassification.py
- mteb/tasks/Classification/slk/CSFDSKMovieReviewSentimentClassification.py
- mteb/tasks/Classification/swe/DalajClassification.py
- mteb/tasks/Classification/zho/CMTEBClassification.py
- mteb/tasks/Classification/zho/YueOpenriceReviewClassification.py
fixes #1350 
- Make samples_per_label  a task attribute for Classification and Multilabel Classification
- Update all relevant tasks. Notice that `n_experiments` is 10 by default, so the duplicates are removed.
> fix: make samples_per_label a task attribute

- mteb/leaderboard/figures.py
Fixes some validation bugs with the leaderboard's main figure.
> Fix: Made data parsing in the leaderboard figure more robust

- mteb/abstasks/TaskMetadata.py
- mteb/tasks/Image/Any2AnyRetrieval/eng/WebQAT2TRetrieval.py
- scripts/run_mieb_missed_results.py
> [mieb] run script for missing results

- mteb/leaderboard/app.py
- mteb/leaderboard/table.py
- mteb/load_results/benchmark_results.py
- mteb/models/overview.py
Prepared leaderboard demo by fixing data loading on it.
> fix: Leaderboard demo data loading

- mteb/descriptive_stats/Classification/FilipinoHateSpeechClassification.json
- mteb/tasks/Classification/fil/FilipinoHateSpeechClassification.py
- tests/test_TaskMetadata.py
Remote files of repository were deleted and moved to another repository
Closes https://github.com/embeddings-benchmark/mteb/issues/1475
> fix: hatespeech filipino

- mteb/models/openai_models.py
- mteb/models/voyage_models.py
> fix: Ensure that models match the names on embedding-benchmarks/results

- mteb/abstasks/AbsTask.py
- mteb/evaluation/MTEB.py
- mteb/leaderboard/table.py
- mteb/overview.py
- tests/test_overview.py
- tests/test_tasks/test_all_abstasks.py
> fix: Correct typos superseeded -> superseded

- mteb/abstasks/Image/AbsTaskImageMultilabelClassification.py
- mteb/models/siglip_models.py
- scripts/run_mieb.py
This PR adds 
- https://huggingface.co/google/siglip-so400m-patch14-224
- https://huggingface.co/google/siglip-so400m-patch16-256-i18n (Multilingual),
> [MIEB] add missing siglip models 

- mteb/tasks/Image/Any2AnyRetrieval/eng/CIRRIT2IRetrieval.py
- mteb/tasks/Image/Any2AnyRetrieval/eng/Fashion200kI2TRetrieval.py
- mteb/tasks/Image/Any2AnyRetrieval/eng/FashionIQIT2IRetrieval.py
- mteb/tasks/Image/Any2AnyRetrieval/eng/Flickr30kI2TRetrieval.py
- mteb/tasks/Image/Any2AnyRetrieval/eng/Flickr30kT2IRetrieval.py
- mteb/tasks/Image/Any2AnyRetrieval/eng/MSCOCOI2TRetrieval.py
- mteb/tasks/Image/Any2AnyRetrieval/eng/MSCOCOT2IRetrieval.py
When reviewing the mieb tasks, I found that the statistical information of some datasets did not match the actual data that was loaded, so I corrected it to the accurate numbers.
> [mieb] Fix numbers of CIRR, Fashion200k, FashionIQ, Flickr30k, MSCOCO data statistics

- mteb/models/nomic_models.py
> fix: add nomic models

- mteb/models/sentence_transformers_models.py
> fix: Added all-minilm-l12-v2

- mteb/models/arctic_models.py
- mteb/models/overview.py
> fix: Added arctic models

- docs/create_tasks_table.py
- docs/tasks.md
- mteb/tasks/STS/eng/SickrSTS.py
The SICK-R metadata included inappropriate references, namely those for the Polish version of this dataset.
> Correction of SICK-R metadata

- mteb/evaluation/evaluators/RetrievalEvaluator.py
- mteb/models/bm25.py
> docs: Fix dependency library name for bm25s

- scripts/run_mieb_missed_results.py
re-run script for datasets that needed to be fixed (flickr, r-oxford, r-paris, blink's 4 settings). We are changing r-oxford and r-paris to use the MultiChoice evaluator instead of the retrieval evaluator to match its original setting in the paper, which will be merged later in #1572
> [mieb] update script for final re-run

- mteb/encoder_interface.py
An intermediate proposed interface for the image encoder designed based on VLM2VecWrapper.
The intention here is to define the current interface and adapt to as close to MTEB as possible and align as much as possible with sentencetransformers.
My goal is to make the interface compatible with the current Encoder interface (or close to). Thus removing the modality specific `get_image_embeddings`, but leave it to be determined by model.
This is to start a discussion, let me know what you think.
> Discussing a standard for ImageEncoders

- mteb/encoder_interface.py
- mteb/evaluation/evaluators/RetrievalEvaluator.py
- mteb/models/sentence_transformer_wrapper.py
- mteb/tasks/Image/Clustering/eng/CIFAR.py
- pyproject.toml
> fix image encoder

- mteb/model_meta.py
Discussed in #1614
Could imagine a few recursive problems
cc @dbuades
> fix: properly add mteb_model_meta to model object

- tests/test_cli.py
Fixes #1630
Current slowest tests
```
============================= slowest 5 durations ==============================
20.86s call     tests/test_cli.py::test_run_task[intfloat/multilingual-e5-small-BornholmBitextMining-fd1525a9fd15316a2d503bf26ab031a61d056e98]
15.86s call     tests/test_cli.py::test_save_predictions
14.51s call     tests/test_tasks/test_mteb_rerank.py::test_mteb_rerank
12.34s call     tests/test_benchmark/test_benchmark_integration_with_datasets.py::test_benchmark_sentence_transformer[model0-BrazilianToxicTweetsClassification]
12.32s call     tests/test_benchmark/test_benchmark_integration_with_datasets.py::test_benchmark_sentence_transformer[model0-task1]
========= 1577 passed, 258 skipped, 274 warnings in 279.78s (0:04:39) ==========
```
> Speed up test_save_predictions

- mteb/models/vista_models.py
1. Update the `VISTA` model loader to newer `FlagEmbeeding`.
2. Add inputs truncation to avoid runtime error of overlength examples (see https://github.com/embeddings-benchmark/mteb/pull/1612#issuecomment-2562753416).
> [MIEB] Fix VISTA model

- mteb/models/openai_models.py
> fix: Use batch size kwargs for openai APIs

- mteb/models/misc_models.py
> fix: Pass trust_remote_code=True to CPM model

- mteb/models/misc_models.py
Closes https://github.com/embeddings-benchmark/mteb/issues/1688
> fix: arg name for openbmb/MiniCPM-Embedding

- mteb/tasks/Retrieval/deu/GermanDPRRetrieval.py
Closes https://github.com/embeddings-benchmark/mteb/issues/1700
> fix: GermanDPR

- .github/workflows/leaderboard_refresh.yaml
This calls to refresh the leaderboard with a factory rebuild daily. 
If the space name changes, we will need to change this and the HF_TOKEN secret in the space (I created a new one with only permissions for the leaderboard repos just in case).
> Refresh the v2 leaderboard daily

- mteb/models/e5_v.py
Fixes #1647
update e5-v transformers version comparison
> fix: change comparison to bigger than

- mteb/tasks/Classification/multilingual/AfriSentiLangClassification.py
- tests/test_tasks/test_all_abstasks.py
Hot fix until we find a way forward. #1777.
This is to fix the broken main build. 
CC @KennethEnevoldsen @Samoed
> ci: skip AfriSentiLID for now

- mteb/benchmarks/benchmarks.py
Follow up on https://github.com/embeddings-benchmark/mteb/pull/1790
@KennethEnevoldsen FYI
> docs: Add contact to MMTEB benchmarks

- mteb/benchmarks/benchmarks.py
> fix: Add additional contacts

- .github/workflows/model_loading.yml
- Makefile
- mteb/abstasks/AbsTask.py
- mteb/abstasks/MultilingualTask.py
- mteb/benchmarks/benchmarks.py
- mteb/languages.py
- mteb/leaderboard/app.py
- mteb/load_results/load_results.py
- mteb/load_results/task_results.py
- mteb/models/bge_models.py
- mteb/models/gritlm_models.py
- mteb/models/misc_models.py
- mteb/models/openai_models.py
- mteb/models/ru_sentence_models.py
- mteb/overview.py
- pyproject.toml
- scripts/compare_leaderboard_results.py
- scripts/extract_model_names.py
- tests/test_tasks/test_all_abstasks.py
Added more annotations on top of the existing
I believe this 
fixes #1556
(at lest for now)
> fix: add even more training dataset annotations

- mteb/abstasks/AbsTask.py
- mteb/overview.py
- scripts/data/create_task_table.py
Ref https://github.com/embeddings-benchmark/mteb/issues/1791
> [v2] remove metadata_dict

- mteb/models/stella_models.py
The last missing Chinese models.
> fix: Added Chinese Stella models

- mteb/leaderboard/app.py
- mteb/leaderboard/table.py
Fixed issues with table not updating when searched, and also when no results are found.
Additionally, now the callback only gets called once you press enter, instead of with every change.
> fix: Fixed leaderboard search bar

- mteb/models/lens_models.py
As per this discussion on their HF repo: https://huggingface.co/yibinlei/LENS-d4000/discussions/1
> fix: Added correct training data annotation to LENS

- mteb/models/align_models.py
Add model meta for models in align_models.py
> [mieb] Fill in align model meta

- .github/pull_request_template.md
Hello,
I’d like to propose an update to the PR template to improve the stability of MTEB. The goal is to ensure that all PRs include appropriate tests and updated documentation where needed.
To kick things off, I’ve added some initial ideas and suggestions for these improvements. Please let me know your thoughts and if there’s anything you’d like to adjust or add.
Here’s the link to the discussion I started: https://github.com/embeddings-benchmark/mteb/issues/1831
@isaac-chung @KennethEnevoldsen @Samoed
> doc: update pr template

- mteb/models/e5_v.py
- mteb/models/evaclip_models.py
Fill in e5v and eva clip model meta
> [mieb] Fill in e5v and eva clip model meta

- mteb/models/jasper_models.py
- mteb/models/stella_models.py
> update stella/jasper metainfo

- mteb/abstasks/TaskMetadata.py
- mteb/tasks/SummaryRetrieval/fas/FaMTEBSummaryRetrieval.py
> fix: remove SummaryRetrieval as a type

- mteb/tasks/SummaryRetrieval/fas/FaMTEBSummaryRetrieval.py
Follow up for https://github.com/embeddings-benchmark/mteb/pull/1915 and https://github.com/embeddings-benchmark/mteb/pull/1843
- opted to use the old names but add to description
- this way we don't need changes to `benchmarks.py`
> revert rename and add to description

- docs/create_tasks_table.py
Tests currently go into an infinite loop. This should prevent that.
> docs: Add sort to domains for task metadata

- mteb/benchmarks/benchmarks.py
> docs: Updated citation for mteb(scandinavian)

- mteb/benchmarks/benchmarks.py
- mteb/leaderboard/app.py
@sivareddyg asked for this one; Hope it is okay for everybody! Lmk if any concerns!
> Leaderboard: Acks

- mteb/abstasks/AbsTask.py
- mteb/evaluation/MTEB.py
Closes https://github.com/embeddings-benchmark/mteb/issues/1770
> [v2] remove `save_suffix`

- mteb/models/bge_models.py
ref https://github.com/embeddings-benchmark/mteb/issues/1912
> misc: add bgev1 models

- mteb/benchmarks/benchmarks.py
> feat: add beir

- mteb/load_results/benchmark_results.py
@KennethEnevoldsen reviewed in person
> Fixed join_revisions if results are empty

- README.md
@x-tabdeveloping should we rename it from demo to app?
fixes #1923
> docs: Add instruction for running leaderboard

- mteb/abstasks/AbsTask.py
- mteb/abstasks/AbsTaskClassification.py
- mteb/abstasks/AbsTaskInstructionRetrieval.py
- mteb/abstasks/AbsTaskMultilabelClassification.py
- mteb/abstasks/AbsTaskReranking.py
- mteb/abstasks/AbsTaskRetrieval.py
- mteb/abstasks/MultiSubsetLoader.py
- mteb/abstasks/MultilingualTask.py
- mteb/cli.py
- mteb/evaluation/MTEB.py
- mteb/evaluation/evaluators/ClassificationEvaluator.py
Closes https://github.com/embeddings-benchmark/mteb/issues/1941
> misc: add warnings

- mteb/leaderboard/app.py
@Muennighoff this hopefully fixes some of our issues with the slider.
I will say though, that this solution is suboptimal, and I would still keep the issue open.
> fix: Changed callback for slider, accounted for None input

- mteb/benchmarks/benchmarks.py
- mteb/leaderboard/app.py
> fix: leaderboard and benchmark.py inconstiencies 

- mteb/models/ru_sentence_models.py
Adds FRIDA model meta and some missing prompts for RoSBERTa model
> Add FRIDA model meta

- README.md
README currently now showing the caching tab:
Caching tab reappears.
> docs: Fix README code rendering

- mteb/models/voyage_models.py
> fix: add Voyage-code-3

- mteb/tasks/Image/ZeroshotClassification/eng/Birdsnap.py
- mteb/tasks/Image/ZeroshotClassification/eng/Caltech101.py
- mteb/tasks/Image/ZeroshotClassification/eng/Country211.py
- mteb/tasks/Image/ZeroshotClassification/eng/DTD.py
- mteb/tasks/Image/ZeroshotClassification/eng/EuroSAT.py
- mteb/tasks/Image/ZeroshotClassification/eng/FER2013.py
- mteb/tasks/Image/ZeroshotClassification/eng/FGVCAircraft.py
- mteb/tasks/Image/ZeroshotClassification/eng/Food101.py
- mteb/tasks/Image/ZeroshotClassification/eng/GTSRB.py
- mteb/tasks/Image/ZeroshotClassification/eng/Imagenet1k.py
- mteb/tasks/Image/ZeroshotClassification/eng/MNIST.py
- mteb/tasks/Image/ZeroshotClassification/eng/OxfordPets.py
- mteb/tasks/Image/ZeroshotClassification/eng/PatchCamelyon.py
- mteb/tasks/Image/ZeroshotClassification/eng/RESISC45.py
- mteb/tasks/Image/ZeroshotClassification/eng/STL10.py
- mteb/tasks/Image/ZeroshotClassification/eng/SUN397.py
- mteb/tasks/Image/ZeroshotClassification/eng/StanfordCars.py
- mteb/tasks/Image/ZeroshotClassification/eng/UCF101.py
Closes https://github.com/embeddings-benchmark/mteb/issues/1974
> [MIEB] Rename classes with duplicated names

- Makefile
- pyproject.toml
- tests/test_benchmark/test_benchmark.py
- tests/test_tasks/test_all_abstasks.py
#2012: Rerun test cases that frequently fail in the pipeline. After 3 unsuccessful reruns, the test cases will fail.
Closes: https://github.com/embeddings-benchmark/mteb/issues/2012
cc: @KennethEnevoldsen @Samoed @isaac-chung
> ci: Rerun tests that fail due to networking issues.

- Makefile
- mteb/models/voyage_models.py
> fix: Ensure voyage model uses different naming scheme

- mteb/benchmarks/benchmarks.py
> fix: Missing fixes for #2086

- mteb/overview.py
Fixes #1767 
- Add warning in main about v2 change https://github.com/embeddings-benchmark/mteb/pull/2107
> misc: add warning about task category conversion

- mteb/abstasks/stratification.py
> docs: Follow google docstring format

- mteb/models/nvidia_models.py
- mteb/models/salesforce_models.py
Closes https://github.com/embeddings-benchmark/mteb/issues/2124
> fix InstructSentenceTransformer Model name

- mteb/models/voyage_models.py
Closes https://github.com/embeddings-benchmark/mteb/issues/2123
> fix voyage

- mteb/models/nvidia_models.py
Added a few missing annotations for nvidia-embed
> fix: Update NVIDIA-Embed training data

- mteb/models/gte_models.py
Closes https://github.com/embeddings-benchmark/mteb/issues/2142
> Fix tokens num in gte models

- mteb/abstasks/Image/AbsTaskAny2AnyRetrieval.py
- mteb/descriptive_stats/Image/Any2AnyRetrieval/FashionIQIT2IRetrieval.json
- add Any2AnyRetrievalDescriptiveStatistics
- run on FashionIQIT2IRetrieval as an example
> misc: add Any2AnyRetrievalDescriptiveStatistics

- mteb/models/linq_models.py
- mteb/models/misc_models.py
> fix: Incorrect annotations for Mistral-based embedding models

- mteb/models/ru_sentence_models.py
> update ru models annotation

- mteb/leaderboard/app.py
This PR is related to issue #2103 for Alphabetical ordering of tasks in dropdown list 
The dropdown list of tasks now has alphabetical ordering. Other dropdown list already follows alphabetical ordering.
> Alphabetical ordering of tasks in dropdowns

- README.md
> use 'mteb.MTEB' instead of 'MTEB' for custom model

- mteb/models/e5_instruct.py
- mteb/models/e5_models.py
> add base models for e5

- mteb/models/sentence_transformers_models.py
They don't have much information in paper, so I don't know what to add
> add labse annotation

- mteb/tasks/MultiLabelClassification/multilingual/MultiEURLEXMultilabelClassification.py
- tests/test_tasks/test_all_abstasks.py
Related to discussion on EURLEX so just added a bit of extra info.
> docs: Update description of EURLex

- docs/adding_a_model.md
> Fix `calculate_memory_usage_mb` in adding_a_model.md

- mteb/models/voyage_models.py
Update voyage name to include Org.
Otherwise the tests fails in the results repo
> fix: Update voyage name to include Org.

- mteb/models/ru_sentence_models.py
> Add ModelMeta rubert-mini-frida, BERTA

- mteb/abstasks/TaskMetadata.py
- mteb/tasks/Audio/AudioClassification/__init__.py
- mteb/tasks/Audio/AudioClassification/eng/LibriCount.py
Solves #2239 
------------------------------------------------------------
> Adding Libricount dataset

- mteb/abstasks/TaskMetadata.py
- mteb/tasks/Audio/AudioClassification/__init__.py
- mteb/tasks/Audio/AudioClassification/eng/FSDD.py
Solves #2370 
-------------------------------------------------------------------------------
> Adding FSDD dataset (Free Spoken Digit Dataset)

- mteb/models/b1ade_models.py
- mteb/models/overview.py
> fix: b1ade

- pyproject.toml
fixes #2376
related issue: https://github.com/gradio-app/gradio/issues/10817
> fix: pin gradio dependency to ensure leaderboards works

- mteb/abstasks/TaskMetadata.py
- mteb/tasks/Audio/AudioClassification/__init__.py
- mteb/tasks/Audio/AudioClassification/eng/SpokenQAforIC.py
- mteb/tasks/Audio/AudioClassification/eng/VoxCelebSA.py
- mteb/tasks/Audio/Clustering/__init__.py
- mteb/tasks/Audio/Clustering/eng/VehicleSoundClustering.py
- [✅] **Code Formatted**: Format the code using `make lint` to maintain consistent style.
- [✅] **Updated Documentation**: Add or update documentation to reflect the changes introduced in this PR.
- [❌] **New Tests Added**: Write tests to cover new functionality. Validate with `make test-with-coverage`.
- [✅] **Tests Passed**: Run tests locally using `make test` or `make test-with-coverage` to ensure no existing functionality is broken.
- [✅] I have run the following models on the task (adding the results to the pr). These can be run using the `mteb -m {model_name} -t {task_name}` command.
- [✅] I have checked that the performance is neither trivial (both models gain close to perfect scores) nor random (both models gain close to random scores).
- [✅] …
> Add VoxCelebSA, SpokenQAforIC, VehicleSoundClustering from Dynamic-SUPERB

- mteb/models/b1ade_models.py
The Bl1de name was added without a prefix and, as a result, was not presented on the leaderboard. I also want to add a validator to it, but I will do so in a separate PR.
Ref https://github.com/embeddings-benchmark/results/pull/154#issuecomment-2741286339
> fix b1ade name

- Makefile
- docs/usage/usage.md
- mteb/evaluation/evaluators/Image/Any2AnyMultiChoiceEvaluator.py
- mteb/evaluation/evaluators/Image/Any2AnyRetrievalEvaluator.py
- mteb/evaluation/evaluators/Image/Any2TextMultipleChoiceEvaluator.py
- mteb/evaluation/evaluators/Image/ClassificationEvaluator.py
- mteb/evaluation/evaluators/Image/ImageTextPairClassificationEvaluator.py
- mteb/evaluation/evaluators/Image/VisualSTSEvaluator.py
- mteb/evaluation/evaluators/Image/ZeroShotClassificationEvaluator.py
- mteb/model_meta.py
- mteb/models/cohere_v.py
- mteb/models/evaclip_models.py
- mteb/models/jina_clip.py
- mteb/models/llm2clip_models.py
- mteb/models/moco_models.py
- mteb/models/openclip_models.py
- mteb/models/vista_models.py
- mteb/models/vlm2vec_models.py
- mteb/models/voyage_v.py
- mteb/requires_package.py
- pyproject.toml
> fix: make torchvision optional

- pyproject.toml
> Min torchvision>0.2.1

- pyproject.toml
> Update speed dependencies with new setuptools release

- mteb/tasks/Retrieval/multilingual/MIRACLRetrieval.py
> Error while evaluating MIRACLRetrievalHardNegatives: 'trust_remote_code'

- .github/workflows/test.yml
Add caching for `~/.cache/huggingface` to improve ci reliability and performance.
> ci: cache `~/.cache/huggingface`

- .github/workflows/dataset_loading.yml
https://github.com/embeddings-benchmark/mteb/pull/2201#discussion_r2025363086
> ci: Run dataset loading only when pushing to main

- docs/tasks.md
Quick fix in tasks.md file as Fix Task Count Per Language Table was not seeing correctly in table format.
> fix table in tasks.md

- mteb/abstasks/Audio/AbsTaskAudioPairClassification.py
- mteb/abstasks/TaskMetadata.py
- mteb/abstasks/__init__.py
- mteb/evaluation/evaluators/Audio/AudioPairClassificationEvaluator.py
- mteb/evaluation/evaluators/__init__.py
> Create AbsTask and Evaluator for audio pair classification task

- mteb/tasks/Image/Any2AnyRetrieval/eng/BLINKIT2IRetrieval.py
- mteb/tasks/Image/Any2AnyRetrieval/eng/BLINKIT2TRetrieval.py
- mteb/tasks/Image/Any2AnyRetrieval/eng/ImageCoDeT2IRetrieval.py
Ref https://github.com/embeddings-benchmark/results/pull/122#issuecomment-2676288974
> [MIEB] align main metrics with leaderboard

- mteb/models/overview.py
- mteb/models/wavlm_models.py
Addressing Issue: #2218
- microsoft/wavlm-large
- microsoft/wavlm-base-plus-sd
- microsoft/wavlm-base-plus-sv
- microsoft/wavlm-base-sd
- microsoft/wavlm-base-sv
- microsoft/wavlm-base-plus
- microsoft/wavlm-base
```python
import mteb
model_name = "microsoft/wavlm-base"
model = mteb.get_model(
model_name, model_revision="efa81aae7ff777e464159e0f877d54eac5b84f81"
)
tasks = mteb.get_tasks(tasks=["VoiceGenderClustering"])
evaluation = mteb.MTEB(tasks=tasks)
results = evaluation.run(model, output_folder=f"results/{model_name}")
```
> added wavlm models

- mteb/models/sentence_transformers_models.py
> typo in model name

- mteb/tasks/Audio/AudioClassification/__init__.py
- mteb/tasks/Audio/AudioClassification/eng/SIBFLEURS.py
- mteb/tasks/Audio/Clustering/eng/MusicGenre.py
- [✅] **Code Formatted**: Format the code using `make lint` to maintain consistent style.
- [✅] **Updated Documentation**: Add or update documentation to reflect the changes introduced in this PR.
- [❌] **New Tests Added**: Write tests to cover new functionality. Validate with `make test-with-coverage`.
- [✅] **Tests Passed**: Run tests locally using `make test` or `make test-with-coverage` to ensure no existing functionality is broken.
- [✅] I have run the following models on the task (adding the results to the pr). These can be run using the `mteb -m {model_name} -t {task_name}` command.
- [✅] I have checked that the performance is neither trivial (both models gain close to perfect scores) nor random (both models gain close to random scores).
- [✅] …
> Adding SIB-FLEURS

- mteb/tasks/Image/Any2AnyRetrieval/eng/MemotionI2TRetrieval.py
- mteb/tasks/Image/Any2AnyRetrieval/eng/MemotionT2IRetrieval.py
fix #2512.
Memotion's original implementation was correct but a bit confusing.
> [mieb] Memotion preprocessing code made more robust and readable

- docs/usage/usage.md
- pyproject.toml
Closes https://github.com/embeddings-benchmark/mteb/issues/2523
> Fix leaderboard version

- mteb/tasks/Image/Any2AnyRetrieval/eng/HatefulMemesI2TRetrieval.py
- mteb/tasks/Image/Any2AnyRetrieval/eng/HatefulMemesT2IRetrieval.py
deduplicate both tasks for HatefulMemes. Fix #2510.
> [mieb] fix hatefulmemes

- mteb/models/conan_models.py
- mteb/models/overview.py
We have added the model implementation and other information. Thanks.
> Model conan

- mteb/benchmarks/benchmarks.py
Add MIEB citation: https://arxiv.org/abs/2504.10471
> docs: Add MIEB citation in benchmarks

- docs/usage/usage.md
- mteb/models/cache_wrapper.py
- mteb/models/ops_moa_models.py
- tests/test_embedding_caching.py
> fix: CacheWrapper per task

- README.md
> Docs: Add MIEB to README

- mteb/models/e5_models.py
> fix: me5 trainind data config to include xquad dataset

- mteb/leaderboard/benchmark_selector.py
> Fix leaderboard entry for BuiltBench

- mteb/models/ru_sentence_models.py
> fix frida datasets

- mteb/models/rerankers_custom.py
ref https://github.com/embeddings-benchmark/mteb/issues/2584#issuecomment-2833510209
Currently it's checked if `flaggembedding` library is installed, but should `FlagEmbeddings`
> fix FlagEmbedding package name

- pyproject.toml
Recently it was updated to `v3` version and not working on macos. Ref https://github.com/embeddings-benchmark/mteb/issues/1766
> fix codecarbon version

- pyproject.toml
Closes https://github.com/embeddings-benchmark/mteb/issues/2557
@x-tabdeveloping 
Gradio `5.25.2`
https://github.com/user-attachments/assets/afc2e202-ab54-45c3-83be-7f395b4ff26e
Gradio `5.17.1`
https://github.com/user-attachments/assets/f174e92c-ac22-45a6-b489-29d4d3517bc9
> Update gradio version

- mteb/custom_validators.py
- mteb/tasks/Classification/__init__.py
- mteb/tasks/Classification/multilingual/ScandiSentClassification.py
- scripts/data/scandisent/create_data.py
- From https://github.com/timpal0l/ScandiSent. Dataset added to MTEB org.
- Results: https://github.com/embeddings-benchmark/results/pull/189
Results
| Model | Main Score |
|----------|----------|
| multilingual-e5-base | 0.93904 |
| multilingual-e5-small | 0.90456 |
| paraphrase-multilingual-MiniLM-L12-v2 | 0.8968 |
> Add ScandiSent dataset

- mteb/abstasks/AbsTask.py
- mteb/abstasks/TaskMetadata.py
Closes https://github.com/embeddings-benchmark/mteb/issues/2623
Now it's possible to update an existing dataset's card without re-uploading it. Before that, I missed that this is possible to load `DatasetCardData` directly
```python
import mteb
task = mteb.get_task("SciDocsRR")
task.metadata.push_dataset_card_to_hub("mteb/SciDocsRR123")
```
E.g. https://huggingface.co/datasets/mteb/SciDocsRR
> [v2] Merge dateset's readme with existing

- mteb/tasks/Classification/multilingual/ScandiSentClassification.py
> fix citations

- mteb/tasks/BitextMining/__init__.py
- mteb/tasks/BitextMining/multilingual/DanishMedicinesAgencyBitextMining.py
- mteb/tasks/Classification/multilingual/ScandiSentClassification.py
- mteb/tasks/PairClassification/dan/TalemaaderPC.py
> add Bilingual English-Danish parallel corpus from The Danish Medicines Agency

- .github/workflows/docs.yml
This reverts commit 82dcb3dd03da0294d8a72ddca7a951680f33d67d.
> Revert "CI: fix infinitely committing issue (#2616)"

- mteb/abstasks/TaskMetadata.py
- mteb/tasks/Summarization/eng/SummEvalSummarization.py
Closes https://github.com/embeddings-benchmark/mteb/issues/1892
> [v2] Add readme to all datasets

- mteb/abstasks/TaskMetadata.py
Closes https://github.com/embeddings-benchmark/mteb/issues/2624
I've added `task_ids` mapping to dataset card, and I'm removing `hf_subset_descriptive_stats` for datasets with more than 10 splits to avoid problems with pushing (now readme for Flores is uploaded https://huggingface.co/datasets/mteb/flores). After that I will update all readme again
@KennethEnevoldsen @isaac-chung 
> [v2] Fix task subtypes

- mteb/tasks/aggregated_tasks/STS17MultilingualVisualSTS.py
- mteb/tasks/aggregated_tasks/STSBenchmarkMultilingualVisualSTS.py
> fix: Update VisualSTS Aggregate task modalities

- mteb/tasks/Classification/multilingual/SIB200Classification.py
- mteb/tasks/Clustering/multilingual/SIB200ClusteringS2S.py
As correctly pointed out in:
https://huggingface.co/datasets/mteb/sib200/discussions/1
> fix: SIB200 machine translated > human translated

- mteb/leaderboard/app.py
- mteb/leaderboard/benchmark_selector.py
- mteb/leaderboard/text_segments.py
Did a few things to improve the simplify the leaderboard UI.
Changes:
- Combined FAQ entries
- Created dropdowns in the select benchmark menu sidebar
- Removed reference to arena
- Removed reference to old leaderboard
- reduced size of the select menu
- reduced the size of acknowledgements
- removed farsi from the selection (as it is a beta)
bugfixes:
- Fixed the bug that happens due to language selection: #2556. 
- Turns out that it happened due to the size of the list. Reducing it to "only" the language in MTEB resolved the issue.
refactors:
- Refactored to use a class for menu items
- refactored text segments out of app.py
<details>
<summary> Images </summary>
Overview
FAQ Unfolded:
FAQ Folded (default) + Ack. 
</details>
> Leaderboard: UI simplifications for menus

- mteb/models/openai_models.py
- mteb/tasks/Image/ZeroShotClassification/eng/templates/PatchCamelyon_labels.txt
Fix #2699 
I have checked with `WebFAQRetrieval` and `VieQuADRetrieval` tasks, and its working correctly. We don't have results of these models present anywhere to verify.
> Fix for Openai_Text-Embedding3-Small

- docs/usage/usage.md
> docs: fix number of tasks for eng, v2 in docs

- mteb/models/ast_model.py
- mteb/models/overview.py
https://arxiv.org/abs/2104.01778
Tested on the BeijingOpera Dataset:
```python
{
"dataset_revision": "c5e967a1ae3569cf7f1dd2bb9273fd9424032e4a",
"task_name": "BeijingOpera",
"mteb_version": "1.34.7",
"scores": {
"train": [
{
"accuracy": 0.966046,
"f1": 0.967896,
"f1_weighted": 0.965991,
"scores_per_experiment": [
{
"accuracy": 0.979167,
"f1": 0.982759,
"f1_weighted": 0.979167
},
{
"accuracy": 1.0,
"f1": 1.0,
"f1_weighted": 1.0
},
{
"accuracy": 0.93617,
"f1": 0.945806,
"f1_weighted": 0.936911
},
{
"accuracy": 0.957447,
"f1": 0.952583,
"f1_weighted": 0.957613
},
{
"accuracy": 0.957447,
"f1": 0.958333,
"f1_weighted": 0.956265
}
],
"main_score": 0.966046,
"hf_subset": "default",
"languages": [
"eng-Latn"
]
}
]
},
"evaluation_time": 68.9672200679779,
"kg_co2_emissions": null
}
```
> Added AST Model

- mteb/tasks/Retrieval/eng/ClimateFEVERRetrieval.py
Update the description to state that the corpus is the same as fever as we have have [multiple questions on it](https://huggingface.co/datasets/mteb/climate-fever/discussions/2)
> docs: Updated description of FEVER

- mteb/tasks/Classification/pol/PolishClassification.py
- mteb/tasks/Clustering/eng/BigPatentClustering.py
- tests/test_TaskMetadata.py
> Backfill task metadata for metadata for BigPatentClustering and AllegroReviews

- mteb/models/seed_models.py
We disclose the training data of Seed1.5-Embedding. Please have a look (I think there is no need to create a new revision, otherwise the results need to be copied again). Thank you!
> Update Seed1.5 training data

- mteb/models/mctct_model.py
- mteb/models/overview.py
Significance: Supervised ASR objective;, supposedly it should learn “phoneme-level” distinctions well.
Tested on BiejingOpera Dataset:
**Model: "speechbrain/m-ctc-t-large"**
```python
{
"dataset_revision": "c5e967a1ae3569cf7f1dd2bb9273fd9424032e4a",
"task_name": "BeijingOpera",
"mteb_version": "1.34.7",
"scores": {
"train": [
{
"accuracy": 0.669504,
"f1": 0.667977,
"f1_weighted": 0.666512,
"scores_per_experiment": [
{
"accuracy": 0.666667,
"f1": 0.667234,
"f1_weighted": 0.663702
},
{
"accuracy": 0.702128,
"f1": 0.70671,
"f1_weighted": 0.702865
},
{
"accuracy": 0.638298,
"f1": 0.627976,
"f1_weighted": 0.646657
},
{
"accuracy": 0.680851,
"f1": 0.682359,
"f1_weighted": 0.677898
},
{
"accuracy": 0.659574,
"f1": 0.655605,
"f1_weighted": 0.641438
}
],
"main_score": 0.669504,
"hf_subset": …
```
> MAEB: M-CTC-T Model

- mteb/tasks/Image/ImageClassification/eng/Caltech101Classification.py
- mteb/tasks/Image/ZeroShotClassification/eng/Caltech101.py
fixes: #2770
Fixes the issue, but only in v1
```
task: mteb.AbsTask = mteb.get_task("Caltech101ZeroShot")
task.load_data()
task.get_candidate_labels()
```
> fix: Update Caltech101 datasets to latest revision [v1]

- mteb/abstasks/dataset_card_template.md
Close https://github.com/embeddings-benchmark/mteb/issues/2719
> fix dataset readme

- pyproject.toml
Fix https://github.com/embeddings-benchmark/mteb/issues/2796
> fix pyproject

- mteb/tasks/Audio/AudioMultilabelClassification/__init__.py
- mteb/tasks/Audio/AudioMultilabelClassification/eng/BirdSet.py
I have explained why this task fills an existing gap in the MTEB benchmark.
I have verified that the dataset runs end-to-end with the `mteb` package:
```python
import mteb
from sentence_transformers import SentenceTransformer
model_name = "facebook/wav2vec2-base"
model = mteb.get_model(model_name) # if the model is not implemented in MTEB it will be eq. to SentenceTransformer(model_name)
tasks = mteb.get_tasks(tasks=["BirdSet"])
evaluation = mteb.MTEB(tasks=tasks)
results = evaluation.run(model, output_folder=f"results/{model_name}")
```
I have evaluated two standard audio models and recorded the scores:
```bash
mteb run -m facebook/wav2vec2-base -t BirdSet
mteb run -m microsoft/wavlm-base -t BirdSet
```
I confirmed that the scores are neither trivial (near-perfect) nor random.
The …
> Adding BirdSet Bioacoustics dataset

- .github/ISSUE_TEMPLATE/new_dataset.yaml
- .github/ISSUE_TEMPLATE/new_model.yaml
> add description to issue template

- mteb/evaluation/evaluators/model_classes.py
Previously this wasn't possible to load dataset with query as dialog (e.g. `StatcanDialogueDatasetRetrieval`)
> [v2] fix dialog task loading

- mteb/abstasks/AbsTaskAnyClassification.py
Close https://github.com/embeddings-benchmark/mteb/issues/2780
| Task | main | PR |
| - | - | - |
| LccSentimentClassification | 0.367333 | 0.367333 |
| ImdbClassification | 0.703564 | 0.703564 | 
| Banking77Classification | 0.651721 | 0.651721 |
> [v2] Fix classification task random state generation

- docs/adding_a_dataset.md
Ref https://github.com/embeddings-benchmark/results/pull/240#discussion_r2218387162
> Use `mteb.get_model` in adding_a_dataset.md

- mteb/models/opensearch_neural_sparse_models.py
> fix: specify revision for opensearch

- mteb/models/opensearch_neural_sparse_models.py
> fix: Only import SparseEncoder once sentence-transformer version have been checked

- mteb/abstasks/AbsTaskRetrieval.py
> fix instruction fields

- mteb/abstasks/AbsTaskReranking.py
- mteb/descriptive_stats/Reranking/JQaRAReranking.json
- mteb/descriptive_stats/Reranking/JaCWIRReranking.json
- mteb/descriptive_stats/Reranking/XGlueWPRReranking.json
- mteb/tasks/Reranking/jpn/JQaRAReranking.py
- mteb/tasks/Reranking/jpn/JaCWIRReranking.py
- mteb/tasks/Reranking/multilingual/XGlueWPRReranking.py
- tests/test_TaskMetadata.py
Closes https://github.com/embeddings-benchmark/mteb/issues/2972
The problem was that these datasets used their own function for `data_loading` and becuase of that they weren't converted to the retrieval format
> [v2] Fix stats compute

- mteb/models/jina_models.py
Correcting the JINA models with SentenceTransformerWrapper
> Correcting the JINA models with SentenceTransformerWrapper

- .github/workflows/leaderboard_build.yml
- Makefile
- pyproject.toml
Close https://github.com/embeddings-benchmark/mteb/issues/2602
> Move dev to dependency groups

- mteb/models/voyage_models.py
Correcting the default batch size calculation in the voyage models.
> Correcting the default batch size calculation in the voyage models.

- mteb/evaluate.py
Close https://github.com/embeddings-benchmark/mteb/issues/3134
> [v2] Don't use cache with override

- mkdocs.yml
> add dark theme

- mteb/models/google_models.py
Ref https://github.com/embeddings-benchmark/mteb/issues/3188#issuecomment-3304379602
> add version check for `embeddinggemma-300m`

- mteb/_evaluators/clustering_evaluator.py
- mteb/abstasks/AbsTaskAnyClassification.py
- mteb/abstasks/AbsTaskAnyClustering.py
- mteb/abstasks/AbsTaskAnySTS.py
- mteb/abstasks/AbsTaskAnyZeroShotClassification.py
- mteb/abstasks/AbsTaskClusteringFast.py
- mteb/abstasks/AbsTaskMultilabelClassification.py
- mteb/abstasks/AbsTaskPairClassification.py
- mteb/abstasks/AbsTaskSummarization.py
- mteb/abstasks/AbsTaskTextRegression.py
- mteb/abstasks/Image/AbsTaskImageTextPairClassification.py
Close https://github.com/embeddings-benchmark/mteb/issues/3163
> [v2] Select required columns to run

- mteb/models/bmretriever_models.py
- mteb/models/instruct_wrapper.py
Close #3217
This pull request enhances the `BMRetrieverWrapper` model in `bmretriever_models.py` by adding a new `encode` method that supports eos token handling, and updates the default model revision to a newer version.
> fix: prevent EOS token truncation

- mteb/leaderboard/benchmark_selector.py
> Remove 'HUME(v1)' from leaderboard benchmark

- .github/workflows/docs.yml
- .github/workflows/documentation.yml
- mteb/benchmarks/benchmarks/benchmarks.py
- mteb/leaderboard/app.py
Change `[docs]` to `--group docs`. Fixed name of `BRIGHT(long)`
> [v2] fix ci
